### ISSUE TITLE
Message.migrate_to_chat_id is None

### ISSUE THREAD

**Issue by prepwork** [aiogram/aiogram#1000]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Ubuntu 20.04.4 LTS

### Python version

Python 3.9.5

### aiogram version

3.0b4

### Expected behavior

`Message.migrate_to_chat_id` contains `chat_id` to which chat has migrated.

### Current behavior

`Message.migrate_to_chat_id` is `None` when it must contain `chat_id` to which chat has migrated.

### Steps to reproduce

1. Create group.
2. Add bot to the group.
3. Run code in the example.
4. Change group history mode from `Hidden `to `Visible`.

### Code example

```python3
from aiogram import Bot, Dispatcher, F
from aiogram.types import Message


BOT_TOKEN = ""

bot = Bot(BOT_TOKEN)
dp = Dispatcher()


@dp.message(F.migrate_from_chat_id)
async def migrate(m: Message):
    await m.answer(
        f"migrate_from_chat_id: {m.migrate_from_chat_id}\n"
        f"migrate_to_chat_id: {m.migrate_to_chat_id}\n"
        f"chat_id: {m.chat.id}"
    )


if __name__ == '__main__':
    dp.run_polling(bot)
```

**Comment by evgfilim1** [comment]
@prepwork Hello.
When chat is migrating, `Message` will have only one of the fields filled in, but you will receive two updates together:
1. `message.chat.id = group_id`, `message.migrate_to_chat_id = supergroup_id`
2. `message.chat.id = supergroup_id`, `message.migrate_from_chat_id = group_id`

![image](https://user-images.githubusercontent.com/17182159/190617767-6df09a1a-22a2-4b2b-9d38-77711273609f.png)

Choose one that you like most and process it. That's how Bot API works, so it's not a bug in aiogram.
If you have further questions, feel free to ask in our [Telegram chat](https://t.me/aiogram).

~~P.S. Congrats with having issue #1000 :smile:~~

**Comment by prepwork** [comment]
Thanks!
