### ISSUE TITLE
`kick_chat_member` should be removed

### ISSUE THREAD

**Issue by Vermilonik** [aiogram/aiogram#1012]
### Problem

`kick_chat_member` is the same as `ban_chat_member`, but having two methods that does the same confuses: Kicking is just removing a person from a chat, and a banning is removing a person from a conversation + blacklisting him.

https://core.telegram.org/bots/api#banchatmember

### Possible solution

Deleting or changing the `kick_chat_member` method

### Additional information

This method no longer exists in Telegram Bot API

https://core.telegram.org/bots/api-changelog#june-20-2022

**Comment by bravelzt** [comment]
Don't see this method in bot.py (dev-3.x) 
<img width="1231" alt="Снимок экрана 2022-12-31 в 21 54 24" src="https://user-images.githubusercontent.com/60758749/210153248-21239b8d-06ae-4412-a4a2-8d59edd24bde.png">

**Comment by evgfilim1** [comment]
> Don't see this method in bot.py (dev-3.x)

@bravelzt That's fine, the issue is about removing `kick_chat_member` method because it's deprecated and replaced with `ban_chat_member` in Bot API
