### ISSUE TITLE
Add more updating methods to Message

### ISSUE THREAD

**Issue by gabbhack** [aiogram/aiogram#103]
Now the Message object has `edit_text` and `edit_live_location` methods and it is very convenient. However, these are not all the methods that you can use to update a message (https://core.telegram.org/bots/api#updating-messages).

I suggest adding these methods:
- edit_caption
- edit_media
- edit_reply_markup

**Comment by JrooTJunior** [comment]
Implemented in #104. Now it in `dev-2.x` branch.
