### ISSUE TITLE
editMessageMedia to message method

### ISSUE THREAD

**Issue by NiKuma0** [aiogram/aiogram#1033]
### Problem

Telegram API has editMessageMedia method and this method exist in framework why this method is missing in message class like editMessageText (as message.edit_text) and etc. ?

### Possible solution

Need to make method `message.edit_media` the same as the others.

### Code example

```python3
async def handler(m: Message):
    await m.edit_media('some_url or InputMedia')
```

**Comment by evgfilim1** [comment]
Hello. If you're talking about aiogram 3.x, then see #1030.
