### ISSUE TITLE
.get_current() typing is always "TelegramObject"

### ISSUE THREAD

**Issue by nullc4t** [aiogram/aiogram#1039]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

macOS 12.3

### Python version

3.10.7

### aiogram version

3.0.0b5

### Expected behavior

`user: User = User.get_current()` no warnings

### Current behavior

Expected type 'User', got 'TelegramObject | None' instead 

currently fixes with `user: Optional[User] = User.get_current()`

### Steps to reproduce

`user: User = User.get_current()`

**Comment by tshipenchko** [comment]
The best solution would be to solve the issue by changing only the ContextInstanceMixin or/and TelegramObject classes

**Comment by JrooTJunior** [comment]
Is not planned to improve usage of contextvars, this feature should be removed from Telegram-types in Beta 8.

Usar and Chat instances should be used explicitly.
