### ISSUE TITLE
`CallbackData` usage example

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#1042]
### aiogram version

3.x

### Problem

Let's assume I'm a newbie in aiogram. I see its awesome feature called "`CallbackQuery.data` parsing" and I don't know how to use it properly. I try to read the docs and still encounter some problems, so I need a code to compare with mine.

### Possible solution

Port and adapt `callback_data_factory` example from 2.x to 3.x. Optionally improve it with new features.

**Comment by Oleksandrigo** [comment]
https://mastergroosha.github.io/aiogram-3-guide/
I think this guide will help you

**Comment by evgfilim1** [comment]
> https://mastergroosha.github.io/aiogram-3-guide/ I think this guide will help you

This is a guide, not a solo example

**Comment by JrooTJunior** [comment]
Did you read the docs?
We have an example in the docs: https://docs.aiogram.dev/en/dev-3.x/dispatcher/filters/callback_data.html#usage

**Comment by evgfilim1** [comment]
@Oleksandrigo @JrooTJunior Sorry, I've updated the first post, so everyone will understand what I meant by creating the issue, including you. 

> This issue is more about adding an example to `examples/` directory of repo rather than the example request itself. I'm already using `CallbackData` class at its 100% potential in my projects.

I think it should be re-opened unless you don't want to add a fully working and ready-to-use example like 2.x has.
