### ISSUE TITLE
Cannot install by pip or git source

### ISSUE THREAD

**Issue by nurmians** [aiogram/aiogram#108]
---
name: Bug report
about: Cannot install aiogram
---

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu 16.04.6 LTS
* Python Version: 3.7
* aiogram version: 
* aiohttp version: 
* uvloop version (if installed): 

## Behavior
~/aiogram$ sudo python3.7 setup.py install
...
Traceback (most recent call last):
  File "setup.py", line 84, in <module>
    include_package_data=False,
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 209, in run
    os.path.join(archive_root, 'EGG-INFO'), self.zip_safe()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 245, in zip_safe
    return analyze_egg(self.bdist_dir, self.stubs)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 355, in analyze_egg
    safe = scan_module(egg_dir, base, name, stubs) and safe
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 392, in scan_module
    code = marshal.load(f)
ValueError: bad marshal data (unknown type code)

# --------------------------

~/aiogram$ pip3 install aiogram

Collecting aiohttp>=3.4.4 (from aiogram)
  Could not find a version that satisfies the requirement aiohttp>=3.4.4 (from aiogram) (from versions: 0.1, 0.2, 0.3, 0.4, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.10.0, 0.10.1, 0.10.2, 0.11.0, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1, 0.14.2, 0.14.3, 0.14.4, 0.15.0, 0.15.1, 0.15.2, 0.15.3, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.16.4, 0.16.5, 0.16.6, 0.17.0, 0.17.1, 0.17.2, 0.17.3, 0.17.4, 0.18.0, 0.18.1, 0.18.2, 0.18.3, 0.18.4, 0.19.0, 0.20.0, 0.20.1, 0.20.2, 0.21.0, 0.21.1, 0.21.2, 0.21.4, 0.21.5, 0.21.6, 0.22.0a0, 0.22.0b0, 0.22.0b1, 0.22.0b2, 0.22.0b3, 0.22.0b4, 0.22.0b5, 0.22.0b6, 0.22.0, 0.22.1, 0.22.2, 0.22.3, 0.22.4, 0.22.5, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.5, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6, 1.2.0, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.6.post1, 2.0.7, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.3.0a1, 2.3.0a2, 2.3.0a4, 2.3.0, 2.3.1a1, 2.3.1, 2.3.2b2, 2.3.2b3, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.3.10, 3.0.0b0)
No matching distribution found for aiohttp>=3.4.4 (from aiogram)

**Comment by JrooTJunior** [comment]
Something strange but it works for me

### Virtual environment:
``` bash
jrootjunior@JRjWorkStation:/tmp/installaiogram$ virtualenv -p python .env
Already using interpreter /usr/bin/python
Using base prefix '/usr'
/usr/lib/python3.7/site-packages/virtualenv.py:1041: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
New python executable in /tmp/installaiogram/.env/bin/python
Installing setuptools, pip, wheel...done.
```
### Install
``` bash
jrootjunior@JRjWorkStation:/tmp/installaiogram$ source .env/bin/activate
(.env) jrootjunior@JRjWorkStation:/tmp/installaiogram$ pip install aiogram
Collecting aiogram
  Using cached https://files.pythonhosted.org/packages/8c/13/4aa3e655b4e508d9db2f3867d4891badbaf5db2ed28bb7fed2814044a5ed/aiogram-2.0.1-py3-none-any.whl
Collecting certifi>=2018.8.24 (from aiogram)
  Downloading https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl (158kB)
    100% |████████████████████████████████| 163kB 2.7MB/s 
Collecting aiohttp>=3.4.4 (from aiogram)
  Using cached https://files.pythonhosted.org/packages/33/60/c21acb7002110699761d3dec36fad3f5087c2752a4eb495444f877db6553/aiohttp-3.5.4-cp37-cp37m-manylinux1_x86_64.whl
Collecting Babel>=2.6.0 (from aiogram)
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Collecting yarl<2.0,>=1.0 (from aiohttp>=3.4.4->aiogram)
Collecting async-timeout<4.0,>=3.0 (from aiohttp>=3.4.4->aiogram)
  Using cached https://files.pythonhosted.org/packages/e1/1e/5a4441be21b0726c4464f3f23c8b19628372f606755a9d2e46c187e65ec4/async_timeout-3.0.1-py3-none-any.whl
Collecting multidict<5.0,>=4.0 (from aiohttp>=3.4.4->aiogram)
  Using cached https://files.pythonhosted.org/packages/88/f0/4d4cbd1a3744e3985efa49682352d0703df653ffa76b81f10fed86599a50/multidict-4.5.2-cp37-cp37m-manylinux1_x86_64.whl
Collecting attrs>=17.3.0 (from aiohttp>=3.4.4->aiogram)
  Downloading https://files.pythonhosted.org/packages/23/96/d828354fa2dbdf216eaa7b7de0db692f12c234f7ef888cc14980ef40d1d2/attrs-19.1.0-py2.py3-none-any.whl
Collecting chardet<4.0,>=2.0 (from aiohttp>=3.4.4->aiogram)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting pytz>=0a (from Babel>=2.6.0->aiogram)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Collecting idna>=2.0 (from yarl<2.0,>=1.0->aiohttp>=3.4.4->aiogram)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Installing collected packages: certifi, multidict, idna, yarl, async-timeout, attrs, chardet, aiohttp, pytz, Babel, aiogram
Successfully installed Babel-2.6.0 aiogram-2.0.1 aiohttp-3.5.4 async-timeout-3.0.1 attrs-19.1.0 certifi-2019.3.9 chardet-3.0.4 idna-2.8 multidict-4.5.2 pytz-2018.9 yarl-1.3.0
```
### Collect information
``` bash
(.env) jrootjunior@JRjWorkStation:/tmp/installaiogram$ python -m aiogram
CPython: 3.7.2 (default, Jan 10 2019, 23:51:51) [GCC 8.2.1 20181127]
OS: Linux-4.20.7-arch1-1-ARCH-x86_64-with-arch
aiogram: 2.0.1
aiohttp: 3.5.4
JSON mode: json
```

**Comment by JrooTJunior** [comment]
Can you provide more information?
How did you install python? I think you installation is partially broken
