### ISSUE TITLE
Can't send message

### ISSUE THREAD

**Issue by justNice** [aiogram/aiogram#1084]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 10

### Python version

3.11

### aiogram version

aiogram==2.23.1

### Expected behavior

The bot should send a message.

### Current behavior

I get error

### Steps to reproduce

I want to send message with this text using markdown: 
![image](https://user-images.githubusercontent.com/53212206/208992362-4cd234fa-b327-49ac-9e63-b126135cb351.png)

But i can't send it and get error `Can't parse entities: can't find end of the entity starting at byte offset 28`

### Code example

```python3
tg_bot.send_message(1120747687, "Username: `JustReaper\`#4444`", parse_mode="MarkDown")
```

**Comment by Olegt0rr** [comment]
Try to use `parse_mode="MarkdownV2"`
