### ISSUE TITLE
python-telegram-bot-pagination does not work with 3.x version aiogram

### ISSUE THREAD

**Issue by macros0** [aiogram/aiogram#1089]
### aiogram version

3.x

### Problem

I am just learning. I wrote my bot, on the 2nd version of iogram using the library https://github.com/ksinn/python-telegram-bot-pagination, everything works. Tried to upgrade to version 3, ran into a problem: json generated by python-telegram-bot-pagination is not converted to InlineKeyboardMarkup class, as it worked before in version 2. 

### Possible solution

Changing the base model of InlineKeyboardMarkup class

### Code example

My example for version 2 of iogram is work: https://github.com/ksinn/python-telegram-bot-pagination/pull/11
Code for 3.x does not work
```python3
import asyncio
from aiogram import Bot, Dispatcher, F
from aiogram.types import Message, CallbackQuery, InlineKeyboardButton
from telegram_bot_pagination import InlineKeyboardPaginator
from data import character_pages

bot = Bot(token="TOKEN")
dp = Dispatcher()
logging.basicConfig(level=logging.INFO)


async def send_character_page(msg, page=1):
    paginator = InlineKeyboardPaginator(
        len(character_pages),
        current_page=page,
        data_pattern='character#{page}'
    )
    paginator.add_before(
        InlineKeyboardButton(text='Like', callback_data='like#{}'.format(page)),
        InlineKeyboardButton(text='Dislike', callback_data='dislike#{}'.format(page))
    )
    paginator.add_after(InlineKeyboardButton(text='Go back', callback_data='back'))
    await bot.send_message(
        msg.chat.id,
        character_pages[page-1],
        reply_markup=paginator.markup,
        parse_mode='Markdown'
    )


async def characters_page_callback(query: CallbackQuery):
    bot: Bot = query.bot
    page = int(query.data.split('#')[1])
    await bot.delete_message(
        query.message.chat.id,
        query.message.message_id
    )
    await send_character_page(query.message, page)


async def get_character(msg: Message):
    await send_character_page(msg)


async def main():
    dp.callback_query.register(characters_page_callback, lambda c: c.data.split('#')[0]=='character')
    dp.message.register(get_character, F.text)
    await dp.start_polling(bot, allowed_updates=dp.resolve_used_update_types())

if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by macros0** [comment]
Code for 3.x
import logging
import asyncio
from aiogram import Router, F
from aiogram.filters.text import Text
from aiogram import Bot, Dispatcher, types
from aiogram.types import Message, CallbackQuery, ReplyKeyboardRemove
from aiogram.types import ReplyKeyboardMarkup, KeyboardButton, InlineKeyboardMarkup, InlineKeyboardButton, WebAppInfo

from telegram_bot_pagination import InlineKeyboardPaginator
from data import character_pages

# Объект бота
bot = Bot(token="TOKEN")
# Диспетчер для бота
#dp = Dispatcher(bot)
dp = Dispatcher()
logging.basicConfig(level=logging.INFO)
router = Router()


async def send_character_page(msg, page=1):
#    bot: Bot = msg.bot
    paginator = InlineKeyboardPaginator(
        len(character_pages),
        current_page=page,
        data_pattern='character#{page}'
    )

    paginator.add_before(
        InlineKeyboardButton(text='Like', callback_data='like#{}'.format(page)),
        InlineKeyboardButton(text='Dislike', callback_data='dislike#{}'.format(page))
    )
    paginator.add_after(InlineKeyboardButton(text='Go back', callback_data='back'))

    await bot.send_message(
        msg.chat.id,
        character_pages[page-1],
        reply_markup=paginator.markup,
        parse_mode='Markdown'
    )


async def characters_page_callback(query: CallbackQuery):
    bot: Bot = query.bot

    page = int(query.data.split('#')[1])
    await bot.delete_message(
        query.message.chat.id,
        query.message.message_id
    )
    await send_character_page(query.message, page)


async def get_character(msg: Message):
    await send_character_page(msg)


async def main():
    # Запуск бота
#    dp.register_callback_query_handler(characters_page_callback, lambda c: c.data.split('#')[0]=='character')
    dp.callback_query.register(characters_page_callback, lambda c: c.data.split('#')[0]=='character')
#    dp.register_message_handler(get_character, content_types=['text'])
    dp.message.register(get_character, F.text)
    #    executor.start_polling(dp, skip_updates=True,
    #                           timeout=2000, reset_webhook=None, fast=True)
    await dp.start_polling(bot, allowed_updates=dp.resolve_used_update_types())


if __name__ == "__main__":
#    main()
    asyncio.run(main())

**Comment by Finzky** [comment]
try to use `reply_markup=json.loads(paginator.markup)`

**Comment by Forden** [comment]
Why would aiogram guarantee compatibility with some third-party libs created for other telegram frameworks?

**Comment by evgfilim1** [comment]
> Why would aiogram guarantee compatibility with some third-party libs created for other telegram frameworks?

@Forden If I understood correctly, it tries to be kinda universal by returning a json string for the corresponding inline keyboard markup. Also, there's a PR open to add aiogram 2.x working example, it's mentioned in first post here.
As 3.x is using pydantic, it's strict for data types checking, the model expects an object, so this doesn't work, but for 2.x it does. I don't think it's an issue on our side, it can be workarounded anyway, but I'd like to hear an opinion from other devs.

**Comment by evgfilim1** [comment]
> try to use `reply_markup=json.loads(paginator.markup)`

@Finzky This still won't work, but you're close to the solution.

@macros0 Try this: `reply_markup=InlineKeyboardMarkup.parse_raw(paginator.markup)`. [What is `.parse_raw(...)`?](https://docs.pydantic.dev/usage/models/#helper-functions)

**Comment by macros0** [comment]
> Try this: `reply_markup=InlineKeyboardMarkup.parse_raw(paginator.markup)`.

Thank you! It works for me.
The error can be closed apparently, because the solution is simple, the problem is my inexperience in Python development.

**Comment by Finzky** [comment]
> > try to use `reply_markup=json.loads(paginator.markup)`
> 
> @Finzky This still won't work, but you're close to the solution.

hmm, but it works fine for me (aiogram 3) 🤷🏽‍♂️🧐
