### ISSUE TITLE
Adding timeout for Bot API methods.

### ISSUE THREAD

**Issue by Forden** [aiogram/aiogram#109]
**Is your feature request related to a problem? Please describe.**
The problem is that Bot API doesn't send any errors, if bot got limited with some methods, like delete_message. Example code:
```
l=[(i, -1000-i) for i in range(1000)]
for i in l:
   try:
      await bot.delete_message(message_id=max(i), chat_id=min(i))
   except Exception:
       pass
```

If there are no `await asyncio.sleep()`, a bot will freeze after deleting ~700-800 msgs. No exceptions will raise, but the process will be completely blocked.

**Describe the solution you'd like**
The best way to solve this problem is by adding timeout for every method, e.g. in `aiogram.Bot` params. 

**Additional context**
[Example](https://t.me/aiogram_ru/44012): `INFO:bot:Process update [ID:711526853]: [success] (in 15379 ms)`

**Comment by JrooTJunior** [comment]
beca19b5e23d215aff86f6f241eefe32ceee5c4b

**Comment by JrooTJunior** [comment]
Now you'r example can be changed to:
``` python3
with bot.request_timeout(1):
    for i in [(i, -1000 - i) for i in range(1000)]:
        try:
            await bot.delete_message(message_id=max(i), chat_id=min(i))
        except Exception:
            pass
```

**Comment by JrooTJunior** [comment]
Already in latest release (v2.1)
