### ISSUE TITLE
can't get data from forum_topic_created in message 

### ISSUE THREAD

**Issue by Aleksey2006** [aiogram/aiogram#1090]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 7

### Python version

3.9.12

### aiogram version

2.24

### Expected behavior

@dp.message_handler()
async def message(message: types.Message):
        print(message)
>>> {"message_id":21,"from":{"id":100636,"is_bot":false,"first_name":"Алексей","last_name":"Чебанюк","language_code":"ru"},"chat":{"id":-10018737,"title":"moderator_test","is_forum":true,"type":"supergroup"},"date":167068,"message_thread_id":2,"reply_to_message":{"message_id":2,"from":{"id":10069,"is_bot":false,"first_name":"Алексей","last_name":"Чебанюк","language_code":"ru"},"chat":{"id":-1001893242737,"title":"moderator_test","is_forum":true,"type":"supergroup"},"date":167700,"message_thread_id":2
,"forum_topic_created":{"name":"Test team","icon_color":13338331,"icon_custom_emoji_id":"5348436127038579546"},"is_topic_message":true},"text":"gfg","is_topic_message":true}

        print(message.forum_topic_created.name)
>>> Test team

### Current behavior

        print(message.forum_topic_created.name)

>>> AttributeError: 'NoneType' object has no attribute 'name'

### Steps to reproduce

get message from supergroup with topic

**Comment by JrooTJunior** [comment]
Note that your example is not suitable for handling any message types other than text:
```python
@dp.message_handler()
```

Because by default this handler has content_types=["text"] filter, but forum topic created event is not a text message.
