### ISSUE TITLE
Middleware documentation

### ISSUE THREAD

**Issue by Ganzeroar** [aiogram/aiogram#1101]
### aiogram version

2.x

### Problem

There is no documentation about middlewares

### Possible solution

I guess i can try to write some dosc

### Additional information

This was a long path which I took while understanding how to do middleware for callback queries. All documentation about it now is "Coming soon...". But in research I found keywords for middleware like "pre_process_", "process_"  and "post_process_". After it in "dispatcher.py" I found strings with "middleware_key" which told me the meaning of comment in BaseMiddleware "All methods on the middle always must be coroutines and name starts with "on_" like "on_process_message".
So, I think, maybe I can make some part of documentation about middlewares?
But I suppose that the middleware theme is rather bigger and if someone tells a list of themes, that I need to understand for writing docs, I will do that.

**Comment by JrooTJunior** [comment]
I don't think so the improvement of 2.x documentation is needed in due to the release of the 3.x version is coming, where it is already documented: https://docs.aiogram.dev/en/dev-3.x/dispatcher/middlewares.html

If you want to help me, you can improve 3.x documentation.
