### ISSUE TITLE
Documentation mistake for PreCheckoutQuery type.

### ISSUE THREAD

**Issue by iamnalinor** [aiogram/aiogram#1103]
### Checklist

- [x] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11 21H2

### Python version

3.11.1

### aiogram version

2.24

### Expected behavior

When I open documentation for [types.PreCheckoutQuery](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/pre_checkout_query.py) class, it should contain docstring as provided in [Bot API documentation](https://core.telegram.org/bots/api#precheckoutquery).

### Current behavior

When I open documentation for [types.PreCheckoutQuery](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/pre_checkout_query.py) class, I see text in docstring about HTML5 games which is not related to Telegram Payments and `PreCheckoutQuery` type.

### Steps to reproduce

1. Open [source code](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/pre_checkout_query.py) for PreCheckoutQuery type.
2. Open official Bot API [documentation](https://core.telegram.org/bots/api#precheckoutquery).
3. Check that docstring in code and description in documentation do not match as they should be.

### Additional information

This is also reproduced when I open documentation on [docs.aiogram.dev](https://docs.aiogram.dev/en/latest/telegram/types/pre_checkout_query.html) in the browser

**Comment by JrooTJunior** [comment]
Stale issue

v2.x will no longer be supported in due to 3.0 is coming
