### ISSUE TITLE
InlineQueryResultCachedPhoto has no title

### ISSUE THREAD

**Issue by PraryDogy** [aiogram/aiogram#1105]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Mac Os 10.15.7 (Catalina)

### Python version

3.7.3

### aiogram version

2.24

### Expected behavior

InlineQueryResultCachedPhoto with title and description in inline mode.

### Current behavior

InlineQueryResultCachedPhoto has no title and description, in same time InlineQueryResultPhoto has title and description.

### Steps to reproduce

- Create InlineQueryResultCachedPhoto object with id, title, description and photo_file_id
- Create InlineQueryResultPhoto obj with id, title, description, thumb URL, img URL
- Start polling
- Call bot @bot_name and you will see menu with photo, but without any text.
- In same time InlineQueryResultPhoto has title and description
![Screenshot 2023-01-22 at 19 52 23](https://user-images.githubusercontent.com/90144260/213929374-e12162a6-a754-4652-8857-6ea5cf8fd54d.png)

### Code example

```python3
InlineQueryResultPhoto(
        id=hashlib.md5('any'.encode()).hexdigest(),
        photo_url='any image URL',
        thumb_url='any image URL',
        title='any title',
        description='any description',
        )

InlineQueryResultCachedPhoto(
        id=hashlib.md5('any_cached'.encode()).hexdigest(),
        photo_file_id='any photo file id',
        title='any title cached',
        description='any description cached'
    )
```

**Comment by JrooTJunior** [comment]
> ### Checklist
> * [x]  I am sure the error is coming from aiogram code

This issue is coming not from  aiogram code, that is server- or client-side behavior.
