### ISSUE TITLE
Filter Command ignores parameter ignore_case

### ISSUE THREAD

**Issue by sheldygg** [aiogram/aiogram#1106]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 10

### Python version

3.10.9

### aiogram version

3.0.0b6

### Expected behavior

The bot must respond to the command /TEST

### Current behavior

The bot does not respond to the command /TEST

### Steps to reproduce

1. Copy code
2. Install aiogram==3.0.0b6
3. Insert bot token
4. Run file

### Code example

```python3
import logging

from aiogram import Bot, Dispatcher
from aiogram.filters import Command
from aiogram.types import Message

TOKEN = ""
dp = Dispatcher()

logging.basicConfig(level=logging.DEBUG)

@dp.message(Command(commands=["test"], ignore_case=True))
async def command_start_handler(message: Message) -> None:
    await message.reply("True")
    
def main() -> None:
    # Initialize Bot instance with an default parse mode which will be passed to all API calls
    bot = Bot(TOKEN, parse_mode="HTML")
    # And the run events dispatching
    dp.run_polling(bot)


if __name__ == "__main__":
    main()
```

### Logs

```sh
INFO:aiogram.event:Update id=****** is not handled. Duration 0 ms by bot id=*******
```

**Comment by JrooTJunior** [comment]
Fixed in Beta 7, will be released soon.
