### ISSUE TITLE
Use content_types will found Undefined variable issue

### ISSUE THREAD

**Issue by YokerDan** [aiogram/aiogram#111]
```
@dp.message_handler(commands=['command'], content_types=ContentType.TEXT)
async def Sticker_handler(message: types.Message):
        await message.reply('test01')
```

**Comment by JrooTJunior** [comment]
Can you provide more information?

**Comment by JrooTJunior** [comment]
Need more information. I copy and paste your example and this code is works for me

![image](https://user-images.githubusercontent.com/6726423/55682701-b0785a80-593f-11e9-9114-45382fbd0e8b.png)

Can you provide exception traceback?

**Comment by YokerDan** [comment]
Thanks 
I found something error 
But i fix that 
And I have other questions 
How can I handle stickers or files?

**Comment by JrooTJunior** [comment]
Use content types

## Examples:
### Handle stickers 
``` python3
@dp.message_handler(content_types=ContentType.STICKER)
```

### Handle photos 
``` python3
@dp.message_handler(content_types=ContentType.PHOTO)
```

### Handle photos and documents
``` python3
@dp.message_handler(content_types=ContentTypes.VIDEO & ContentTypes.VIDEO_NOTE)
```
In this example used ContentType**s** instead of ContentType
