### ISSUE TITLE
register_errors_handler don't catch TerminatedByOtherGetUpdates

### ISSUE THREAD

**Issue by igmorozkin** [aiogram/aiogram#1115]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Mac OS Monretey 12.5.1 (21G83)

### Python version

python3.11

### aiogram version

aiogram 2.25.1

### Expected behavior

I want to catch the error `TerminatedByOtherGetUpdates` To do this I use `dp.register_errors_handler`. However, it doesn't catch this type of error (User can create a bot clone, but apparently ignores warnings about two instances in my project)

### Current behavior

The register_errors_handler should catch an error with the type TerminatedByOtherGetUpdates, so I can stop the bot

### Steps to reproduce

1. Create first instance
2. Create second instance
3. Wait until Telegram starts sending errors about the inability to launch two bot instances

### Code example

```python3
import asyncio

from aiogram import Bot, Dispatcher
from aiogram.utils.exceptions import TerminatedByOtherGetUpdates

TOKEN='...'

async def on_handle_terminate(update, error):
    print('Hadnle terminate, Stopping bot...')

bot = Bot(token=TOKEN)
dp = Dispatcher(bot)
dp.register_errors_handler(callback=on_handle_terminate,
                           exception=TerminatedByOtherGetUpdates)

async def main():
    await dp.start_polling()

if __name__ == '__main__':
    asyncio.run(main())
```

### Logs

```sh
Cause exception while getting updates.
Traceback (most recent call last):
  File "/Users/admin/Downloads/aiogram-handler-bug/venv/lib/python3.11/site-packages/aiogram/dispatcher/dispatcher.py", line 381, in start_polling
    updates = await self.bot.get_updates(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Downloads/aiogram-handler-bug/venv/lib/python3.11/site-packages/aiogram/bot/bot.py", line 110, in get_updates
    result = await self.request(api.Methods.GET_UPDATES, payload)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Downloads/aiogram-handler-bug/venv/lib/python3.11/site-packages/aiogram/bot/base.py", line 236, in request
    return await api.make_request(await self.get_session(), self.server, self.__token, method, data, files,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Downloads/aiogram-handler-bug/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 140, in make_request
    return check_result(method, response.content_type, response.status, await response.text())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Downloads/aiogram-handler-bug/venv/lib/python3.11/site-packages/aiogram/bot/api.py", line 119, in check_result
    exceptions.ConflictError.detect(description)
  File "/Users/admin/Downloads/aiogram-handler-bug/venv/lib/python3.11/site-packages/aiogram/utils/exceptions.py", line 140, in detect
    raise err(cls.text or description)
aiogram.utils.exceptions.TerminatedByOtherGetUpdates: Terminated by other getupdates request; make sure that only one bot instance is running
```

### Additional information

provided by previous messages

**Comment by JrooTJunior** [comment]
Error handler can handle only exceptions that coming from event handlers, but TerminatedByOtherGetUpdates exception is coming from polling process (is not handler), so that's mean you can't handle it in this way and should not expect that such kind of errors will be propagated to errors handler.

The another point that is this error means you hanve already running process with current bot token and should not perform any additional actions from current process.

Also you can't (and shouldn't) stop the application from any handler, because it's not theirs responsibility.

**Comment by igmorozkin** [comment]
> 



> you can't handle

Then how do I catch the error? User can ignore the message, and run a second bot instance. That would be fine, but there are too many garbage messages in logs

**Comment by Olegt0rr** [comment]
You shouldn't catch this error.
You should make this error never happen.
If you you run a new app, don't forget to close previous.
And if you still wanna suppress the error, use `try/except` or `contextlib.suppress` statement around `start_polling` method

**Comment by lilydjwg** [comment]
>  You should make this error never happen.

Except when I can't. My use case is this: I have an important bot running on a server. Someday the server went offline and didn't come back soon. I had to run it on another server. Days after, the previous server comes back online, and starts fighting with my new bot instance. So I want either of them to stop.
