### ISSUE TITLE
KeyboardButtonRequestUser makes a chat request instead of a user request

### ISSUE THREAD

**Issue by hittiks** [aiogram/aiogram#1130]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 10 Pro

### Python version

3.8.10

### aiogram version

2.25.1

### Expected behavior

By clicking button bot request a user (bot or human) like in intro:

![image](https://user-images.githubusercontent.com/58007224/219555937-43424968-59fc-4b16-bfef-51dc9399cdc1.png)

### Current behavior

By clicking button bot request a chat (channel or group) like this:

![image](https://user-images.githubusercontent.com/58007224/219556254-162968fc-02aa-4e70-9bd2-530d8e7c003c.png)

or this:

![image](https://user-images.githubusercontent.com/58007224/219560241-7df21223-917a-4aa4-ab3f-d3f11084810f.png)

### Steps to reproduce

1. Run code.
2. Send some text to bot.
3. Click by one of buttons (test1 or test2).
4. Have incorrect request...

### Code example

```python3
from aiogram import Bot as AiogramBot, Dispatcher, executor, types
from aiogram.utils import deep_linking
from aiogram.types.reply_keyboard import ReplyKeyboardMarkup, KeyboardButton, KeyboardButtonRequestUser


bot = AiogramBot(config.BOT_TOKEN)
dp = Dispatcher(bot)


@dp.message_handler(content_types=['text'])
async def text_handler(message: types.Message):
    await message.answer("I'm here", reply_markup=ReplyKeyboardMarkup(
        [
            [
                KeyboardButton("test1", request_chat=KeyboardButtonRequestUser(1, user_is_bot=True)),
                KeyboardButton("test2", request_chat=KeyboardButtonRequestUser(2, user_is_bot=False)),
            ]
        ]
    ))


if __name__ == "__main__":
    executor.start_polling(dp)

```
```


### Logs

_No response_

### Additional information

I'm 100% sure, that I not use KeyboardButtonRequestChat.
Also error occurs both in pc and phone tg app, so chance that error in client app is minimum

**Comment by Olegt0rr** [comment]
Make sure that you pass `KeyboardButtonRequestUser` object to correct kwarg of `KeyboardButton` :)

**Comment by hittiks** [comment]
Ohh, I'm so sorry, I understand my fail...
