### ISSUE TITLE
Error handler registration in the router, responds to errors in other routers

### ISSUE THREAD

**Issue by WilliamQosmos** [aiogram/aiogram#1149]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: MacOS 13.2.1 (22D68)
* Python Version: 3.10
* aiogram version: 3.0.0b7
* aiohttp version: 3.8.4

## Expected Behavior

Catching errors only in the handlers of the router in which the error handler is registered

## Current Behavior

When registering an error handler inside the router, the handler reacts to all error events

**Comment by JrooTJunior** [comment]
This is expected behavior.

The errors coming from handlers handles inside first outer update middleware in dispatcher and propagates to all nested routers.
