### ISSUE TITLE
What is the difference between message.reply and message.answer. Such a confusing use of words

### ISSUE THREAD

**Issue by Suaralanre** [aiogram/aiogram#1153]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu LTS 22.04
* Python Version: 3.10
* aiogram version:
* aiohttp version:
* uvloop version (if installed):

I can't seem to understand the difference between the two. The quick start tutorial just glossed over it.

**Comment by barabane** [comment]
When you using **message.reply**, bot reply on the last user's message 
Example:
![image](https://user-images.githubusercontent.com/116812464/230274972-c02c2a7d-44e3-4060-9d96-9a14f22d2942.jpeg)

But, when you using **message.answer**, bot just send message
Example: 
![image](https://user-images.githubusercontent.com/116812464/230275385-a382db9a-d378-450a-814e-626843c0dcd7.jpeg)

**Comment by Suaralanre** [comment]
Thanks @barabane . I kinda wondered if they could have just used .send_message like other libraries. That's less ambiguous honestly.
