### ISSUE TITLE
Traceback when calling get_chat_menu_button

### ISSUE THREAD

**Issue by m0wer** [aiogram/aiogram#1174]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Debian GNU/Linux 11 (bullseye)
* Python Version: Python 3.11.1
* aiogram version: 2.25.1
* aiohttp version: aiohttp==3.8.4
* uvloop version (if installed): -

## Expected Behavior

No traceback, just the function normal return value.

## Current Behavior

```python
  File ".../main.py", line 849, in echo
    menu_button = await bot.get_chat_menu_button()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/aiogram/bot/bot.py", line 3026, in get_chat_menu_button
    return types.MenuButton.resolve(**result)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/aiogram/types/menu_button.py", line 40, in resolve
    return class_(**kwargs)
           ^^^^^^^^^^^^^^^^
  File ".../lib/python3.11/site-packages/aiogram/types/menu_button.py", line 78, in __init__
    super().__init__(type='default', **kwargs)
TypeError: aiogram.types.base.TelegramObject.__init__() got multiple values for keyword argument 'type'
```

## Failure Information (for bugs)

Also fails when passing a `chat_id` to `get_chat_menu_button`.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Install the described versions.
2. After initializing the bot in polling, run `await bot.get_chat_menu_button()`.
3. You should get the traceback.

**Comment by JrooTJunior** [comment]
Confirmed. Can you please fix it and create pull request?

**Comment by m0wer** [comment]
> Confirmed. Can you please fix it and create pull request?

It was just for some small change. I worked around it by using the API directly. Since it's not something I need I don't plan on fixing it.

Thanks for the great library!

**Comment by JrooTJunior** [comment]
v2 will no more be supported, i will close this issue.
