### ISSUE TITLE
Why is the structure of text formatting files so illogical?

### ISSUE THREAD

**Issue by NiKuma0** [aiogram/aiogram#1179]
**For now we have this:**
```
aiogram/
|__ utils/
    |__ markdown.py  # Why markdown? In this file we also have html 
    |__ text_decorations.py  # In telegram docs this is called formatting
```

**My suggestions is:**
```
aiogram/
|__ utils/
    |__ formatting/
        |__ markdown.py
        |__ html.py  # Split the markdown.py file into two parts
        |__ models,py  # old text_decorations.py, but idk about naming. 
``` 
This is not perfect, but it is more logical, so I am open to discussion.

**Comment by JrooTJunior** [comment]
`markdown.py` is historical artifact and will be removed soon (i think after grand release), more details in #1167
It will be replaced with `formatting` util (introduced by #1172)
