### ISSUE TITLE
Not able to receive post with photos from channel_post_handler 

### ISSUE THREAD

**Issue by fuyarchuk-kg** [aiogram/aiogram#1180]
Hi! May be I am doing something wrong, but I can only receive text posts with this handler:

@dp.channel_post_handler()
async def new_post(message):
    print('Received new post!')
    print(message.photo)
    print(message.text)

executor.start_polling(dp, skip_updates=False)

If I post text with phot as one post I don't get updates(

**Comment by JrooTJunior** [comment]
By default content type "text" is applied, if you want to receive any other message type just specify content type in filters, for example:
`@dp.channel_post_handler(content_types=ContentType.PHOTO)`

**Comment by fuyarchuk-kg** [comment]
> By default content type "text" is applied, if you want to receive any other message type just specify content type in filters, for example: `@dp.channel_post_handler(content_types=ContentType.PHOTO)`

Absolutely! It works! Thanks a lot!

**Comment by JrooTJunior** [comment]
Media rgoup is a set of different messages, so, you can't handle it as single event out of the box, but you can do it by yourself.
