### ISSUE TITLE
Event Logging Middleware. 

### ISSUE THREAD

**Issue by NiKuma0** [aiogram/aiogram#1181]
**3.x version**

**Is your feature request related to a problem? Please describe.**
I can't make the event logging more verbose or/and different format.

**Describe the solution you'd like**
Add the event logging middleware. I have this one and it works fine:
```python
class LoggerMiddleware(BaseMiddleware):
    async def __call__(self, handler, update, data):
        loop = asyncio.get_running_loop()
        start_time = loop.time()
        handled = False
        try:
            result = await handler(update, data)
            handled = result is not UNHANDLED
            return result
        finally:
            duration = (loop.time() - start_time) * 1000
            self._logger.info(
                "Update id=%s is %s. Duration %d ms by bot id=%d",
                update.update_id,
                "handled" if handled else "not handled",
                duration,
                data["bot"].id,
            )
```
![image](https://github.com/aiogram/aiogram/assets/78080842/e7f1524f-efb7-4e38-b9bd-31146566c21a)
As you can see there are two logs from aiogram and my application. So my solution is to make only middleware and remove old logging.

**Comment by JrooTJunior** [comment]
You can disable `aiogram.event` logger and use your own middleware for logging.

But if you want to always correctly log all events the logging layer should be as early as possible, ideally the first level in the processing chain (as you can see in current implementation).

**Comment by NiKuma0** [comment]
> But if you want to always correctly log all events the logging layer should be as early as possible, ideally the first level in the processing chain (as you can see in current implementation).

I see your point. But in my test, the difference is only 2ms, and I used some other custom middleware. If you put this middleware in the __init__ method of the `Dispatcher` class, the duration time would be acceptable to users of this library and, more importantly, they will be able to modify this logging without any problem.

**Comment by JrooTJunior** [comment]
As i says previously, you can do it by yourself, just disable logger and use your own middleware.
