### ISSUE TITLE
`USER_IN_THREAD` requires `is_topic_message`

### ISSUE THREAD

**Issue by Desiders** [aiogram/aiogram#1186]
## Expected Behavior

A thread isn’t necessarily a topic, so [`FSMStrategy::USER_IN_THREAD`](https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/fsm/strategy.py#L9) is expected that it can be topic or no

## Current Behavior

[`FSMStrategy::USER_IN_THREAD`](https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/fsm/strategy.py#L9) requires be [`is_topic_message`](https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/dispatcher/middlewares/user_context.py#L41). Now it's more like on `USER_IN_TOPIC`.

**Comment by JrooTJunior** [comment]
Thanks.
I renamed it to USER_IN_TOPIC.
