### ISSUE TITLE
class Text(Filter) 

### ISSUE THREAD

**Issue by attid** [aiogram/aiogram#1199]
class Text(Filter):

описание 
        :param contains: Text contains value or one of values
        :param startswith: Text starts with value or one of values
        :param endswith: Text ends with value or one of values

а на деле 
        if self.contains is not None:
            contains = map(self.prepare_text, self.contains)
            return **all**(map(text.contains, contains))

т.е. или описание не верное или код 😬

**Comment by JrooTJunior** [comment]
1. Be respectful, use English on this repository.
2. This filter was removed in 3.0b8
