### ISSUE TITLE
Can't send /proc/self/*

### ISSUE THREAD

**Issue by hikariatama** [aiogram/aiogram#1206]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux
* Python Version: 3.11
* aiogram version: 2.19
* aiohttp version: 3.8.3
* uvloop version (if installed): -

## Expected Behavior

The file `/proc/self/cmdline` is being sent, as well as any other file from `/proc`

## Current Behavior

The process hangs

## Failure Information (for bugs)

-

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

```python
bot.send_document(<chat_id>, "/proc/self/cmdline")
```

### Failure Logs

-

**Comment by hikariatama** [comment]
After a certain amount of time, `aiogram.utils.exceptions.TelegramAPIError: Gateway Timeout` is being raised

**Comment by JrooTJunior** [comment]
This caused in due to you are trying to send files in a incorrect way
You can't put path to file directly as a file_id (just look at Telegram Bot API documetation)
getaway timeout means that caused an server error, not on our side

**Comment by hikariatama** [comment]
> This caused in due to you are trying to send files in a incorrect way You can't put path to file directly as a file_id (just look at Telegram Bot API documetation) getaway timeout means that caused an server error, not on our side

If I use the same approach with other files (common ones), it works fine. The issue appears only when I try to send `/proc/self/*`
