### ISSUE TITLE
Aiogram ReplyKeyboardMarkup does not have the optional option "is_persistent"

### ISSUE THREAD

**Issue by officialbishowb** [aiogram/aiogram#1212]
* Operating System: Windows 10
* Python Version: Python 3.11.3
* aiogram version: 2.23.1
* aiohttp version: 3.8.4
* uvloop version (if installed): / 

## Expected Behavior

The `ReplyKeyboardMarkup` class should have the `is_persistent` keyword which can be found on the [Telegram Bot API](https://core.telegram.org/bots/api#replykeyboardmarkup) and the [Aiogram documentation](https://docs.aiogram.dev/en/latest/telegram/types/reply_keyboard.html?highlight=ReplyKeyboardMarkup#replykeyboardmarkup).

## Current Behavior

When I try to use the `is_persistent` on my Bot with the Aiogram module, the option does not appear.

![image](https://github.com/aiogram/aiogram/assets/55999477/b626f589-2bb2-4139-ae37-7b43b1043084)
![image](https://github.com/aiogram/aiogram/assets/55999477/64a15970-344f-4315-8513-36524111822a)

**Comment by JrooTJunior** [comment]
v2 will no more be supported, please migrate to v3
