### ISSUE TITLE
Webhook start_webhook() not working in async

### ISSUE THREAD

**Issue by greatUzumaki** [aiogram/aiogram#1219]
The code is completely copied from the documentation.
https://docs.aiogram.dev/en/latest/examples/webhook_example.html
All requests go sequentially, checked with asyncio.sleep()

* Operating System: Windows
* Python Version:  3.10.2
* aiogram version: 2.25.1
* aiohttp version: 3.8.4

I also checked with a request to the server, the situation is the same, everything goes in turn
![image](https://github.com/aiogram/aiogram/assets/67081739/3cf3c9a8-2c6d-4b33-860d-65cf689a216c)

**Comment by JrooTJunior** [comment]
What do you mean in words "not working in async"?

**Comment by greatUzumaki** [comment]
> What do you mean in words "not working in async"?

I have a telegram bot that answers users' questions, but with the webhook mode, the responses have become sequential, until the first user receives an answer, the processing of the second does not start

**Comment by Olegt0rr** [comment]
Sounds strange. Please, provide a reproducible example

**Comment by JrooTJunior** [comment]
Stale issue
