### ISSUE TITLE
it is not possible to set the state in the handler registration 

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [aiogram/aiogram#1223]
it is not possible to set the state in the handler registration as a string, although it is possible to set the state via 
`await state.set_state("Name:name1")`

**Comment by JrooTJunior** [comment]
States is always is optional string, so, you can use "Name:name1" as state as in your example in any version of aiogram.

So, if you have any errors with that, just provide minimum reproducible example and traceback

**Comment by JrooTJunior** [comment]
I will close this issue, if you have further questions, please open a new issue or discussion.
