### ISSUE TITLE
Send data from middlewares to filters

### ISSUE THREAD

**Issue by gabbhack** [aiogram/aiogram#124]
In middleware, I get a user object from the database, but it is not passed to filters. 
I think we need to replace
`data.update(await check_filters(handler_obj.filters, args))` in [handler](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/dispatcher/handler.py#L108)
on
`data.update(await check_filters(handler_obj.filters, args + (data,)))`

**Comment by JrooTJunior** [comment]
Changes of #140 is reverted in #148

**Comment by JrooTJunior** [comment]
Already implemented in 3.0
