### ISSUE TITLE
I propose to make a working example of deploying code on webhooks

### ISSUE THREAD

**Issue by iyamk** [aiogram/aiogram#1241]
**Is your feature request related to a problem? Please describe.**
I tried to make the code according to the example and no one helped me, in the end nothing happened, but fiddling with nginx is too difficult and goes beyond python

**Describe the solution you'd like**
I think someone should suggest a solution because aiohttp server with certificates doesn't work

**Describe alternatives you've considered**
Make everything work on aiohttp or write a working example for apache or nginx, this information is valuable and it is not found anywhere

**Additional context**
Until there is such an opportunity, the use of a bot is not promising for most people, I had to change the programming language because writing telegram bots in python is impractical when you need to quickly install a bot on a server and domain

**Comment by JrooTJunior** [comment]
Added: #1248
