### ISSUE TITLE
TypeError: aiogram.dispatcher.router.Router.emit_startup() got multiple values for keyword argument 'bot'

### ISSUE THREAD

**Issue by arynyklas** [aiogram/aiogram#1242]
## Expected Behavior

Successful startup of Dispatcher.start_polling

## Current Behavior

`TypeError: aiogram.dispatcher.router.Router.emit_startup() got multiple values for keyword argument 'bot'`

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `dispatcher.start_polling(bot)`

### Failure Logs

```
Traceback (most recent call last):
  File "...lib\site-packages\aiogram\dispatcher\dispatcher.py", line 519, in start_polling
    await self.emit_startup(bot=bots[-1], **workflow_data)
TypeError: aiogram.dispatcher.router.Router.emit_startup() got multiple values for keyword argument 'bot'
```

**Comment by JrooTJunior** [comment]
Did you pass the "bot" key into `dispatcher.workflow_data`?

With described scenario in the "Steps to reproduce" section it can't be reproduced, but if you set manually `dispatcher.workflow_data["bot"] = bot` this error can be caused.

**Comment by Olegt0rr** [comment]
It also may looks like a `
```python
dp["bot"] = ...
```
