### ISSUE TITLE
Incorrect Type Annotations - InlineKeyboardButton

### ISSUE THREAD

**Issue by ruslan-korneev** [aiogram/aiogram#1246]
Hello, I'm one of the developers who use pyright as a type-checker, and with aiogram's current type-annotation i've got a lot type errors, ofc everything works in runtime, but its really annoying, you could say "dont use pyright then" but I hope u'll find a better solution, as an example I choose InlineKeyboardButton class, here you can see current and expected annotations:

## Current Annotations

[source](https://github.com/aiogram/aiogram/blob/88baf0b5828fe35805a58bc48b63615a906f6ea6/aiogram/types/inline_keyboard.py#L100C1-L109)
```python
class InlineKeyboardButton(base.TelegramObject):
    """..."""
    ...
    def __init__(self, text: base.String,
                 url: base.String = None,
                 login_url: LoginUrl = None,
                 callback_data: base.String = None,
                 switch_inline_query: base.String = None,
                 switch_inline_query_current_chat: base.String = None,
                 callback_game: CallbackGame = None,
                 pay: base.Boolean = None,
                 web_app: WebAppInfo = None,
                 **kwargs):
        ...
```

## Expected Annotations
```python
from typing import Optional

...

class InlineKeyboardButton(base.TelegramObject):
    """..."""
    ...
    def __init__(self, text: base.String,
                 url: Optional[base.String] = None,
                 login_url: Optional[LoginUrl] = None,
                 callback_data: Optional[base.String] = None,
                 switch_inline_query: Optional[base.String] = None,
                 switch_inline_query_current_chat: Optional[base.String] = None,
                 callback_game: Optional[CallbackGame] = None,
                 pay: Optional[base.Boolean] = None,
                 web_app: Optional[WebAppInfo] = None,
                 **kwargs):
        ...
```

## Context
* aiogram version: 2.25.1

**Comment by JrooTJunior** [comment]
Approved, but v2.x is no more be supported, please migrate to v3.0
It is going to RC stage, so, it should be stable and usable now.

**Comment by ruslan-korneev** [comment]
@JrooTJunior its cool, but when u gonna release it? as I see its not done yet and there is no due date for [milestone 3.0](https://github.com/aiogram/aiogram/milestone/2)

**Comment by JrooTJunior** [comment]
Today the first release candidate will be published, i think from 2 to 4 weeks is needed to complete all required preparations for release
