### ISSUE TITLE
Broken message.html_text property

### ISSUE THREAD

**Issue by Forden** [aiogram/aiogram#1259]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Ubuntu 22.04 LTS

### Python version

Python 3.10.12

### aiogram version

3.0.0b8

### Expected behavior

Using message.html_text on text with hashtag in bold font should result in correct parsing.

Incoming text
**#test**
Output
`<b>#test</b>`

### Current behavior

Instead it escapes created markup and breaks formatting.

Incoming text
**#test**
Output
`&lt;b&gt;#test&lt;/b&gt;`

### Steps to reproduce

1. Send message with hashtag inside any formatting (bold, italic, etc.)
2. Call message.html_text on received message

### Code example

```python3
import asyncio

from aiogram import Bot, Dispatcher, types

async def demo(msg: types.Message) -> None:
   await msg.reply(msg.html_text, parse_mode='HTML')


async def main() -> None:
   dp = Dispatcher()
   dp.message.register(demo)

   bot = Bot('123:ABC')
   await dp.start_polling(bot)

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except (KeyboardInterrupt, SystemExit):
        logging.info("Bot stopped!")
```

**Comment by dsodx** [comment]
why not aiogram==3.0.0rc1 ?
