### ISSUE TITLE
Deep link AES128

### ISSUE THREAD

**Issue by Naturalov** [aiogram/aiogram#1262]
### aiogram version

3.x

### Problem

Wants to create deep link with AES, now byte64.

### Possible solution

.

### Alternatives

.

### Code example

```python3
link = await create_start_link(bot=bot, payload='text', encode='Aes128', key='key')
```

**Comment by JrooTJunior** [comment]
In some cases it can be useful, but Base64 works out of the box in Python unlike AES or other cryptographic algorithms, so, i think it should not be added directly into aiogram, but it can be implemeted as separate library.

**Comment by Naturalov** [comment]
> In some cases it can be useful, but Base64 works out of the box in Python unlike AES or other cryptographic algorithms, so, i think it should not be added directly into aiogram, but it can be implemeted as separate library.

That's a good idea, too

**Comment by Olegt0rr** [comment]
@Naturalov now you can use your custom encoder :)
