### ISSUE TITLE
Dependency specifiers are not SemVer compliant

### ISSUE THREAD

**Issue by monosans** [aiogram/aiogram#1271]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### aiogram version

3.0.0rc1

### Expected behavior

Successful installation of aiogram==3.0.0rc1 and pydantic>=2.2.0

### Current behavior

pip:

```
ERROR: Cannot install aiogram==3.0.0rc1 and pydantic>=2.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested pydantic>=2.2.0
    aiogram 3.0.0rc1 depends on pydantic~=2.1.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

poetry:

```
Because  depends on aiogram (3.0.0rc1) which depends on pydantic (>=2.1.1,<2.2.0), pydantic is required.
So, because  depends on pydantic (2.2.0), version solving failed.
```

### Steps to reproduce

```
pip install aiogram==3.0.0rc1 pydantic>=2.2.0
```

### Additional information

The problem is related to the use of `~=` to specify the version. `pydantic~=2.1.1` actually means `pydantic>=2.1.1,<2.2`, whereas according to SemVer it would be correct to specify `pydantic>=2.1.1,<3`.

Let me know if you want me to make a pull request.

**Comment by Olegt0rr** [comment]
It's not a bug.

1. Open this: https://docs.pydantic.dev/latest/changelog/
2. Search for "Breaking Change"

Pydantic usually adds breaking changes on minor versions.
So `~=` is a protection.

**Comment by JrooTJunior** [comment]
I checked that open-source projects that using wider dependency constraints, so, we can do the same - use `pydantic>=2.1.1,<3`
