### ISSUE TITLE
JSON of model_dump_json of aiogram types are not BotAPI compatible

### ISSUE THREAD

**Issue by MrYacha** [aiogram/aiogram#1277]
### aiogram version

3.x

### Problem

In case we want to dump current event/message/etc using model_dump_json method we get something like this:

``` json
{
  "update_id": 909208484,
  "message": {
    "message_id": 3171,
    "date": "2023-08-20T18:12:29Z",
    "chat": {
      "id": 483808054,
      "type": "private",
      "username": "MrYacha",
      "first_name": "Yacha"
    },
    "from": {
      "id": 483808054,
      "is_bot": false,
      "first_name": "Yacha",
      "username": "MrYacha",
      "language_code": "de",
      "is_premium": true
    },
    "text": "/notes",
    "entities": [
      {
        "type": "bot_command",
        "offset": 0,
        "length": 6
      }
    ]
  }
}
```
The message.date field has its own type which is not BotAPI compatible.

### Possible solution

Make aiogram types serialize to BotAPI standard.

### Code example

```python3
message.model_dump_json(exclude_none=True, by_alias=True)
```

**Comment by JrooTJunior** [comment]
This behaviour was disabled since pydantic 2.0 in due to `json_serializers` was removed from models settings, so, now it can be resolved via `Annotated` custom types with custom serializers like:

```python
DateTime = Annotated[
    datetime.datetime,
    PlainSerializer(lambda dt: int(dt.timestamp()), return_type=int, when_used="json"),
]
```

I think in v3.1-3.3 i can add this alias to codegeneration.
