### ISSUE TITLE
Adding aioredis to requirements.txt

### ISSUE THREAD

**Issue by Forden** [aiogram/aiogram#128]
`Aioredis` is not present in requirements.txt, so `pipreqs` cannot detect it and form the correct requirements.txt for bot

**Comment by JrooTJunior** [comment]
`aioredis` is optional dependency and not needed for all developers. In this reason [RedisStorage](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/contrib/fsm_storage/redis.py#L2) is placed in the `contrib` package as the same with Rethink storage.

This dependency is placed in `dev_requirements.txt` file: https://github.com/aiogram/aiogram/blob/0b33b041ceaf90c74a8c10cae60cbdee2ba3ad41/dev_requirements.txt#L11
