### ISSUE TITLE
Router level filtering

### ISSUE THREAD

**Issue by slmv-e** [aiogram/aiogram#1297]
### aiogram version

3.x

### Problem

I was writing my telegram and faced with filtering problem, I want to add admin interface to my bot, but I forced to duplicate my AdminOnly filter to all my admin handlers

### Possible solution

I propose make a router level filtering, I propose to create a new field in Router class

```
def __init__(self, *, name: Optional[str] = None, filters: Optional[CallbackType] = None) -> None:
   ...
   self.filters = filters
   ...
```
then create add subrouter interceptor and modify subrouter filters array by combining parent and child routers filters array, then in `TelegramEventObserver.__call__` provide not only handler filters but router filters too (by combining arrays)

### Code example

```python3
router = Router(name='router', filters=[AdminOnly()])

router1 = Router(name='router1')

@router.message(Command('admin')) # this handler has AdminOnly filter
async def admin(...):
   ...


@router1.message(Command('ban_user')) # this handler also has AdminOnly filter, because next we make router1 nested in router
async def ban_user(...):
   ...


router.include_router(router1)
```

**Comment by JrooTJunior** [comment]
It is already implemented.

```python
router.message.filter(AdminOnly())
router.callback_query.filter(AdminOnly())
...
```

**Comment by slmv-e** [comment]
Thanks
