### ISSUE TITLE
Inline button not responding

### ISSUE THREAD

**Issue by progdagi** [aiogram/aiogram#1300]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

ubuntu 22

### Python version

3.10

### aiogram version

3.0.0

### Expected behavior

I expect the bot to respond with a message saying "Hi" when the inline button is clicked.

### Current behavior

The bot does not respond when the inline button is clicked. No message is displayed.

### Steps to reproduce

1. Start the application using python main.py.
2. Send the /test command to the bot.
3. Observe that an inline keyboard with a "Test" button is displayed.
4. Click on the "Test" button.

### Code example

```python3
# main.py

from fastapi import FastAPI

app = FastAPI()

@app.on_event("startup")
async def on_startup():
    webhook_info = await Bot.get_webhook_info()
    if webhook_info.url != webhook_url:
        await Bot.set_webhook(url=webhook_url)

@app.post(webhook_path)
async def feed_update(update: Dict[str, Any]) -> None:
    telegram_update = types.Update(**update)
    await dp.feed_webhook_update(bot=Bot, update=telegram_update)



if __name__ == "__main__":
    import logging
    logging.basicConfig(level=logging.INFO)
    main()
    uvicorn.run(app,port=5050)


# routers/init.py
router = Router()

@router.message(Command("test"))
async def language(message: Message):
    button = InlineKeyboardButton(text="Test", callback_data="test_me")
    keyboard = InlineKeyboardMarkup(inline_keyboard=[[button]])
    
    
    await message.reply("Just a test", reply_markup=keyboard)


@router.callback_query(lambda c: c.data == "test_me")
async def language_callback(callback: CallbackQuery):
    await callback.answer("Hi", show_alert=True)
```

### Additional information

I am using aiogram v3.0.
I have properly configured the ngrok tunnel and webhook URL.
The rest of the bot functionality is working fine.

**Comment by JrooTJunior** [comment]
Can you show me the result of `getWebhookInfo` result?

`await bot.get_webhook_info()`

**Comment by progdagi** [comment]
Tanks for your reply the issue not from aiogram it's just my telegram app
bung when i update my app it worked.... I will close the issue on github
