### ISSUE TITLE
SIGINT is pre-emtied by aiogram

### ISSUE THREAD

**Issue by rudyvan** [aiogram/aiogram#1301]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

MAC OS 

### Python version

3.11.1

### aiogram version

3.0.0

### Expected behavior

Firstly, thanks for the new version, got it all working fine!

Just, seems that aiogram is overwriting the signal SIGINT handler and therefore the behaviour with ctrl_c is changed.

See below, i managed a work around to have my original signal handler working (pi.tasks.handle_exception):
  When 'start_polling' terminates, i restore the signal handler and activate the signal again.

Maybe aiogram should not hijack the SIGINT signal?

```
        try:
            self.disp = Dispatcher()
            self.router = Router()
            self.disp.include_router(self.router)
            self.menu_ptr = self._menu_main
            cmds_start = {"start", "restart"}
            self.router.message.register(self.start_handler)
            self.router.message.register(self.start_handler, CommandStart(deep_link=cmds_start))
            self.all_cmds |= cmds_start
            self.router.callback_query.register(self.query_handler, lambda callback_query: True)
            await self.disp.start_polling(self.bot)
            # seems that the signal handler is not called when the bot stops polling
            signal.signal(signal.SIGINT, pi.tasks.handle_exception)
            signal.raise_signal(signal.SIGINT)
        except Exception as e:
            pi.nty_print(f"!!err_telegram_poll {e}", is_except=True)
            pi.tasks.add("Telegram Handler", self.telegram_task)
        finally:
            await self.disp.stop_polling()
```

### Current behavior

SIGINT signal is used by aiogram but then other signal handlers are mute.

### Steps to reproduce

set a signal handler
start aiogram polling
terminate with ctrl_c key
origina signal handler is not called

**Comment by JrooTJunior** [comment]
The only one signal handler can be registered for any application, if you register your own you should call `dispatcher.stop_polling()` from your own signals handler.
Also you can disable signals handler registration by settings argument `handle_signals=False`:  [Docs](https://docs.aiogram.dev/en/dev-3.x/dispatcher/dispatcher.html#aiogram.dispatcher.dispatcher.Dispatcher.start_polling)

**Comment by Remendado** [comment]
In Executor on start_polling event I can describe on_start and on_stop tasks .  Is there on_stop analog in aiogram 3?

**Comment by rudyvan** [comment]
Thanks, works!
Apologies, should have read the documentation better.
