### ISSUE TITLE
breaking changes

### ISSUE THREAD

**Issue by project621c** [aiogram/aiogram#1324]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Linux kanairo-desktop 5.15.0-1032-realtime #35-Ubuntu 2023 x86_64 x86_64 x86_64 GNU/Linux

### Python version

Python 3.10.12

### aiogram version

aiogram-3.1.1

### Expected behavior

I just updated the code now with pip and i can't call executor
  Attempting uninstall: aiogram
    Found existing installation: aiogram 2.25.1
    Uninstalling aiogram-2.25.1:
      Successfully uninstalled aiogram-2.25.1
Successfully installed aiofiles-23.1.0 aiogram-3.1.1 aiohttp-3.8.5 annotated-types-0.5.0 magic-filter-1.0.11 pydantic-2.3.0 pydantic-core-2.6.3 typing-extensions-4.7.1

### Current behavior

Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
Downloading annotated_types-0.5.0-py3-none-any.whl (11 kB)
Installing collected packages: typing-extensions, magic-filter, annotated-types, aiofiles, pydantic-core, aiohttp, pydantic, aiogram
  Attempting uninstall: typing-extensions
    Found existing installation: typing_extensions 4.8.0
    Uninstalling typing_extensions-4.8.0:
      Successfully uninstalled typing_extensions-4.8.0
  Attempting uninstall: magic-filter
    Found existing installation: magic-filter 1.0.9
    Uninstalling magic-filter-1.0.9:
      Successfully uninstalled magic-filter-1.0.9
  Attempting uninstall: aiohttp
    Found existing installation: aiohttp 3.8.4
    Uninstalling aiohttp-3.8.4:
      Successfully uninstalled aiohttp-3.8.4
  Attempting uninstall: pydantic
    Found existing installation: pydantic 1.10.12
    Uninstalling pydantic-1.10.12:
      Successfully uninstalled pydantic-1.10.12
  Attempting uninstall: aiogram
    Found existing installation: aiogram 2.25.1
    Uninstalling aiogram-2.25.1:
      Successfully uninstalled aiogram-2.25.1
Successfully installed aiofiles-23.1.0 aiogram-3.1.1 aiohttp-3.8.5 annotated-types-0.5.0 magic-filter-1.0.11 pydantic-2.3.0 pydantic-core-2.6.3 typing-extensions-4.7.1
(betbot) kanairo@kanairo-desktop:~/Private/cashathand/telebot/riambatang$ python3 telegrambbt.py
Traceback (most recent call last):
  File "/home/kanairo/Private/cashathand/telebot/riambatang/telegrambbt.py", line 1, in <module>
    import config
  File "/home/kanairo/Private/cashathand/telebot/riambatang/config.py", line 6, in <module>
    from aiogram import Bot, Dispatcher, executor, types
ImportError: cannot import name 'executor' from 'aiogram' (/home/kanairo/.local/lib/python3.10/site-packages/aiogram/__init__.py)

### Steps to reproduce

>>> import aiogram
>>> from aiogram import executor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'executor' from 'aiogram' (/home/kanairo/.local/lib/python3.10/site-packages/aiogram/__init__.py)
>>>

### Code example

```python3
>>> import aiogram
>>> from aiogram import executor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'executor' from 'aiogram' (/home/kanairo/.local/lib/python3.10/site-packages/aiogram/__init__.py)
>>>


from aiogram import Bot, Dispatcher, executor, types
```

### Logs

```sh
Traceback (most recent call last):
  File "/home/kanairo/Private/cashathand/telebot/riambatang/telegrambbt.py", line 1, in <module>
    import config
  File "/home/kanairo/Private/cashathand/telebot/riambatang/config.py", line 6, in <module>
    from aiogram import Bot, Dispatcher, executor, types
ImportError: cannot import name 'executor' from 'aiogram' (/home/kanairo/.local/lib/python3.10/site-packages/aiogram/__init__.py)
(betbot) kanairo@kanairo-desktop:~/Private/cashathand/telebot/riambatang$ nano config.py
```

### Additional information

it has just broken now i bet its due to my latest upgrade

**Comment by JrooTJunior** [comment]
Just read migration guide: https://docs.aiogram.dev/en/dev-3.x/migration_2_to_3.html

3.0 has no more executor.

3.0 is a big update with critical changes, this is expected behavior, you can't run old code without making changes that match the changelog.

If you wan't to use old code without updating it - install legacy version of aiogram - `pip install aiogram==2.25.1`, but if you want to use 3.x version you should also update your code.
