### ISSUE TITLE
`flags` and `filters` in `HandlerObject` won't be set correctly on new events

### ISSUE THREAD

**Issue by sina-e** [aiogram/aiogram#1329]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Arch Linux 6.5.5-arch1-1 x86_64

### Python version

3.11.5

### aiogram version

3.1.1

### Expected behavior

`flags` and `filters` of `HandlerObject` will be filled with the values set in the flags deorator. just like the docs says:

```python
@router.message(F.text == "test")
@flags.rate_limit(count=10, duration=20, limit_for=10)
async def my_handler(message: Message)
```

### Current behavior

but when i print out or use `extract_flags` in a `middleware`, I get an empty dictionary for `flags` and also the `filters`.

I tried to fix this but was unsuccessful. 

### Steps to reproduce

create a handler and set a flag for it, doesn't make any difference if you use decorators or kwargs in the handler registration.

### Additional information

I did some digging and found out that when an update comes and the middlewares are being wrapped. everything is ok until in the `wrap_middlewares`.

when i print out handler, it will show a HandlerObject with `flags` and `filters` filled. but after that they are empty.

**Comment by JrooTJunior** [comment]
n your example, where do you register this handler on the router?

**Comment by sina-e** [comment]
@JrooTJunior sorry. i updated my issue. i register the handler but forgot to mention it here.

**Comment by JrooTJunior** [comment]
Please provide an minimum reproducible example.

I checked that and it works as well:

![image](https://github.com/aiogram/aiogram/assets/6726423/d3e58661-8631-4a57-b3ee-7572161c4737)

```python
import asyncio
import logging
from os import getenv

from aiogram import Router, flags, F, Dispatcher, Bot
from aiogram.dispatcher.flags import extract_flags
from aiogram.types import Message

router = Router(name=__name__)


@router.message(F.text == "test")
@flags.rate_limit(count=10, duration=20, limit_for=10)
async def my_handler(message: Message):
    await message.answer("test")


@router.message.middleware()
async def my_middleware(handler, event, data):
    flags_data = extract_flags(data)
    print(f"{flags_data = }")

    return await handler(event, data)


async def create_dispatcher() -> Dispatcher:
    dispatcher = Dispatcher()
    dispatcher.include_router(router)
    return dispatcher


async def main():
    bot = Bot(token=getenv("TELEGRAM_TOKEN"), parse_mode="HTML")
    dispatcher = await create_dispatcher()
    await dispatcher.start_polling(bot)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())
    # Alternatively, you can use aiogram CLI:
    # `aiogram run polling --reload --log-level info --token <TOKEN> issue1329:create_dispatcher`
```

**Comment by antos07** [comment]
@JrooTJunior  I also encountered the behavior @sina-e described. It happens when a middleware registered in the `dispatcher.update`, so I slightly updated your code:
```python
import asyncio
import logging
from os import getenv

from aiogram import Router, flags, F, Dispatcher, Bot
from aiogram.dispatcher.flags import extract_flags
from aiogram.types import Message

router = Router(name=__name__)


@router.message(F.text == "test")
@flags.rate_limit(count=10, duration=20, limit_for=10)
async def my_handler(message: Message):
    await message.answer("test")


async def my_middleware(handler, event, data):
    flags_data = extract_flags(data)
    print(f"{flags_data = }")

    return await handler(event, data)


async def create_dispatcher() -> Dispatcher:
    dispatcher = Dispatcher()
    dispatcher.include_router(router)
    dispatcher.update.middleware(my_middleware)
    return dispatcher


async def main():
    bot = Bot(token=getenv("TELEGRAM_TOKEN"), parse_mode="HTML")
    dispatcher = await create_dispatcher()
    await dispatcher.start_polling(bot)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    asyncio.run(main())
```
![aiogram-issue-1329-example](https://github.com/aiogram/aiogram/assets/37223374/f9943186-307d-4ca2-b80a-5452e0843cf0)

**Comment by JrooTJunior** [comment]
Expected behavior because you are trying to read flags of the update handler instead of message handler.

When telegram sent event the update handler will be triggered, we have internal updates handler which detects the update type and propagate it to the specific ones (message, callback_query, ...), so, when you check the flags for update event - you are trying to read flags of the internal update handler.

**Comment by antos07** [comment]
Thanks for the explanation. Btw, it would be great to have it in the docs because the existing one is quite confusing and not really helpful:

> Inner middlewares is always calls for [aiogram.types.update.Update](https://docs.aiogram.dev/en/latest/api/types/update.html#aiogram.types.update.Update) event type in due to all incoming updates going to specific event type handler through built in update handler

**Comment by Cactiw** [comment]
I agree, the documentation is very confusing. I think it should be changed to address the difference between update and other middlewares.

**Comment by JrooTJunior** [comment]
Feel free to contribute to the documentation, just make changes to the documentation files and submit a pull request to make this article more understandable for other developers.

**Comment by faerics** [comment]
Just want to say that I felt into exactly the same pitfall. 
Is the issue relevant? I can update docs to reflect middleware difference.
