### ISSUE TITLE
i18n example update

### ISSUE THREAD

**Issue by iscopan** [aiogram/aiogram#1333]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

GitHub Codespace

### Python version

3.10.8

### aiogram version

3.1.1

### Expected behavior

https://github.com/aiogram/aiogram/blob/56662d6bd8052ee835fcfebd928c8a2786fe922c/examples/i18n_example.py#L51

### Current behavior

AttributeError: 'Dispatcher' object has no attribute 'middleware'

### Steps to reproduce

1. Use function
2. Fail

### Code example

```python3
from os import getenv


from aiogram import Dispatcher, Bot
from aiogram.enums import ParseMode
from aiogram.utils.i18n import I18n
from aiogram.utils.i18n.middleware import SimpleI18nMiddleware


TOKEN = getenv("BOT_TOKEN")
dp = Dispatcher()
bot = Bot(TOKEN, parse_mode=ParseMode.HTML)
i18n = I18n(path="/src/bot/locales", default_locale="es", domain="messages")
dp.middleware.setup(i18n)
```

### Logs

```sh
telegram-bot_1  | Traceback (most recent call last):
telegram-bot_1  |   File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
telegram-bot_1  |     return _run_code(code, main_globals, None,
telegram-bot_1  |   File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
telegram-bot_1  |     exec(code, run_globals)
telegram-bot_1  |   File "/src/bot/__main__.py", line 12, in <module>
telegram-bot_1  |     from botloader.botloader import dp, bot
telegram-bot_1  |   File "/src/bot/botloader/botloader.py", line 14, in <module>
telegram-bot_1  |     dp.middleware.setup(i18n)
telegram-bot_1  | AttributeError: 'Dispatcher' object has no attribute 'middleware'
```

**Comment by JrooTJunior** [comment]
You are trying to use example from V2 with installed V3, please check V3 examples and migration guides:
- https://docs.aiogram.dev/en/latest/utils/i18n.html
- https://docs.aiogram.dev/en/latest/contributing.html
- https://github.com/aiogram/aiogram/tree/dev-3.x/examples

**Comment by iscopan** [comment]
Sorry, but there is no example of i18n

**Comment by JrooTJunior** [comment]
Read the docs.

**Comment by iscopan** [comment]
I have read the docs but I haven't been able to get it to work. Seeing an example would be great, if it could be added to the repository
