### ISSUE TITLE
Documentation Ukrainian translation mistake

### ISSUE THREAD

**Issue by pavetr1337** [aiogram/aiogram#1348]
### aiogram version

n/a

### Problem

Ukrainian translator replaced the Russian flag with Shit emoji
![IMG_20231025_075918](https://github.com/aiogram/aiogram/assets/61318253/839a64c8-3749-4245-88d0-050850fe13f4)
![IMG_20231025_075824](https://github.com/aiogram/aiogram/assets/61318253/79f31fd9-f3f0-49e1-8397-df5ed63e316d)

### Possible solution

Replace shit emoji with russian flag

**Comment by JrooTJunior** [comment]
Don't see any mistakes.
