### ISSUE TITLE
Dispathcer middleware for sub_routers

### ISSUE THREAD

**Issue by dexsper** [aiogram/aiogram#1350]
### aiogram version

3.x

### Problem

If I have a large number of global middleware I have to do so:

 for r in dispatcher.sub_routers:
        r.message.middleware(...)

### Possible solution

I would like dispatcher to call its middleware before calling sub_routers
That would be logical

### Code example

```python3
https://paste.aiogram.dev/sasinariga.py
https://paste.aiogram.dev/lopaguqepi.py
https://paste.aiogram.dev/tiboniziwo.py
```

**Comment by JrooTJunior** [comment]
You can register the middleware for dispatcher or for the parent router and it will be used by all nested routers.
