### ISSUE TITLE
Default events logging behavior

### ISSUE THREAD

**Issue by doreshnikov** [aiogram/aiogram#1355]
### aiogram version

3.x

### Problem

Currently logs in `aiogram` look like 
```
INFO:aiogram.event:Update id=<event_id> is handled. Duration <time> by bot id=<id>
```
This behavior is not adjustable. [Other related issue](https://github.com/aiogram/aiogram/issues/1181) was received with a response "You can disable `aigoram.event` logger and implement your own logging middleware". However, it's not clear to me that purpose serves intentionally omitting event timestamp in default logging mechanism.

### Possible solution

Ideally, if there is no real reason behind omitting timestamps in logs, they should probably be included.

### Alternatives

I would assume most developers expect to find timestamps in their app's logs. If there is a reason why `aiogram` intentionally omits them, it would be at least very much useful to have an example of how to replace default logger with a custom middleware in the [examples](https://github.com/aiogram/aiogram/tree/dev-3.x/examples) directory.

**Comment by JrooTJunior** [comment]
Did you mean the timestamp in the log message?
This question is not directly related to aiogram, just read the docs about logging configuration in Python, it seems you have a default logging format, but you can enable it: https://docs.python.org/3/howto/logging-cookbook

**Comment by doreshnikov** [comment]
> Did you mean the timestamp in the log message? This question is not directly related to aiogram, just read the docs about logging configuration in Python, it seems you have a default logging format, but you can enable it: https://docs.python.org/3/howto/logging-cookbook

I was trying to change the Formatter for logging, but it didn't affect logs from aiogram. But maybe it indeed is a problem on my side, thanks, I'll check it again.

**Comment by doreshnikov** [comment]
Yes, seems like I was updating the logger format in the wrong place in my code, which affected only my internal modules. Which led me to believe that `aiogram` handles logging differently. Thank for help!
