### ISSUE TITLE
Passing the context from a middleware to a handler is undocumented and has no related examples

### ISSUE THREAD

**Issue by doreshnikov** [aiogram/aiogram#1356]
### aiogram version

3.x

### Problem

There seems to be no documentation for the particular feature that took me two hours to discover by analyzing `aiogram` code. Which is: being able to pass arbitrary additional arguments to handlers by using middleware's `data` and assigning key-value arguments for handler to it.

### Possible solution

An important feature like this should be properly documented or at least given an example like [this one](https://github.com/aiogram/aiogram/blob/dev-3.x/examples/context_addition_from_filter.py) for the similar behavior implemented in filters.

**Comment by JrooTJunior** [comment]
Documented: https://docs.aiogram.dev/en/dev-3.x/dispatcher/dependency_injection.html

**Comment by doreshnikov** [comment]
> Documented: https://docs.aiogram.dev/en/dev-3.x/dispatcher/dependency_injection.html

Got it, my bad, thank you!
