### ISSUE TITLE
List Forum Topics / Find Out Topics IDs 

### ISSUE THREAD

**Issue by kit4py** [aiogram/aiogram#1358]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

MacOS

### Python version

3.11

### aiogram version

3.1.1

### Expected behavior

channels.getForumTopics
channels.getForumTopicsByID

### Current behavior

I can create a new topic in a forum, but there is no way to view it's message_thread_id. I have searched the web in all languages but couldn't find anything. Is there a way?
So the plan is: 
1. Create a new topic
2. Get the ID from the new created topic
3. Send a message to the new created topic using the thread_id

### Steps to reproduce

?

**Comment by JrooTJunior** [comment]
The Bot API has no such methods, so, it cannot be added to the aiogram.
Official Bot API Documentation: https://core.telegram.org/bots/api

**Comment by kuidin-mykhailo** [comment]
Dear @JrooTJunior.
Today I faced the same issue, expecting that aiogram supporting this functions.

I can see them in docs:
https://core.telegram.org/method/channels.getForumTopics
https://core.telegram.org/method/channels.getForumTopicsByID

**Comment by Olegt0rr** [comment]
@kuidin-mykhailo, it's not Bot API docs.

Bot API Documentation: https://core.telegram.org/bots/api
