### ISSUE TITLE
Outer Middleware does not catch CallbackQuery objects

### ISSUE THREAD

**Issue by xDayTripperx** [aiogram/aiogram#1359]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Mac OS Sonoma

### Python version

3.10.11

### aiogram version

3.1.1

### Expected behavior

Catch all CallbackQuery Objects via outer middleware if that’s specified in outer middleware

### Current behavior

Clicking the button in inline keyboard bypass the middleware and goes directly to the router. Middleware does actually react to other updates as typing commands, sending text and voice messages, but completely ignores callbackquery from clicking the button in inline keyboard.

### Steps to reproduce

1. Create outer middleware as such:
```python
class dialogue_ban_middleware(
    BaseMiddleware
):
    async def __call__(
        self,
        handler: Callable[[Update, Dict[str, Any]], Awaitable[Any]],
        event: Update,
        data: Dict[str, Any],
    ) -> Any:
        if not isinstance(event, CallbackQuery):
            return await handler(event, data)
```
2. Create a button and attach it to the message via reply_markup
3. Set up a router and configure it to catch callback_query updates via "F.data =="
4. As a result - middleware ignores the buttons press, but does notice text and voice messages and commands

### Code example

```python
# Middleware

class dialogue_ban_middleware(
    BaseMiddleware
): 
    async def __call__(
        self,
        handler: Callable[[Update, Dict[str, Any]], Awaitable[Any]],
        event: Update,
        data: Dict[str, Any],
    ) -> Any:
        if not isinstance(event, CallbackQuery):
            return await handler(event, data)


# Router

@callback_router.callback_query(
    F.data == "btn_dialogue_start"
)
async def dialogue_mode_enable(message: types.Message, state: FSMContext):
    await state.set_state(UserState.Dialogue)
    await bot.send_message(
        chat_id=message.from_user.id,
        text="Dialogue has begun",
    )

# Menu with the button

button_dialogue_start = [
    [InlineKeyboardButton(text="start dia", callback_data="btn_dialogue_start")]
]

menu_dialogue_start = InlineKeyboardMarkup(
    inline_keyboard=button_dialogue_start
)
```

### Additional information

I've tried changing "Update" type in middleware in these fields
`handler: Callable[[Update, Dict[str, Any]], Awaitable[Any]],
event: Update,`
        
I changed it to "TelegramObject", "CallbackQuery" and "Message" but it does not change the behavior

**Comment by JrooTJunior** [comment]
Where did you register this middleware on any event observer?

**Comment by JrooTJunior** [comment]
As you can see in the documentation https://docs.aiogram.dev/en/dev-3.x/dispatcher/middlewares.html#class-based
you should register middleware on the desired event observer, for example if you want to use middleware on callback query you should do:

```python
router.callback_query.middleware(DialogueBanMiddleware())
```
Note that instead of router you can use the Dispatcher instance.
Also you can use outer middleware (before filters) instead of inner (after filters) to do something in the wider scope.

So, please read the docs.

**Comment by xDayTripperx** [comment]
> As you can see in the documentation https://docs.aiogram.dev/en/dev-3.x/dispatcher/middlewares.html#class-based you should register middleware on the desired event observer, for example if you want to use middleware on callback query you should do:
> 
> ```python
> router.callback_query.middleware(DialogueBanMiddleware())
> ```
> 
> Note that instead of router you can use the Dispatcher instance. Also you can use outer middleware (before filters) instead of inner (after filters) to do something in the wider scope.
> 
> So, please read the docs.

I actually did register middleware (not in the router though, but in the dispatcher itself), just didn't mention it in the code, my bad - it's kinda obvious from this part of my message as otherwise it wouldn't react to anything at all

> Middleware does actually react to other updates as typing commands, sending text and voice messages, but completely ignores callbackquery from clicking the button in inline keyboard.

To fix this misunderstanding - here is the part where I register it


```
async def main():
    dp = Dispatcher(storage=storage)
    from handlers.callback_handler import callback_router
    from handlers.command_handler import command_router
    from handlers.text_msg_handler import text_msg_router
    from handlers.voice_msg_handler import voice_msg_router

    dp.message.outer_middleware(dialogue_ban_middleware())
    dp.message.outer_middleware(processing_ban_middleware())

    dp.message.outer_middleware(user_info_middleware())
    dp.message.middleware(transcribe.transcribe_middleware())

    dp.include_routers(
        command_router, text_msg_router, voice_msg_router, callback_router
    )

    await dp.start_polling(bot)
    
    if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, stream=sys.stdout)
    asyncio.run(main())
```

**Comment by xDayTripperx** [comment]
Adding some info:
With the help of debug mode in VS code I can check that all my middlewares that I have in bot actually ignore all clicking on button responses. However, they do activate when the user sends a text message, voice message or command.

Some of my other middleware look like this:

```
class processing_ban_middleware(
    BaseMiddleware
):
    async def __call__(
        self,
        handler: Callable[[Update, Dict[str, Any]], Awaitable[Any]],
        event: Message,
        data: Dict[str, Any],
    ) -> Any:
    
        # Here I process it
        
        return await handler(event, data)
```

and this

```
class user_info_middleware(
    BaseMiddleware
): 
    async def __call__(
        self,
        handler: Callable[[Message, Dict[str, Any]], Awaitable[Any]],
        event: Message,
        data: Dict[str, Any],
    ) -> Any:
    
         # Here I process it

        return await handler(event, data)
```

Guess I'm missing something. Hope this helps!

**Comment by xDayTripperx** [comment]
Sorry - I found a problem. I registered it as outer middleware, when I should have registered it as callback_query middleware as such:
`dispatcher.callback_query.middleware(CallbackAnswerMiddleware())`
