### ISSUE TITLE
Copy_message only copy one attachment to a message

### ISSUE THREAD

**Issue by xDayTripperx** [aiogram/aiogram#1364]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

WSL Ubuntu 22.04 LTS

### Python version

3.10.12

### aiogram version

3.1.1

### Expected behavior

The bot should 

> copy messages of any kind

as mentioned in docs, when using copy_message.

### Current behavior

When the user sends the message, containing more than one media (photo, video, etc) bot sends only one of them (with caption) and then, after a great pause sends another one.

Here are some logs:

1) Sends the first photo of the message instanly with the caption
`INFO:aiogram.event:Update id=********** is handled. Duration 758 ms by bot id=**********`

2) Sends another one after a huge delay in another message
`INFO:aiogram.event:Update id=********** is handled. Duration 61557 ms by bot id=**********`

### Steps to reproduce

1. Create a copy_message function
2. Send bot a message with two or more attachments

### Code example

```python3
# Router and function

admin_router = Router()
admin_router.message.filter(
    F.from_user.id == admin_id
)


@admin_router.message()
async def send_all(message: types.Message):
    admin_message = (
        message.message_id
    )

    users = (
        get_users()
    )
    for user_info in users:
        try:
            await bot.copy_message(
                user_info[0],
                message.from_user.id,
                message_id=admin_message,
            )

            if int(user_info[1]) != 1:
                set_active_status(
                    user_info[0], 1
                
        except:
            set_active_status(
                user_info[0], 0

# Main
async def main():
  dp = Dispatcher(storage=storage)
  from handlers.admin_handler import admin_router

    dp.include_routers(
        admin_router)

  await bot(
        DeleteWebhook(drop_pending_updates=True)
    )

  await dp.start_polling(bot)


  if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, stream=sys.stdout)
    asyncio.run(main())
```

### Logs

```sh
`INFO:aiogram.event:Update id=44951606 is handled. Duration 758 ms by bot id=6265406963`
`INFO:aiogram.event:Update id=44951607 is handled. Duration 61557 ms by bot id=6265406963`
```

### Additional information

I am trying to build a function for sending all the users the exact same message, as the admin sent to bot. 
This means the message should include all attachments, caption and formatting. I chose to do this with "copy_message" method to ease the way of parsing if the message is the video, photo, text, etc.

So if there is a way to make this functionality easier (i mean building a function that copies all formatting and just resends the adming message to all users) i would be really happy to know.

**Comment by JrooTJunior** [comment]
Expected behavior.

A media group cannot be copied directly using the API because a media group is a collection of different messages that are grouped together only visually on the client side.

So if you want to send a media group to another chat, you'll have to handle it yourself and send it as a new media group instead of copying.

**Comment by xDayTripperx** [comment]
> Expected behavior.
> 
> A media group cannot be copied directly using the API because a media group is a collection of different messages that are grouped together only visually on the client side.
> 
> So if you want to send a media group to another chat, you'll have to handle it yourself and send it as a new media group instead of copying.

Okay thanks

I know this is kinda offtop, sorry for that - but can i get an advice of how to copy formatting from sent message?

message.text only contains text as a str and i wish i could copy the formatting of the message and send it to another chat.

I know how to send including formatting (parse_mode = smth), but can't manage to find how i can copy formatting from message from user..

Thanks in advance, you will help me a lot if u answer!

**Comment by JrooTJunior** [comment]
formatting is a entities list, so, you can copy it:
`message.text` + `message.entities` if you have text message
`message.caption` + `message.caption_entities` if you have any media with caption

You can check how actually Message.send_copy method wotks: https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/types/message.py#L2798-L2974

Also you can use message entities parser to get the message text with applied entities into HTML or MarkdownV2 format:
for example message.html_text returns text in the HTML format.

**Comment by xDayTripperx** [comment]
Thank you so much!

**Comment by 6jlarogap** [comment]
> So if you want to send a media group to another chat, you'll have to handle it yourself and send it as a new media group instead of copying.

Hi! Could you please tell - is it possible to use your suggestion to create a new media group - without using a server for local saving of all media content? my use case is to save only ids of user message with multiple attachments and to send it to other users by their demand.
