### ISSUE TITLE
ImportError: cannot import name 'get_start_link' from 'aiogram.utils.deep_linking'

### ISSUE THREAD

**Issue by nurmukhammaddev** [aiogram/aiogram#1373]
### aiogram version

3.x

### Problem

ImportError: cannot import name 'get_start_link' from 'aiogram.utils.deep_linking'

### Possible solution

ImportError: cannot import name 'get_start_link' from 'aiogram.utils.deep_linking'

### Alternatives

ImportError: cannot import name 'get_start_link' from 'aiogram.utils.deep_linking'

### Code example

```python3
ImportError: cannot import name 'get_start_link' from 'aiogram.utils.deep_linking'
```

### Additional information

ImportError: cannot import name 'get_start_link' from 'aiogram.utils.deep_linking'

**Comment by JrooTJunior** [comment]
This function was changed, please read the docs: https://docs.aiogram.dev/en/dev-3.x/utils/deep_linking.html
