### ISSUE TITLE
updated telgram url chanel fragment

### ISSUE THREAD

**Issue by nurmukhammaddev** [aiogram/aiogram#1378]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

how to change fragment telegram channel username with python ?

### Python version

how to change fragment telegram channel username with python ?

### aiogram version

how to change fragment telegram channel username with python ?

### Expected behavior

how to change fragment telegram channel username with python ?

### Current behavior

how to change fragment telegram channel username with python ?

### Steps to reproduce

how to change fragment telegram channel username with python ?

### Code example

```python3
how to change fragment telegram channel username with python ?
```

### Logs

```sh
how to change fragment telegram channel username with python ?
```

### Additional information

how to change fragment telegram channel username with python ?

**Comment by tshipenchko** [comment]
@nurmukhammaddev, I don't think that BotAPI has such method available. But looks like you can do it using client API. For example with [UpdateUsernameRequest](https://tl.telethon.dev/methods/channels/update_username.html) and [ToggleUsernameRequest](https://tl.telethon.dev/methods/channels/toggle_username.html). Not sure that it will work properly with fragment, but ToggleUsernameRequest looks like method you need.

**Comment by JrooTJunior** [comment]
Telegram Bot API has no such method, just check the documentation: https://core.telegram.org/bots/api
