### ISSUE TITLE
JSONStorage and PickleStorage aren't persistent

### ISSUE THREAD

**Issue by Birdi7** [aiogram/aiogram#138]
## Context

* Operating System: Linux Linux Mint 19.1 Tessa
* Python Version: 3.7.1
* aiogram version: 2.2
* aiohttp version: 3.5.4

## Expected Behavior
The user's states will be saved with calling 
```python3
await dispatcher.storage.close()
await dispatcher.storage.wait_closed()
``` 
on shutdown and after the restart will stay the same as before.

## Current Behavior

The states are not saved on the disk, the empty object is saved instead. 

## Failure Information

During the shutdown, the storage makes 2 writing operations on the disk: first one with the correct data and the second with an empty object. The invocation of dispatcher.storage.close() performs these 2 operations. 
There is no bug in restoring data: if saving was successful, everything works correctly. 

### Steps to Reproduce

1. Run [this](https://gist.github.com/Birdi7/ffb3077b89d81f897df0d51072a8dbbd) gist. The JSONStorage is used there, but the situation with the PickleStorage is the same
2. Set your state with `/s1` or `/s2` and check if it is set with `/g`
3. Restart the script. An empty object will be saved In your "fsm_data.json" file 
4. Check that your state has changed after rebooting with `/g`

**Comment by Birdi7** [comment]
My investigation leds me to the following thoughts: 
If you delete the `on_shutdown` from your code, the storage will save the states. This happens because the aiogram's executor by itself calls the `dispatcher.storage.close()` and `dispatcher.storage.wait_closed()` [here](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/utils/executor.py#L312). When you have the `on_shutdown` function in your code, the flow is the following:
1. `storage.close()` is invoked by the aiogram's executor in coroutine `_shutdown()`. Inside it, the data is saved on disk and cleared
2. then, [here](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/utils/executor.py#L366) your `on_shutdown` coroutine gets invoked. As it invokes `storage.close()` too, the empty(from the previous step) data is saved on disk(and, as json and pickle modules replace the whole content in the destination with new information, the old info gets wiped and the new(empty) data is written).

The same flow works with other storages(with redis, in particular) because they append the data unlike `json` and `pickle` do. Now i am not sure, that there is a bug, because all you need to do is to use these storages without calling `dp.storage.close()` on your own

**Comment by JrooTJunior** [comment]
Yep. If you using executor from the latest version of aiogram you don't need to close storage manualy it will be called automatically by the executor.
