### ISSUE TITLE
Add aiohttp=3.9.x support for aiogram 2.25.x

### ISSUE THREAD

**Issue by DAKExDUCK** [aiogram/aiogram#1380]
### aiogram version

2.x

### Problem

#9 61.98 ERROR: Cannot install -r requirements.txt (line 1) and aiohttp==3.9.0 because these package versions have conflicting dependencies.
#9 61.98 
#9 61.98 The conflict is caused by:
#9 61.98     The user requested aiohttp==3.9.0
#9 61.98     aiogram 2.25.1 depends on aiohttp<3.9.0 and >=3.8.0

### Possible solution

How i can see, there is no code that should be changed for [aiohttp v3.9.x](https://docs.aiohttp.org/en/v3.9.1/changes.html)

Maybe just need to upgrade requirements.txt

### Additional information

![image](https://github.com/aiogram/aiogram/assets/63103528/07b80226-01b8-453e-a7a8-11bd0ba85db6)
no big changes, just fixes
================================================================================
![image](https://github.com/aiogram/aiogram/assets/63103528/9a461e67-5019-452c-a1c5-378509eb8dc9)
![image](https://github.com/aiogram/aiogram/assets/63103528/1a3f9021-d148-4a53-9aa2-b390256332e2)
Some deprecated and a lot of bug fixes, improvals
================================================================================

**Comment by JrooTJunior** [comment]
2.x version will no longer be updated.

> no big changes, just fixes

Dropping support of Python 3.7 is a big change, because 2.x version works on Python 3.7

**Comment by JrooTJunior** [comment]
You should use aiogram 3.x to use aiohttp 3.9
