### ISSUE TITLE
I18n context is not passed to error handler

### ISSUE THREAD

**Issue by pavelmakis** [aiogram/aiogram#1381]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

MacOS Sonoma 14.1.1

### Python version

3.11.6

### aiogram version

3.2.0

### Expected behavior

The exception handler receives the same I18n context as the handler that raised the exception.

### Current behavior

After the exception handler is called, it retrieves the I18n object via function arguments, but the I18n context is not set and rises `LookupError: I18n context is not set` while trying to run `get_i18n()`.

### Steps to reproduce

1. Create bot with I18n middleware
2. Create handler than raises custom exception
3. Create error handler and attach it to the same router as handler in step 2
4. Trigger message handler 

### Code example

```python3
from aiogram.utils.i18n import gettext as _

@router.message(F.text == "/start")
async def answer_start_cmd(msg: Message, i18n: I18n) -> None:
    await msg.answer(text=_("Hello")) # works as expected
    raise ExampleError

@router.error(ExceptionTypeFilter(ExampleError))
async def handle_example_err(event: ErrorEvent, msg: Message, i18n: I18n) -> None:
    await msg.answer(_("Exception rised")) # raises LookupError: I18n context is not set
```

### Logs

```sh
File "/Users/pavelmakis/Developer/telegram-bots/bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/router.py", line 136, in _propagate_event
    response = await observer.trigger(event, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelmakis/Developer/telegram-bots/bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/telegram.py", line 121, in trigger
    return await wrapped_inner(event, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelmakis/Developer/telegram-bots/bot/.venv/lib/python3.11/site-packages/aiogram/dispatcher/event/handler.py", line 43, in call
    return await wrapped()
           ^^^^^^^^^^^^^^^
  File "/Users/pavelmakis/Developer/telegram-bots/bot/bot/handlers/errors.py", line 25, in handle_categories_not_set_error
    text=_("Exception rised"),
         ^^^^^^^^^^^^^^^^^^^^
  File "/Users/pavelmakis/Developer/telegram-bots/bot/.venv/lib/python3.11/site-packages/aiogram/utils/i18n/context.py", line 15, in gettext
    return get_i18n().gettext(*args, **kwargs)
           ^^^^^^^^^^
  File "/Users/pavelmakis/Developer/telegram-bots/bot/.venv/lib/python3.11/site-packages/aiogram/utils/i18n/context.py", line 10, in get_i18n
    raise LookupError("I18n context is not set")
LookupError: I18n context is not set
```

### Additional information

I saw issue #726 but it seems that was about access to i18n in error handlers, not about context reset

**Comment by pavelmakis** [comment]
```python
# I18n configuration
i18n = I18n(path=config.LOCALES_DIR, default_locale="en", domain="telexpense")

class BotI18nMiddleware(I18nMiddleware):
    async def get_locale(self, event: TelegramObject, data: dict[str, Any]) -> str:
        return 'en'


# Initializing bot
bot = Bot(token=TOKEN, parse_mode="HTML")

# Initializing dispatcher
dp = Dispatcher(bot=bot)
dp.update.outer_middleware(BotI18nMiddleware(i18n))
```

I simplified middleware logic for this example. Actually I worked with I18n and aiogram many times before and there was no issues with that. I have few others middlewares but I18n middleware is added to `update.outer_middleware` and is almost first registered middleware (only db session opener is earlier).

**Comment by el-bekasto** [comment]
Hello, I'm having same issue. I set my middleware same way as @JrooTJunior suggested.
```
i18n = I18n(path='locales', default_locale='RU', domain='messages')
LanguageMiddleware(i18n).setup(dp)
```
`LanguageMiddleware` is my custom middleware, nothing special in there
Error occurs when I use lazy_gettext
```
from aiogram.utils.i18n import lazy_gettext as __
@r.message(or_f(F.text == f'🏠{__("Main")}', Command('start')))
...
```

**Comment by JrooTJunior** [comment]
It doesnt works because you use lazy gettext inside f-string, but f-string is not lazy and imediatelly translate your text.
