### ISSUE TITLE
Bot API 7.0

### ISSUE THREAD

**Issue by Desiders** [aiogram/aiogram#1386]
### aiogram version

3.x

### Problem

Bot API 7.0 is released

### Possible solution

https://core.telegram.org/bots/api#december-29-2023

**Comment by JrooTJunior** [comment]
Thanks for the issue.

Already implemented, it will be ready for release today or tomorrow.

In most of cases i have ready to release of the aiogram at the same time as the public Bot API release is published, but I had a rough week, so, I didn't have time after my job to prepare it ahead of time, sorry for the delay.
