### ISSUE TITLE
Dynamic callback pydantic error

### ISSUE THREAD

**Issue by denlycode** [aiogram/aiogram#1391]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11

### Python version

Python 3.10.1

### aiogram version

3.3.0

### Expected behavior

Сreate an inline button where an argument of type CallbackData is specified as the callback data

### Current behavior

1 validation error for InlineKeyboardButton
callback_data
  Input should be a valid string [type=string_type, input_value=AdminAction(action=<Actio...hat_id=123, user_id=123), input_type=AdminAction]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type

### Steps to reproduce

Create a InlineKeyboardButton and set callback_data with CallbackData type

### Code example

```python3
class Action(str, Enum):
    ban = "ban"
    kick = "kick"
    warn = "warn"

class AdminAction(CallbackData, prefix="adm"):
    action: Action
    chat_id: int
    user_id: int

try:
        keyboard = InlineKeyboardBuilder()

        btn = InlineKeyboardButton(text="my text", callback_data=AdminAction(action=Action.ban, chat_id=123, user_id=123),)
        keyboard.button(btn)
    except Exception as e:
        print(e) # 1 validation error for InlineKeyboardButton
```

### Logs

```sh
1 validation error for InlineKeyboardButton
callback_data
  Input should be a valid string [type=string_type, input_value=AdminAction(action=<Actio...hat_id=123, user_id=123), input_type=AdminAction]
    For further information visit https://errors.pydantic.dev/2.5/v/string_type
```

**Comment by JrooTJunior** [comment]
Is not bug. You should read the docs: https://docs.aiogram.dev/en/dev-3.x/dispatcher/filters/callback_data.html#usage

![image](https://github.com/aiogram/aiogram/assets/6726423/8f62166a-2cfa-4f72-b9df-5a242f45b073)

Also method `.button` doesn't accept already constructed button as an argument: https://docs.aiogram.dev/en/dev-3.x/utils/keyboard.html#inline-keyboard

So, you should use it like this:

```python
keyboard = InlineKeyboardBuilder()
keyboard.button(text="my text", callback_data=AdminAction(action=Action.ban, chat_id=123, user_id=123))
```
