### ISSUE TITLE
Getting "Flood control exceeded on method 'GetUpdates'"

### ISSUE THREAD

**Issue by Chenger1** [aiogram/aiogram#1401]
Have a very simple bot:
`@dp.channel_post()`
`async def echo_handler(message: types.Message) -> None:`
`    await service.prepare(message.text)`

Each received message we proceed and send special event to another service.
And i received this error: 
`ERROR:aiogram.dispatcher:Failed to fetch updates - TelegramRetryAfter: Telegram server says - Flood control exceeded on method 'GetUpdates'. Retry in 5 seconds.`

if it is important, every message in this channel contains emojis: 🟢, 🌟, etc,
Bot`s configuration - default which i got from the documentation. 

Telegram Api documentation says we can use offset parameter to, but can`t find it in aiogram. 
So, how can i fix this?

**Comment by Olegt0rr** [comment]
1. Your handler is OK, but we need minimal reproducible example to help you.
2. Emoji is not important, it's just a content
3.  `TelegramRetryAfter` is a result of 2 kinds of activities. Either you're really DoSing Telegram by many request, or Telegram API Server rebooting right now

**Comment by Chenger1** [comment]
Cant understand how i can send too many requests if i using default aiogram configuration.
I caught this error several times for the past few days, so what minimal reproducible example should be?

For example: full code of by bot.
`import asyncio`
`import sys`
`from os import getenv`
`from aiogram import Bot, Dispatcher, types`
`from aiogram.enums import ParseMode`
`from services import MyService`

`TOKEN = getenv("TELEGRAM_BOT_TOKEN")`
`dp = Dispatcher()`
`service = MyService()`

`@dp.channel_post()`
`async def echo_handler(message: types.Message) -> None:`
`    await service.prepare(message.text)`

`async def main() -> None:`
`    bot = Bot(TOKEN, parse_mode=ParseMode.HTML)`
`    await dp.start_polling(bot)`

`if __name__ == "__main__":`
`    asyncio.run(main())`

**Comment by Olegt0rr** [comment]
Edited your msg. If you post a code - use triple quotes instead of single

There's nothing wrong with your code.
Several times in few days - it's a Telegram Bot API maintenance.

**Comment by Chenger1** [comment]
Okay, thank you.
