### ISSUE TITLE
Global `parse_mode` (if set in bot) breaks parse mode for replies with Quotes

### ISSUE THREAD

**Issue by wkpn** [aiogram/aiogram#1406]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

any

### Python version

any

### aiogram version

3.3.0 and up (latest commit is affected as well)

### Expected behavior

reply with a quote is correctly sent to chat

### Current behavior

raises `QUOTE_TEXT_INVALID` exception

### Steps to reproduce

1. Given: a message with some markdown text known to bot. Let's say the text is `normal bold italic spoiler` (each word is markdowned as titled, e.g. `normal` has no markdown, `bold` is bold and so on)

2. I want to quote the `bold` part. For that I construct my request roughly as:

```
bot = Bot(token=BOT_TOKEN, parse_mode=ParseMode.MARKDOWN_V2)

...

await bot.send_message(
    text="example text",
    chat_id=CHAT_ID,
    message_thread_id=MESSAGE_THREAD_ID,
    reply_parameters=ReplyParameters(
        message_id=MESSAGE_ID_TO_REPLY_TO,
        quote="bold",
        quote_entities=[
            MessageEntity(type='bold', offset=0, length=4)
        ]
    )
```

3. Expected: 
<img width="427" alt="image" src="https://github.com/aiogram/aiogram/assets/1161827/dad94c94-0177-4c1a-bee1-25b975e422a2">

4. Actual:
```
File "/opt/python/aiogram/client/session/base.py", line 120, in check_response
raise TelegramBadRequest(method=method, message=description)
Telegram server says - Bad Request: QUOTE_TEXT_INVALID
```

5. There is no error if the quoted part doesn't contain markdown entities

### Logs

```sh
File "/opt/python/aiogram/client/session/base.py", line 120, in check_response
raise TelegramBadRequest(method=method, message=description)
Telegram server says - Bad Request: QUOTE_TEXT_INVALID
```

### Additional information

Manually adding `quote_parse_mode=None` to `ReplyParameters` fixes everything, so that kind of makes `quote_entities` and `quote_parse_mode` mutually exclusive as of right now

**Comment by JrooTJunior** [comment]
Expected behavior.

You should excplicitly set parse mode in the API method if it is not the same as globally defined.

So, when`quote_parse_mode` is not set the default global value will be used, if it is explicitly specified as None - None value will be skipped.

**Comment by wkpn** [comment]
> You should excplicitly set parse mode in the API method if it is not the same as globally defined.

I'm not sure I need to specify `parse_mode` if I have already provided full list of `MessageEntity`, just as I'm not adding a list of `MessageEntity` manually when I want to send markdown messages, I just do:

```
bot = Bot(..., parse_mode=ParseMode.MARKDOWN_V2)
text = f'{md.bold("Hello"), world'
bot.send_message(text=text, ...)
```

I'm just saying that the global parse mode should not be applied automatically when `quote_entities` are already there
that pretty much applies to any other case when a user copies text/entities manually and uses them somewhere else, because even in docs it is stated that:
<img width="832" alt="image" src="https://github.com/aiogram/aiogram/assets/1161827/3f319117-ec5b-4dde-ab4b-82b6c00f2c02">

so if the latter is used it is expected that there is no need for `parse_mode`, the entities already define it, but still it will be applied from a global default and the thing will just break

**Comment by JrooTJunior** [comment]
Global `parse_mode` means that this value should be used wherever possible.
So, if you specify `bot = Bot(..., parse_mode=ParseMode.MARKDOWN_V2)` - you explicitly says "I want to automatically set in all places parse mode as MarkdownV2 despite everything until i change my mind in explicit way".
