### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by AlessioMeloni** [aiogram/aiogram#141]
**I had an internal server error[500] and the script has been stopped.**
**error:** https://core.telegram.org/api/errors#500-internal
**Script output:** `ClientError Internal Server Error (Code: 500, Response: Oops, an error occurred.)`

**The question is:** _How can we catch this error for don't stop the script in the future?_

**Comment by JrooTJunior** [comment]
Can you provide traceback of this error?

**Comment by JrooTJunior** [comment]
@AlessioMeloni, FYI

**Comment by JrooTJunior** [comment]
I'll close the issue. Reopen if you have more information about that.
