### ISSUE TITLE
Aiogram "forgets" video link in a day (video is on telegram servers)

### ISSUE THREAD

**Issue by KeyboardGecko** [aiogram/aiogram#1415]
### Checklist

- [ ] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

windows 7

### Python version

3.11

### aiogram version

3.4

### Expected behavior

So, I have a bot. It answers with a video, if there's no video it posts a picture instead. 

The link works for about a day. Then, to make it enabled, I have to forward this video to a bot one more time. Then it lasts another day.

### Current behavior

Forgets the link in a day.

### Steps to reproduce

look into code for example

### Code example

```python3
`async def post_video(chat_id):
        try:
            await bot.send_video(chat_id=chat_id, video='BAACAgIAAx0CVBeD_wACAYdlpAABrOYmKm-LDKToqz8cchDmsQIAAjo-AAL1SRhJamBnQTY0JT80BA', caption = 'Hey user!', reply_markup=make_keyboard().as_markup(), parse_mode = 'HTML')
        except Exception as error:
            print(error)
            pic = FSInputFile("C:/pic.jpg")
            await bot.send_photo(chat_id=chat_id, photo=pic, caption = 'Hey user!', reply_markup=make_keyboard().as_markup(), parse_mode = 'HTML')`
```

### Logs

```sh
Telegram server says - Bad Request: wrong file identifier/HTTP URL specified

(when forgetting about vid)
```

**Comment by Olegt0rr** [comment]
Telegram does not promise that it will store your data forever. 
Therefore, if the identifier gives an error, then provide re-downloading in your application
