### ISSUE TITLE
Make the message parameter optional in handlers

### ISSUE THREAD

**Issue by makarworld** [aiogram/aiogram#1416]
### aiogram version

3.x

### Problem

I have implemented my own class with all the event operations and now I want to use it as:
```python
@router.message()
async def any_message(m: MyMessageClass):
    await m.answer("Ok")
```
but I get the error `any_message() got multiple values for argument 'm'`.

This will only work if I add 1 more parameter to func: `async def any_message(_, m: MyMessageClass):`

### Possible solution

Event must be added as a 'message' and 'callback' parameter to the data dict in the global middleware. (or add a new parameter in the router, e.g. `event_key`)

### Code example

```python3
from aiogram import Bot, Dispatcher, Router

class MyMessageClass: ...

dp = Dispatcher()
# dp.message.middleware(MyMiddleware())
# dp.callback_query.middleware(MyMiddleware())

router = Router(name = "test")
dp.include_router(router)

@router.message()
async def any_message(m: MyMessageClass):
    await m.any_my_func()

# run
bot = Bot(token = os.getenv("BOT_TOKEN"), disable_web_page_preview = True, parse_mode = "HTML")
dp.run_polling(bot)
```

**Comment by JrooTJunior** [comment]
Your code example seems irrelevant to the description. I don't understand what you are actually trying to solve.
