### ISSUE TITLE
Set Custom URL for Multiple Games

### ISSUE THREAD

**Issue by 0xSaurabhx** [aiogram/aiogram#1420]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Ubuntu 20.04

### Python version

3.8.10

### aiogram version

2.25.1

### Expected behavior

there should be any way to set custom url for each games

### Current behavior

i get error if i try to use any method

### Steps to reproduce

set game shortname, bot token.
then bot = Bot(token=token)
dp = Dispatcher(bot, storage=MemoryStorage())
start msg handler
game command:
@dp.callback_query_handler(lambda c: c.data and c.data.startswith('game'))
async def process_callback(callback_query: types.CallbackQuery):
    await bot.answer_callback_query(callback_query.id, url=url)
......

### Code example

```python3
@dp.inline_handler()
async def inline_query_handler(inline_query: types.InlineQuery):
    games = [
        types.InlineQueryResultGame(
            id='game1',
            game_short_name='demo1'
        ),
        types.InlineQueryResultGame(
            id='game2',
            game_short_name='demo2'
        ),

    ]

    await bot.answer_inline_query(inline_query.id, results=games)
```

**Comment by Olegt0rr** [comment]
@0xSaurabhx, is it reproducible on 3.x verion?
