### ISSUE TITLE
Add function get_value to FSMContext

### ISSUE THREAD

**Issue by wrrrzr** [aiogram/aiogram#1431]
### aiogram version

3.x

### Problem

In a situation where you only need to take one value in FSMContext handler, you need to write 2 lines of code to take value

### Possible solution

Add a get_value function for FSMContext that takes value by key

### Code example

```python3
# before
data = await state.get_data()
name = data["name"]

# after
name = await state.get_value("name")
```

**Comment by infikot** [comment]
_# before
data = await state.get_data()
name = data["name"]

# after
name = await state.get_value("name")_


data = await state.get_data()["name"] 

wouldn't that work? :3
