### ISSUE TITLE
Update pydantic 2.6.4

### ISSUE THREAD

**Issue by tranvannhat** [aiogram/aiogram#1448]
### aiogram version

3.x

### Problem

Please update Pydantic to latest version 
![Screenshot 2024-04-04 at 16 39 42](https://github.com/aiogram/aiogram/assets/28804941/e7b2f93c-faa2-4391-81e7-3bfcd36011a1)

### Possible solution

Please update Pydantic to latest version

**Comment by Olegt0rr** [comment]
Version already bumped

Wait for release or use version direct from master branch
