### ISSUE TITLE
 Error serializing to JSON: PydanticSerializationError: Unable to serialize unknown type: <class 'aiogram.client.default.Default'>

### ISSUE THREAD

**Issue by derby-vv** [aiogram/aiogram#1450]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11

### Python version

3.11

### aiogram version

3.4.1

### Expected behavior

Correctly serialized json of Message object

### Current behavior

Seems like aiogram doesn't properly describe pydantic Default class for link_preview_options.

### Steps to reproduce

1. Send message to bot with link preview
2. Try to call model_dump_json method on it

### Code example

```python3
>>> msg.model_dump(exclude_none=True) # default is python mode
 ... link_preview_options=LinkPreviewOptions(is_disabled=<Default('link_preview_is_disabled')>, url='http://t.me/ffffff', ...

>>> msg
 ... link_preview_options=LinkPreviewOptions(is_disabled=<Default('link_preview_is_disabled')>, url='http://t.me/ffffff', prefer_small_media= ...

>>> msg.model_dump_json(exclude_none=True) #trying to serialize to json
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: PydanticSerializationError: Unable to serialize unknown type: <class 'aiogram.client.default.Default'>
```

**Comment by JrooTJunior** [comment]
If you want to dump objects with the `Default` placeholder you should use serializer from the Bot session like
```python
files = {}
dump = bot.session.prepare_value(message, bot=bot, files=files)
```
Note that if you have customized global link preview options dumped object will be affected too in due to this values is unset in the original object.

---

#1483 seems little bit weird, i need to research to find another solution.

**Comment by DanZ-ix** [comment]
@JrooTJunior 
As far as i understood, link_preview_is_disabled is bot parameter, not message. Message object just inherits the value from the bot, when it is sent. But the Message objects are not connected to a Bot object, so we cant really get link_preview_is_disabled value before the message is sent. So there is no way to serialize this value before the message is sent using a Bot object, therefore i think its ok to serialize those variables without a particular value. I just need to be sure that those objects are deserialized in a right way. I'll try to update that PR))

**Comment by JrooTJunior** [comment]
introduced a new utility to deserialize any Telegram object into a JSON-compatible object (dict) in #1515

```python
message_data = deserialize_telegram_object_to_python(message)
```

This solution is based on the `session.prepare_value` method.
