### ISSUE TITLE
message.get_url() in chat with topics -> wrong url

### ISSUE THREAD

**Issue by Robotvasya** [aiogram/aiogram#1451]
### aiogram version

3.x

### Problem

The method message.get_url() returns wrong url when it call in chat with topics:
Returns `https://t.me/username/message_id`  but should `https://t.me/username/message_thread_id/message_id`

https://github.com/aiogram/aiogram/blob/acf52f468cae79b3511c2939cf39a801fa47f9f3/aiogram/types/message.py#L3750

I have not checked whether there is such a problem in other methods of the Message object. And I haven’t checked whether this method is used in other parts of the aiogram framework.

### Possible solution

possible patch 

```
--- a/.venv/lib/python3.10/site-packages/aiogram/types/message.py	
+++ b/.venv/lib/python3.10/site-packages/aiogram/types/message.py	(date 1712428103364)
@@ -3765,8 +3765,13 @@
             else self.chat.username
         )
 
+        message_value = (
+            f"{self.message_id}"
+            if not self.message_thread_id
+            else f"{self.message_thread_id}/{self.message_id}"
+        )
 
-        return f"https://t.me/{chat_value}/{self.message_id}"
+        return f"https://t.me/{chat_value}/{message_value}"
 
     def react(
         self,
```

**Comment by Olegt0rr** [comment]
Why don't you send a PR?

**Comment by Robotvasya** [comment]
I'll send PR, no problem.  I'm afraid that this behavior not only in this function but also remains somewhere else.
