### ISSUE TITLE
Mixed-Format Sticker Packs

### ISSUE THREAD

**Issue by Oven29** [aiogram/aiogram#1455]
### aiogram version

3.x

### Problem

[Telegram update 31 march 2024 ](https://core.telegram.org/bots/api-changelog#march-31-2024) with Mixed-Format Sticker Packs

### Possible solution

- Removed the fields is_animated and is_video from the class [StickerSet](https://core.telegram.org/bots/api#stickerset).
- Added the field format to the class [InputSticker](https://core.telegram.org/bots/api#inputsticker).
- Removed the parameter sticker_format from the method [createNewStickerSet](https://core.telegram.org/bots/api#createnewstickerset).
- Added the parameter format to the method [setStickerSetThumbnail](https://core.telegram.org/bots/api#setstickersetthumbnail).

**Comment by Vadim-Khristenko** [comment]
This was fixed 4 days ago in AIogram 3.5.0!
I think you can solve this problem by updating to AIogram 3.5.0.
`pip install -U Aiogram`

So I think you can close this issue. :)
