### ISSUE TITLE
aiogram\utils\formatting.py (as_section)

### ISSUE THREAD

**Issue by post1917** [aiogram/aiogram#1465]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 10

### Python version

3.12

### aiogram version

3.4.1

### Expected behavior

aiogram\utils\formatting.py (as_section)

...
return Text(title, "\n", **as_list(*body)**)

### Current behavior

aiogram\utils\formatting.py (as_section)

```
def as_section(title: NodeType, *body: NodeType) -> Text:
    """
    Wrap elements as simple section, section has title and body

    :param title:
    :param body:
    :return: Text
    """
    return Text(title, "\n", *body)
```

### Steps to reproduce

Not required

### Additional information

It is necessary to use "as_list(*body)" instead of "*body", because "\n" characters are not added to the end of each body element.

**Comment by Olegt0rr** [comment]
@post1917, thanks for report. 

Feel free to create PR with fix and related test case

**Comment by JrooTJunior** [comment]
Is not a bug. Expected behavior.

Section can not only be a list, So, it is is important that there is an opportunity to create section with any type of the content.
