### ISSUE TITLE
How to use custom emoji in aiogram message formatting

### ISSUE THREAD

**Issue by Ardanila** [aiogram/aiogram#1466]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Mac OS Sonoma

### Python version

Python 3.8.19

### aiogram version

3.4.1

### Expected behavior

I expect the bot to send custom (premium) emoji when a custom emoji is provided by user.

### Current behavior

When a custom emoji is provided, the bot sends a basic emoji (e.g., 😎) instead of the corresponding custom (premium) emoji.

### Steps to reproduce

1. User sends a message containing a custom emoji.
2. The bot extracts the custom emoji ID from the message.
3. The bot attempts to retrieve the custom emoji using the get_custom_emoji_stickers method provided by Aiogram.
4. The bot sends a message with the retrieved custom emoji sticker.

### Code example

```python3
...

class UserState(StatesGroup):
waiting_for_emoji = State()

...

@dp.message(CommandStart())
async def cmd_start(message: Message, state: FSMContext):

    await message.answer("Welcome! Please send the custom emoji you want to use.")
    await state.set_state(UserState.waiting_for_emoji)

...

@dp.message(Command('set_emoji'))
async def cmd_set_emoji(message: Message, state: FSMContext):
    await message.answer("Please send the custom emoji you want to use.")
    await state.set_state(UserState.waiting_for_emoji)

...

@dp.message(UserState.waiting_for_emoji)
async def process_emoji(message: Message, state: FSMContext):
    if message.text and message.text.startswith('/'):
        await message.answer("Invalid input. Please send a custom emoji.")
        return

    emoji = message.text
    custom_emoji_id = None

    if message.entities:
        for entity in message.entities:
            if entity.type == 'custom_emoji':
                custom_emoji_id = entity.custom_emoji_id
                break

    if custom_emoji_id:
        await state.update_data(custom_emoji_id=custom_emoji_id)
        await message.answer(f"Custom emoji {emoji} set successfully!")

...

async def process_text_common(text, message, state):

state_data = await state.get_data()
custom_emoji_id = state_data.get('custom_emoji_id')

await message.answer(f"{custom_emoji_id}", parse_mode="HTML", reply_markup=keyboard)
```

**Comment by remixer-dec** [comment]
It also works in group chats without custom username if your group chat is boosted enough to support custom emoji pack for all members

**Comment by newmetastudio** [comment]
Hi, to quickly get the ID of custom emojis in Telegram, you can also use the bot: [https://Emoji_ID_Extractor_bot](https://t.me/Emoji_ID_Extractor_bot)
