### ISSUE TITLE
Get user from `chat_boost` with source `ChatBoostSourcePremium`

### ISSUE THREAD

**Issue by Desiders** [aiogram/aiogram#1472]
### aiogram version

3.x

### Problem

Currently, user from chat boost always `None` in `UserContextMiddleware`: https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/dispatcher/middlewares/user_context.py#L117-L118, but `chat_boost` with source `ChatBoostSourcePremium` always has user that boosted the chat: https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/types/chat_boost_source_premium.py#L21.

### Possible solution

I think it makes sense to add a new condition in the middleware like in https://github.com/aiogram/aiogram/blob/dev-3.x/aiogram/dispatcher/middlewares/user_context.py#L81

**Comment by Desiders** [comment]
I can do it if you agree

**Comment by Olegt0rr** [comment]
LGTM, feel free to make PR
