### ISSUE TITLE
Message class bug 

### ISSUE THREAD

**Issue by 0xlucyy** [aiogram/aiogram#1475]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

MacOS big sur v 11.5.2

### Python version

3.8.9

### aiogram version

2.25.1

### Expected behavior

When I create a Message object, I should be able to access all the message values passed into the message at message object instantiation.

The code in question

```
from aiogram.types import Message, User, Chat
from datetime import datetime

def create_message(chat_id, user_id):
  # Create a Message object
  user = User(id=user_id)
  chat = Chat(id=chat_id)
  current_timestamp = int(datetime.now().timestamp())

  message = Message(message_id=0, date=current_timestamp, chat=chat, from_user=user, text="/pull")
  
  print(message.chat.id) # Prints the chat id
  print(message.text) # Prints /pull
  print(message.date) # Prints datetime date
  print(message.from_user.id) # <---- Supposed to print user id ---->

  return message
  ```

### Current behavior

Please notice the `message` object  below, as described in `Expected Behavior`

```
(Pdb) type(message)
<class 'aiogram.types.message.Message'>

(Pdb) type(user)
<class 'aiogram.types.user.User'>

(Pdb) type(chat)
<class 'aiogram.types.chat.Chat'>

(Pdb) vars(message)
{
  '_conf': {},
  '_values': {
     'message_id': 0, 
     'date': datetime.datetime(2024, 5, 1, 13, 56, 49), 
     'chat': <Chat {"id": -941331806}>, 
     'from_user': <User {"id": 519327325}>, 
     'text': '/pull'}
  }
```

Here are the following outputs for the `print` statements described in `Expected Behavior`

```
(Pdb) message.chat.id
-941331806

(Pdb) message.text
'/pull'

(Pdb) message.date
datetime.datetime(2024, 5, 1, 13, 56, 49)

(Pdb) message.from_user.id
*** AttributeError: 'NoneType' object has no attribute 'id'

(Pdb) message.from_user
(Pdb)

(Pdb) dir(message.from_user)
['__bool__', '__class__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']
```

I cannot access the `user id` from the message object that has been created!

### Steps to reproduce

1. create a message object with the values from my example
2. attempt to access the message values

### Additional information

This message object is being created on behave of a user, not by the user themselves.
The bot is taking action on behave of a user, in case a user times out or is inactive for whatever reason.

**Comment by 0xlucyy** [comment]
I think I found a work around

Error producing code
```
  message = Message(message_id=0, date=current_timestamp, chat=chat, from_user=user, text="/pull")
  message.from_user.id # ERROR
```

Work around code
```
  message = Message(message_id=0, date=current_timestamp, chat=chat, via_bot=user, text="/pull")
  message.via_bot.id # 519327325
```

**Comment by JrooTJunior** [comment]
2.25.1 is no longer supported.

**Comment by 0xlucyy** [comment]
wow, sad!

**Comment by JrooTJunior** [comment]
Please update your code to 3.x version ([Migration guide](https://docs.aiogram.dev/en/dev-3.x/migration_2_to_3.html))
