### ISSUE TITLE
Typo in `__slots__` field of class `MagicData`

### ISSUE THREAD

**Issue by K1rL3s** [aiogram/aiogram#1485]
Based on [PLC0205](https://docs.astral.sh/ruff/rules/single-string-slots/), in the class `MagicData` field `__slots__` should be a tuple, not a string. This situation also does not occur in the code, so it is most likely a typo.

[Current code](https://github.com/aiogram/aiogram/blob/a7d3e9a72047037d85a5907ca503b52c6c72ca00/aiogram/filters/magic_data.py#L14): 
```python
class MagicData(Filter):
    __slots__ = "magic_data"
```

Expected code: 
```python
class MagicData(Filter):
    __slots__ = ("magic_data",)
```

**Comment by JrooTJunior** [comment]
Fixed (without changelog)
