### ISSUE TITLE
business_opening_hours is not shown in chat information.

### ISSUE THREAD

**Issue by proDreams** [aiogram/aiogram#1490]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Debian 12

### Python version

3.12

### aiogram version

3.6.0

### Expected behavior

I expect to receive information about opening hours in the information about the current chat.

### Current behavior

business_opening_hours=None

### Steps to reproduce

1. Connect the bot to business mode
2. Write a message
3. Check the logs

### Code example

```python3
async def handle_business_message(message: Message):
    print(await bot(GetChat(chat_id=message.chat.id)))
    # or
    print(message.chat)
```

### Additional information

If you make a request directly to Telegram `https://api.telegram.org/BOT_TOKEN/getChat?chat_id=CHAT_ID`, then the necessary information is in the answer.

**Comment by Olegt0rr** [comment]
```python
import logging

from aiogram import Bot, Dispatcher
from aiogram.types import Message

logger = logging.getLogger(__name__)

bot = Bot(token="...")
dp = Dispatcher()


@dp.message()
async def handler(message: Message):
    user = message.from_user

    chat = await bot.get_chat(user.id)
    hours = chat.business_opening_hours

    lines = [str(interval) for interval in hours.opening_hours]
    text = "\n".join(lines)
    await message.answer(text)


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    dp.run_polling(bot)

```
<img width="467" alt="Screenshot 2024-06-06 at 19 37 46" src="https://github.com/aiogram/aiogram/assets/25399456/90e039ec-55fc-44f1-a931-afca56d31ab6">

**Comment by proDreams** [comment]
> Can't reproduce:

I tried to get in the middleware from the data argument, also through the GetChat class. I'll try your option, thanks.

**Comment by Olegt0rr** [comment]
The field in the original API is declared as `Optional`. 
It shouldn't be in the `Chat` object sent with the message, so `message.chat.business_opening_hours` is guaranteed to return `None`
