### ISSUE TITLE
Stories posting

### ISSUE THREAD

**Issue by KhoruzhevskiiGeorgii** [aiogram/aiogram#1491]
### aiogram version

3.x

### Problem

Hi, I want to post stories via script to my telegram channel (say i have stories.mp4 file on my local computer and it should just post it). Is it possible? I did not find anything similar in the documentation

### Possible solution

in the best it would be nice just to have feature "post_stories(channel, file)"

**Comment by JrooTJunior** [comment]
[Telegram Bot API](https://core.telegram.org/bots/api) doesn't have such a method, so this is currently not possible.
