### ISSUE TITLE
Aiogram kills my script

### ISSUE THREAD

**Issue by Eikosa** [aiogram/aiogram#1495]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Ubuntu - 22.04

### Python version

Python 3.10.12

### aiogram version

3.6.0

### Expected behavior

When I run my code with start polling, my bot shuts down without any error, there is no exception.

### Current behavior

.

### Steps to reproduce

?

### Code example

```python3
bot = Bot(token=bot_token, parse_mode="html")
dp = Dispatcher()

async def main_fnc():
    await dp.start_polling(bot)
    print("Bot started.")


loop = asyncio.get_event_loop()
loop.run_until_complete(main_fnc())
```

### Logs

```sh
root@ubuntu-s-4vcpu-16gb-amd-sfo3-01:~# python3 main.py
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @mybot_Bot id=5434332608 - 'My Bot'
INFO:aiogram.event:Update id=95742535 is handled. Duration 2 ms by bot id=5434332608
Killed
root@ubuntu-s-4vcpu-16gb-amd-sfo3-01:~#
```

**Comment by Olegt0rr** [comment]
It's killed by your linux user while trying to exit.
Use docker or service manager to run your app in background
