### ISSUE TITLE
MongoStorage FSM section in documentation doesn't display correctly

### ISSUE THREAD

**Issue by Rishat-F** [aiogram/aiogram#1501]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Ubuntu 20.04 LTS

### Python version

3.10.13

### aiogram version

3.7.0

### Expected behavior

There should be a description of MongoStorage FSM class in [documentation page](https://docs.aiogram.dev/en/dev-3.x/dispatcher/finite_state_machine/storages.html#mongostorage).
![2024-06-01_00-13](https://github.com/aiogram/aiogram/assets/66554797/ee2aa1b1-b413-4d95-a819-5dda92ffd6ef)

### Current behavior

Description of MongoStorage FSM class doesn't displayed on [documentation page](https://docs.aiogram.dev/en/dev-3.x/dispatcher/finite_state_machine/storages.html#mongostorage).

### Steps to reproduce

1. Generate local docs via:
`sphinx-autobuild --watch aiogram/ docs/ docs/_build/`
2. Open FSM MongoStorage section of local documentation on http://127.0.0.1:8000/dispatcher/finite_state_machine/storages.html#mongostorage
3. Make sure MongoStorage class description presented on page
4. Open [FSM MongoStorage section of official documentation page](https://docs.aiogram.dev/en/dev-3.x/dispatcher/finite_state_machine/storages.html#mongostorage)
5. Make sure MongoStorage class description presented on page

**Comment by JrooTJunior** [comment]
Thanks for the report, fixed by adding mongo to the ReadTheDocs configuration.
