### ISSUE TITLE
Bug with reply_to_message

### ISSUE THREAD

**Issue by GentleHedgehog** [aiogram/aiogram#1511]
Aiogram 3.1.1. Ubuntu 20.04, python 3.9.18. 
 The following filter passes all messages (reply and non-reply):

  ```python
  @router.message(F.reply_to_message)
  async def function (message, bot):
  ...
  ```
  For regular messages (not replies), the message object always contains a Not None object in the reply_to_message field (this object always has the same ID and the text field is None).

**Comment by JrooTJunior** [comment]
This can happen only in chats that are forums, since all messages in topics are a response to the message of the beginning of the topic.

You should check type of the reply message to ignore unwanted replies.

**Comment by GentleHedgehog** [comment]
Hello, thank you very much, I couldn't find this information in documentation (aiogram, bot api).
