### ISSUE TITLE
Calling aiogram in an ad-hoc manner?

### ISSUE THREAD

**Issue by devkhan** [aiogram/aiogram#1528]
### aiogram version

both

### Problem

I want to create a webhook for the bot in a serverless fashion (AWS lambda, Google Cloud Functions, Vercel serverless, etc.). But since calling `start_webhook` starts a web server, we can't use them in a serverless mode as they don't give you control over the server and only one end-point is published.

So, instead of running a server, I'd like to call some method that just takes in an update, process it, and exits. I can then call this entrypoint from the request handler of the serverless function. This isn't really serverless specific as I can run it from a non-server environment too.

### Possible solution

I'm not sure if there is already an interface exposed to do this. But I believe something like `notify` or `process_updates` can be used to just call it once and have it exit after that.

Has anyone done something similar before?

### Code example

```python3
# getting the updates from somewhere else, or a different webhook handling server
sample_updates = [
    {
        "update_id": 631673874, 
        "message": {
            "message_id": 4,
            "from": {
                "id": 628865920, 
                "is_bot": false, 
                "first_name": "Devesh",
                "last_name": "Khandelwal", 
                "username": "deveshkhandelwal",
                "language_code": "en"
            },
            "chat": {
                "id": 628865920, 
                "first_name": "Devesh", 
                "last_name": "Khandelwal",
                "username": "deveshkhandelwal", 
                "type": "private"
            }, 
            "date": 1719603023,
            "text": "test"
        }
    },
]

for update in updates:
    results = executor.process_update(update, ...other flags)

print(results)
```

**Comment by devkhan** [comment]
Thanks!

I was about to comment that we should add it to the webhook page in the docs, but I saw that both `feed_update` and `feed_webhook_update` over there. I think I missed it because I'm still on v2.

Is the v2 still supported? If so, can we add this to the docs for v2 as well? I can raise the PR if maintainers are okay with it.

**Comment by Olegt0rr** [comment]
> Is the v2 still supported

v2 is no longer supported
