### ISSUE TITLE
gino and aiogram

### ISSUE THREAD

**Issue by LuckyDenis** [aiogram/aiogram#156]
Good evening, I have a question. I wanted to tie the library `gino`, but quickly how to do it did not figure out who can give advice or have faced with this?

**Comment by JrooTJunior** [comment]
You can use any library with aiogram by following instructions from documentations of this libraries.

Maybe you have more specific question? Or maybe can describe what do you do and what error you got?

**Comment by LuckyDenis** [comment]
@JrooTJunior, I'll forgive you for taking so long to answer. Work) I found a way how to slip `gino` through `middleware`. But faced with another task. As I can not figure out how it was possible to screw out the metric. But perhaps this is no longer the case.

**Comment by LuckyDenis** [comment]
Did so, can someone come in handy.

```
from aiogram.dispatcher.middlewares import BaseMiddleware
from aiogram import types
from gino import Gino

__all__ = ['GinoMiddleware']


class GinoMiddleware(BaseMiddleware):
    def __init__(self, dns):
        self._dns = dns
        super(GinoMiddleware, self).__init__()

    async def on_process_message(self, message: types.Message, data: dict):
        data['conn'] = self.conn

    async def conn(self, sql):
        db = Gino()
        async with db.with_bind(self._dns) as engine:
            async with engine.acquire() as conn:
                rows = await conn.all(
                    sql
                )
        return rows
```

**Comment by gabbhack** [comment]
Perhaps this example will be useful to you.
https://gist.github.com/gabbhack/166699945458cbd90a49bed8af95fbc8

**Comment by LuckyDenis** [comment]
@gabbhack, Yeah, it looks interesting and kind of suits me. Thanks.
