### ISSUE TITLE
Bot API 7.9 paid media breaks get_chat method

### ISSUE THREAD

**Issue by nurikk** [aiogram/aiogram#1561]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Any

### Python version

3.12.4

### aiogram version

3.11.0

### Expected behavior

the bot should corretly handle paid media in get_chat response

### Current behavior

Bot crashes with ValidationError

### Steps to reproduce

Call `get_chat` for any channel with paid media available reaction
```
await bot.get_chat(chat_id='@currencynetwork')
```

### Code example

```python3
bot = Bot(token='token')
await bot.get_chat(chat_id='@currencynetwork')
```

### Logs

```sh
ValidationError
4 validation errors for Response[ChatFullInfo]
result.available_reactions.0.ReactionTypeEmoji.type
  Input should be <ReactionTypeType.EMOJI: 'emoji'> [type=literal_error, input_value='paid', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/literal_error
result.available_reactions.0.ReactionTypeEmoji.emoji
  Field required [type=missing, input_value={'type': 'paid'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
result.available_reactions.0.ReactionTypeCustomEmoji.type
  Input should be <ReactionTypeType.CUSTOM_EMOJI: 'custom_emoji'> [type=literal_error, input_value='paid', input_type=str]
    For further information visit https://errors.pydantic.dev/2.8/v/literal_error
result.available_reactions.0.ReactionTypeCustomEmoji.custom_emoji_id
  Field required [type=missing, input_value={'type': 'paid'}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/missing
```

### Additional information

this behavior only reproducible if chat enabled paid reaction

**Comment by JrooTJunior** [comment]
Fixed in v3.12, please update your installation.

This error caused because a new object has appeared in the API that cannot be deserialized in previous versions when calling the `getChat` method.
