### ISSUE TITLE
Failing to shutdown all bots with Control C

### ISSUE THREAD

**Issue by 0xlucyy** [aiogram/aiogram#1565]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

MacOS Sonoma 14.5

### Python version

Python 3.12.4

### aiogram version

aiogram 3.6.0

### Expected behavior

Bots should shut down 

### Current behavior

Only 1 bot shuts down

### Steps to reproduce

```
# Shared Redis storage for both bots
shared_storage = RedisStorage.from_url('redis://localhost:6379/5')

# botA setup
botA_TOKEN = getenv("botA")
botA_session = AiohttpSession()
botA = Bot(botA_TOKEN, session=botA_session)
dp_a = Dispatcher(storage=shared_storage)


# botB setup
botB_TOKEN = getenv("botB")
botB_session = AiohttpSession()
botB = Bot(botB_TOKEN, session=botB_session)
dp_b = Dispatcher(storage=shared_storage)

logger = logging.getLogger(__name__)

async def run_bot(bot: Bot, dp: Dispatcher, name: str):
    logger.info(f"Starting {name}")
    try:
        await dp.start_polling(bot)
    except asyncio.CancelledError:
        logger.info(f"Polling cancelled for {name}")
        raise
    finally:
        logger.info(f"Stopping {name}")
        await dp.storage.close()
        logger.info(f"{name} storage closed.")
        await bot.session.close()
        logger.info(f"{name} session closed.")
        logger.info(f"Stopped {name}")

async def main():
    logger.info("Started")

    # Use asyncio.TaskGroup for more robust task management
    async with asyncio.TaskGroup() as tg:
        tg.create_task(run_bot(botA, dp_a, "BotA"))
        tg.create_task(run_bot(botB, dp_b, "BotB"))

    logger.info("Both bots have completed. All tasks are done.")

if __name__ == '__main__':
    try:
        logger.info("Starting the main event loop.")
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info('Received exit signal via keyboard interrupt')

```

I can issue individual commands to both bots and the bots work as expected when they are live.

However, when I issue command `control c` from my keyboard, only `botB` shuts down, `botA` remains and I am unable to shut the bot down from the terminal. I have to close my terminal tab to shut `bot_a` down.

### Logs

When I start the program, the terminal logs look like this

```
2024-08-20 14:23:29,119 - __main__ - INFO - [rr_bot.py:1304] - Starting the main event loop.
2024-08-20 14:23:29,120 - __main__ - INFO - [rr_bot.py:1293] - Started
2024-08-20 14:23:29,120 - __main__ - INFO - [rr_bot.py:1278] - Starting BotA
2024-08-20 14:23:29,121 - __main__ - INFO - [rr_bot.py:1278] - Starting BotB
^C2024-08-20 14:23:35,995 - __main__ - INFO - [rr_bot.py:1285] - Stopping BotB
2024-08-20 14:23:35,996 - __main__ - INFO - [rr_bot.py:1287] - BotB storage closed.
2024-08-20 14:23:35,996 - __main__ - INFO - [rr_bot.py:1289] - BotB session closed.
2024-08-20 14:23:35,996 - __main__ - INFO - [rr_bot.py:1290] - Stopped BotB
```

BotA remains and I am unable to shut it down unless I close the terminal tab.

### Additional information
Potential Causes

    Blocking Operation in start_polling:
        The start_polling method may be blocking or not yielding control back to the event loop, which would prevent it from responding to the CancelledError. This could cause one bot to shut down correctly while the other does not.

    Signal Handling:
        It's possible that the Dispatcher.start_polling is capturing the signal (like KeyboardInterrupt) and handling it internally, which might lead to only one bot being able to process the signal correctly.

    Event Loop Deadlock or Blocking:
        If start_polling is holding onto resources or is in a long-running operation that doesn't check for cancellation, it can prevent the bot from properly exiting when a shutdown signal is received.

Any help is welcome.

**Comment by 0xlucyy** [comment]
the issue likely lies with how `aiogram` manages the event loop when running multiple bots. The root problem is that aiogram's start_polling method isn't playing well with the concurrent execution of multiple tasks.

**Comment by JrooTJunior** [comment]
This situation is caused by your using the dispatcher incorrectly, only one signal handler can be registered per Python process, so when you start multiple polling processes, the second task overrides the SIGINT/SIGTERM handlers that are registered at the start of the poll.

https://github.com/aiogram/aiogram/blob/f10414c1ebdb357808e74b01a6a0a2e2c8607de6/aiogram/dispatcher/dispatcher.py#L510-L515

---

aiogram supports "multibots" out of the box, so you should use this option to run multiple bot instances with the same set of handlers registered in the dispatcher.

You can specify as many bots as you need in the start_polling/run_polling method:
```python
await bot.start_polling(bot1, bot2, ... botN)
```

On the other hand, if you need to run bots with different sets of handlers, you should separate them into different programs and run them separately.

---

You can use the same client session for all bots

```python
session = AiohttpSession()
default = DefaultBotProperties(parse_mode=ParseMode.HTML)

bot1 = Bot(token1, session=session, default=default)
bot2 = Bot(token2, session=session, default=default)
...
```

---

If you want to use the same FSM store for all bots, you need to configure the store key factory to pass the bot ID in the key to separate states for one user in each bot.

```python
shared_storage = RedisStorage.from_url('redis://localhost:6379/5', key_builder=DefaultKeyBuilder(with_bot_id=True))
```

---

You don't need to close the dispatcher and client session manually because the Dispatcher does this by default.

https://github.com/aiogram/aiogram/blob/f10414c1ebdb357808e74b01a6a0a2e2c8607de6/aiogram/dispatcher/dispatcher.py#L555-L559

https://github.com/aiogram/aiogram/blob/f10414c1ebdb357808e74b01a6a0a2e2c8607de6/aiogram/dispatcher/dispatcher.py#L92

---

So if you put it all together:

```python
import asyncio
import logging
from os import getenv

from aiogram import Dispatcher, Bot
from aiogram.client.session.aiohttp import AiohttpSession
from aiogram.fsm.storage.base import DefaultKeyBuilder
from aiogram.fsm.storage.redis import RedisStorage

BOT_A_TOKEN = getenv("TOKEN_A")
BOT_B_TOKEN = getenv("TOKEN_B")

logger = logging.getLogger(__name__)


def create_dispatcher() -> Dispatcher:
    shared_storage = RedisStorage.from_url(
        "redis://localhost:6379/5",
        key_builder=DefaultKeyBuilder(with_bot_id=True),
    )
    dispatcher = Dispatcher(storage=shared_storage)

    # dispatcher.include_routers(
    #     ...
    # )

    return dispatcher


async def main():
    logger.info("Started")
    dispatcher = create_dispatcher()
    session = AiohttpSession()

    bot_a = Bot(BOT_A_TOKEN, session=session)
    bot_b = Bot(BOT_B_TOKEN, session=session)

    await dispatcher.start_polling(bot_a, bot_b)


if __name__ == "__main__":
    asyncio.run(main())
```

**Comment by JrooTJunior** [comment]
Note that you will need to use webhook mode to make  efficient usage of the resources

Conditionally, the situation is as follows:
- usage in polling mode = bot polling processes count * events intensity per bot
- usage in webhook mode = events intensity

So the use with a webhook depends only on the intensity of incoming events and not on the number of bots multiplied by the intensity of events, and also the webhook allows you to easily scale the process horizontally and distribute the load.
