### ISSUE TITLE
Telegram aiogram poll_answer.option_ids problem

### ISSUE THREAD

**Issue by kolosok9966** [aiogram/aiogram#1573]
### Checklist

- [ ] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11

### Python version

3.12.5

### aiogram version

3.12.0

### Expected behavior

the bot from Telegram Desktop should recieve poll_answer.option_ids: [1]
the bot from Telegram Web should recieve poll_answer.option_ids: [1]

### Current behavior

the bot from Telegram Desktop recieved poll_answer.option_ids: [1]
the bot from Telegram Web recieved poll_answer.option_ids: [1,1]

https://github.com/user-attachments/assets/1e636e6c-121e-4990-b052-2c4f18d1e258

### Steps to reproduce

Choose second answer in poll

### Code example

```python3
async def handler_poll_answer(bot, poll_answer: PollAnswer, state: FSMContext):
    state_data = await state.get_data()
    chat_id = poll_answer.user.id
    exam = state_data.get("exam")

    print(f"poll_answer.option_ids:{poll_answer.option_ids}")
    print(f"correct_ids:{state_data.get("correct_option_indices")}")
    
    if poll_answer.option_ids == state_data.get("correct_option_indices"):
        await bot.send_message(chat_id=chat_id, text="Ответ верный! ✅")
        if exam:
            current_score = state_data.get("score", 0)
            await state.update_data(score=current_score + 1)
    else:
        await bot.send_message(chat_id=chat_id, text="Ответ неверный! ❌")
    
    await delete_question_message(bot,chat_id,state)
    
    if exam:
        questions_count = state_data.get("questions_count", 0)
        await state.update_data(questions_count=questions_count + 1)
        await exam_send_question(bot,chat_id, state)
    else:
        await send_question(bot, chat_id, state)
```

### Logs

```sh
None
```

### Additional information

https://stackoverflow.com/staging-ground/78947713

**Comment by Olegt0rr** [comment]
Look like Telegram Web bug, not aiogram
