### ISSUE TITLE
pydantic error Default

### ISSUE THREAD

**Issue by rudyvan** [aiogram/aiogram#1579]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

mac os

### Python version

3.11

### aiogram version

3.0

### Expected behavior

After installing latest aiogram version, when running a bot instance:

```
self.bot = Bot(token=self.token, default=DefaultBotProperties(parse_mode=ParseMode.HTML))
```

got pydantic error:

<img width="1003" alt="image" src="https://github.com/user-attachments/assets/ceea3881-a01c-46b3-b375-6f395c8c18c2">

has to do with the fact that Default is generates an error in pydantic validation.

<img width="1111" alt="image" src="https://github.com/user-attachments/assets/053884d2-ba2e-4d2f-9b53-73f64f806456">

Fact is that Default is not a dataclass and not an element of the pydantic BaseModel.

I reverted to aiogram version 3.12.0 where this error doesn't happen.

Thanks for solving this in the next release.

### Current behavior

pydantic returns error and aiogram stops the program

### Steps to reproduce

install aiogram version 3.12.0

run example script --> no error

install latest aiogram version 3.13.0

pydantic error on Default

**Comment by JrooTJunior** [comment]
I ran into the same problem a few days ago, it seems something changed in the latest `pydantic` version that is breaking it.

A fix will be published as soon as possible.
