### ISSUE TITLE
i18n Middleware defaults to "ru" locale instead of configured default_locale ("unknown"/"en")

### ISSUE THREAD

**Issue by 00021943** [aiogram/aiogram#1590]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11

### Python version

3.12.3

### aiogram version

3.13.1

### Expected behavior

The locale should be set to the default locale specified in the configuration, either "unknown" or "en", and it should not default to "ru" unless explicitly set by the user.

### Current behavior

Despite setting the default_locale to "unknown" or "en", the locale always defaults to "ru" when using the /start command. The value printed by `state_data.get("locale")` is consistently "ru" instead of the expected locale.

### Steps to reproduce

1. Set up the i18n configuration as described.
2. Register the middleware and set the default_locale to "unknown" or "en".
3. Use the /start command.
4. Check the output of `state_data.get("locale")`, which always shows "ru".

### Code example

```python3
# main.py
i18n = I18n(path="locales", default_locale="unknown", domain="messages")
i18n_middleware = FSMI18nMiddleware(i18n)
dp.message.middleware.register(i18n_middleware)
dp.callback_query.middleware.register(i18n_middleware)

# router start.py
@router.message()
async def start(
    message: Message,
    state: FSMContext
) -> None:
    state_data = await state.get_data()
    print(state_data.get("locale"))
```

### Logs

```sh
INFO:aiogram.dispatcher:Start polling
INFO:aiogram.dispatcher:Run polling for bot @image_generating_bot id=... - '...'
ru <---- output
```

### Additional information

This issue occurs consistently across all messages and callbacks using the i18n middleware. I have checked the locale settings and ensured that the configuration points to the correct paths. The expected behavior is that the locale should default to either "unknown" or "en", depending on the setup.

**Comment by OzodbekUSTECH** [comment]
I noticed something else:

When I create the "ru" folder in main_dir/locales using the following command:

```python
pybabel init -i locales/messages.pot -d locales -D messages -l ru
```
the default locale always switches to "ru", even if I set a different default_locale (e.g., "unknown" or "en") in the i18n configuration.

However, if I don't create the "ru" folder in locales, the default locale remains as whatever I set when initializing the i18n instance.

What could be causing this behavior? Why does creating the "ru" language folder force the default locale to "ru", even if a different default_locale is specified?
