### ISSUE TITLE
TokenBasedRequestHandler should support secret_token

### ISSUE THREAD

**Issue by drizzt** [aiogram/aiogram#1613]
### aiogram version

3.x

### Problem

TokenBasedRequestHandler currently doesn't support secret_token, but it should since it's straightforward to add it

### Possible solution

As "workaround" I just added support in a child class

```
class PatchedTokenBasedRequestHandler(TokenBasedRequestHandler):
    """
    Just a TokenBasedRequestHandler with added support for secret_token
    """

    def __init__(
        self,
        dispatcher: Dispatcher,
        handle_in_background: bool = True,
        bot_settings: dict[str, Any] | None = None,
        secret_token: str | None = None,
        **data: Any,
    ) -> None:
        super().__init__(
            dispatcher=dispatcher,
            handle_in_background=handle_in_background,
            bot_settings=bot_settings,
            **data,
        )
        self.secret_token = secret_token

    def verify_secret(self, telegram_secret_token: str, bot: Bot) -> bool:
        if self.secret_token:
            return secrets.compare_digest(telegram_secret_token, self.secret_token)
        return True
```

**Comment by JrooTJunior** [comment]
The described problem should be solved in the way you described in the "Possible solution" section, there are many different ways from where and how to check the secret token, so the most universal way is added to the framework - the ability to define your own key verification method with all the necessary parameters for this.

So I don't see a good reason to change the code for this request.

**Comment by Olegt0rr** [comment]
> The described problem should be solved in the way you described in the "Possible solution" section, there are many different ways from where and how to check the secret token, so the most universal way is added to the framework - the ability to define your own key verification method with all the necessary parameters for this.
> 
> So I don't see a good reason to change the code for this request.

@JrooTJunior ,
How about to reopen this issue for docs?
We can add your explaination and alse add provided workaround as an example
