### ISSUE TITLE
Rename chat and user arguments to chat_id and user_id

### ISSUE THREAD

**Issue by JrooTJunior** [aiogram/aiogram#174]
After discussion in [aiogram_ru#80199](https://t.me/aiogram_ru/80199) and #172 is planned to rename all `chat` and `user` arguments to `chat_id` and `user_id` and marking old arguments as deprecated until 3.0.

Affected:

1. https://github.com/aiogram/aiogram/blob/c6923e331c1222b275aa87ce87ffabf17b185890/aiogram/dispatcher/dispatcher.py#L860-L862
2. https://github.com/aiogram/aiogram/blob/c6923e331c1222b275aa87ce87ffabf17b185890/aiogram/dispatcher/dispatcher.py#L887
3. https://github.com/aiogram/aiogram/blob/c6923e331c1222b275aa87ce87ffabf17b185890/aiogram/dispatcher/dispatcher.py#L964

**Comment by Birdi7** [comment]
The number of affected lines can be more, it's necessary to check all other files, too

**Comment by Birdi7** [comment]
Additional affected lines, in [storage.py](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/dispatcher/storage.py):

https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L41-L43
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L63-L66
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L80-L83
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L97-L100
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L113-L116
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L129-L133
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L150-L152
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L165-L168
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L186-L188
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L204-L207
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L221-L224
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L237-L241
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L258-L260
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L275-L277
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L295
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L298
https://github.com/aiogram/aiogram/blob/01f075d905798c8dde04e9ba86a9bb6917ba9e9a/aiogram/dispatcher/storage.py#L301

**Comment by Birdi7** [comment]
Example of implementing this issue might be found [here](https://github.com/aiogram/aiogram/blob/81b36bd19249dbb0d4eb8a0df8e7d5fb0ad16ae4/aiogram/dispatcher/dispatcher.py#L1034). The task is to use the same approach to all other places with the usage of `user` and `chat` as arguments instead of `user_id` and `chat_id`

**Comment by Birdi7** [comment]
@JrooTJunior might be a good idea to use `chat_id` and `user_id` argument naming in `3.0` version from scratch, to avoid occurrence of this issue

**Comment by JrooTJunior** [comment]
Yep

**Comment by tohabyuraev** [comment]
Hello @Birdi7 , @JrooTJunior . I want to help **aiogram** and try to solve all or part of this issue.

First of all, dispatcher.py and storage.py are not the only ones where `chat` and `user` can be found. So, i need to start replace from this ones and after that try to find in other modules? What do i need to do for effective search?

**Comment by Birdi7** [comment]
Hi @tohabyuraev. Thank you for your interest!

This issue affects all the modules in the framework, including `dispatcher.py` and `storage.py`. I am not sure whether there is an effective technique to search, because we need to rename all usages in every module.

I would recommend to do refactoring step by step: that's not a task which is easy to be done in an evening. Consider opening a draft PR - this way you'll get the feedback ASAP. Feel free to ping me for any further questions!

**Comment by JrooTJunior** [comment]
Fixed in v3
