### ISSUE TITLE
can not send multiple request to aiogram

### ISSUE THREAD

**Issue by hamedhjz** [aiogram/aiogram#184]
## Context
i tried both aiohttp and run directly by python3

* Operating System: debian 10
* Python Version: 3.7.3
* aiogram version: lastest
* aiohttp version: lastest
* uvloop version (if installed): 0.12.2

## Expected Behavior
i want to download multiple files and requests to bot by many of clients at same time

## Current Behavior
waiting to donwload video from youtube using youtube-dl module
and until finnishing this session i can not receive the next file download request same time

## Failure Information (for bugs)
none

**Comment by Birdi7** [comment]
Could you provide an example of your code? 
I think your behavior happens because you use the youtube-dl module without running it in an executor and as a result, it blocks the event loop

**Comment by hamedhjz** [comment]
`from __future__ import unicode_literals

import asyncio
from aiogram import Bot, Dispatcher, types
from aiogram.utils.executor import start_webhook
from aiogram.contrib.fsm_storage.memory import MemoryStorage

import re 
import logging
import youtube_dl
import os
import math


WEBHOOK_HOST = '####'
WEBHOOK_PATH = '###'
WEBHOOK_URL = f"{WEBHOOK_HOST}{WEBHOOK_PATH}"


WEBAPP_HOST = '###'  # or ip
WEBAPP_PORT = ###

def convert_size(size_bytes):
   if size_bytes == 0:
       return "0B"
   size_name = ("B", "KB", "MB", "GB", "TB", "PB", "EB", "ZB", "YB")
   i = int(math.floor(math.log(size_bytes, 1024)))
   p = math.pow(1024, i)
   s = round(size_bytes / p, 2)
   return "%s %s" % (s, size_name[i])

class MyLogger(object):
    def debug(self, msg):
        pass

    def warning(self, msg):
        pass

    def error(self, msg):
        print(msg)

        
API_TOKEN = '######'

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)

bot = Bot(token=API_TOKEN, connections_limit=100)
storage = MemoryStorage()
dp = Dispatcher(bot, storage=storage)

def youtube_url_validation(url):
    youtube_regex = (r'(https?://)?(www\.)?'
        '(youtube|youtu|youtube-nocookie)\.(com|be)/'
        '(watch\?v=|embed/|v/|.+\?v=)?([^&=%\?]{11})')

    youtube_regex_match = re.match(youtube_regex, url)
    if youtube_regex_match:
        return youtube_regex_match

    return youtube_regex_match

async def on_startup(dp):
    webhook = await bot.get_webhook_info()
    if webhook.url != WEBHOOK_URL:
        if not webhook.url:
            await bot.delete_webhook()
        await bot.set_webhook(WEBHOOK_URL)

async def on_shutdown(dp):
    await bot.delete_webhook()
    await dp.storage.close()
    await dp.storage.wait_closed()
    
    
    
@dp.message_handler(commands=['start', 'help'])
async def send_welcome(message: types.Message):
    await bot.send_chat_action(message.chat.id, "typing")
    await message.reply("Enter Youtube url below:")

@dp.message_handler()
async def echo(message: types.Message):
    await bot.send_chat_action(message.chat.id, "typing")
    if youtube_url_validation(message.text):
        
        with youtube_dl.YoutubeDL() as ydl:  
        
            keyboard_markup = types.InlineKeyboardMarkup(row_width=2)
            
            info_dict = ydl.extract_info(message.text, download=False)
            
            vformats = info_dict['formats']
            vtitle = info_dict['title']
            display_id = info_dict['display_id']
#            formatslen = len(vformats)

            for vformat in vformats:
                format_note = vformat['format_note']
                filesize = vformat['filesize']
                ext = vformat['ext']
                format_id = vformat['format_id']  
                tbr = "%s"%vformat['tbr']
                vname = re.sub(r'DASH audio', r'mp3', format_note)
                
                if vname in 'mp3':
                    vname = 'mp3 - ' + tbr.split('.')[0] + 'k'
                    af = 'm'
                else:
                    vname = vname + ' - ' + ext
                    af = 'v'
                keyboard_markup.insert(types.InlineKeyboardButton(vname, callback_data=('fid*' + format_id + '*' + display_id + '*' + tbr + '*' + af)))    

            await bot.send_message(message.chat.id, "choose your format:", reply_markup=keyboard_markup)
        
        
    else:
        await bot.send_message(message.chat.id, 'use /help')    
        
@dp.callback_query_handler(lambda cb: 'fid' in cb.data)        
async def inline_kb_answer_callback_handler(query: types.CallbackQuery):

    await query.answer()
    answer_data = query.data
    logger.debug(f"answer_data in {answer_data}")
    split_answer_data = answer_data.split('*')
    if 'fid' == split_answer_data[0]:
    
        await bot.edit_message_text("Downloading to server", query.message.chat.id, query.message.message_id)
        
        def my_hook(d):
            global filename
            if d['status'] == 'finished':
                file_tuple = os.path.split(os.path.abspath(d['filename']))
                print("Done downloading {}".format(file_tuple[1]))
                filename = d['filename']
                
        if not os.path.exists(str(query.from_user.id)):
            os.makedirs(str(query.from_user.id))
            
        ydl_opts = {
            'outtmpl': str(query.from_user.id) + '/%(title)s.%(ext)s',
            'format': str(split_answer_data[1]),
            'postprocessors': [{
                'key': 'FFmpegExtractAudio',
                'preferredcodec': 'mp3',
                'preferredquality': split_answer_data[3].split('.')[0],
            }],
            #'forcefilename': True,
            'logger': MyLogger(),
            'progress_hooks': [my_hook],
        }
        
        with youtube_dl.YoutubeDL(ydl_opts) as ydl:
            ydl.download(['https://www.youtube.com/watch?v=' + split_answer_data[2]])
        
        await bot.edit_message_text("now sending to your telegram", query.message.chat.id, query.message.message_id)
    
    else:
        await bot.send_message(query.from_user.id, "Invalid callback data!")

        
if __name__ == '__main__':
#    executor.start_polling(dp, skip_updates=True)
        start_webhook(dispatcher=dp, webhook_path=WEBHOOK_PATH, on_startup=on_startup, on_shutdown=on_shutdown,
                    skip_updates=True, host=WEBAPP_HOST, port=WEBAPP_PORT)`

**Comment by Birdi7** [comment]
Use pastebin.com please

**Comment by Birdi7** [comment]
Use pastebin.com please

**Comment by hamedhjz** [comment]
https://codeshare.io/2El6yp

**Comment by JrooTJunior** [comment]
All synchronous IO operations will blocks asyncio event loop.
`youtube-dl` doesn't have asyncio implementation and in this behavior you can't use `youtube-dl` in asynchronous code as is in synchronous. You need to pass IO operations to executor.

For example:
```python3
def download_video(url: str) -> io.BytesIO:
    video = ...  # Download video by youtube-dl
    return video

@dp.message_handler(commands=["youtube"])
async def cmd_youtube(message: types.Message):
    url = ...  # parse URL here
    video = await loop.run_in_executor(None, functools.partial(download_video, url))

```

**Comment by hamedhjz** [comment]
> All synchronous IO operations will blocks asyncio event loop.
> `youtube-dl` doesn't have asyncio implementation and in this behavior you can't use `youtube-dl` in asynchronous code as is in synchronous. You need to pass IO operations to executor.
> 
> For example:
> 
> ```python
> def download_video(url: str) -> io.BytesIO:
>     video = ...  # Download video by youtube-dl
>     return video
> 
> @dp.message_handler(commands=["youtube"])
> async def cmd_youtube(message: types.Message):
>     url = ...  # parse URL here
>     video = await loop.run_in_executor(None, functools.partial(download_video, url))
> ```

thanks ❤❤❤

**Comment by JrooTJunior** [comment]
> https://codeshare.io/2El6yp

In github external sites for publishing the code is not needed. You can simply put youre code-snippet to the triple backqoutes with specifying the programming language.

For example text:
~~~
```python3
async def foo(bar: baz) -> qux:
    return bat
```
~~~

will be represented as:
```python3
async def foo(bar: baz) -> qux:
    return bat
```
