### ISSUE TITLE
ImportError: cannot import name 'executer' from 'aiogram'

### ISSUE THREAD

**Issue by RecNes** [aiogram/aiogram#193]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Linux Mint 19.1 
* Python Version: 3.7.3
* aiogram version: 2.3
* aiohttp version: 3.5.4
* uvloop version (if installed): 0.13.0

## Expected Behavior

Should expected to import necessary library 

## Current Behavior

from aiogram import Bot, Dispatcher, executer, types
ImportError: cannot import name 'executer' from 'aiogram'

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Open a python shell
2. execute "from aiogram import executer"

**Comment by JrooTJunior** [comment]
This problem is related with typo in you'r code-snippet.

Use `executor` instead of `executEr`.

**Comment by RecNes** [comment]
Sorry my bad.
