### ISSUE TITLE
Handle ForceReply user replies

### ISSUE THREAD

**Issue by David-Lor** [aiogram/aiogram#194]
I was wondering how aiogram's ForceReply can be used, mainly how to handle messages sent by the user as reply to a message sent by the bot with a ForceReply markup.

This is what I done so far:

1.-Create a ForceReply instance:
```python
RenameStopForceReply = ForceReply()
```
I don't really know what parameters can be set on the constructor.

2.-Send a message with this ForceReply instance as the reply_markup:
```python
await callback_query.bot.send_message(
            chat_id=callback_query.message.chat.id,
            reply_markup=RenameStopForceReply.create(),
            text="Rename me!"
        )
```

This generates a ForceReply-like message on the Telegram client as expected:
![telegram client - forcereply](https://user-images.githubusercontent.com/17401854/63370184-f62f4000-c381-11e9-95c2-e6e8bfa3ec6e.png)

The problem is: How do I handle the messages the user send as reply to that "Rename me!" message? I can get them with a "global message handler" (the one which receives any text message), but I don't know how to get the ForceReply instance from it, if possible - or at least somehow identify if the message sent by the client is a reply to a ForceReply message (tried debugging the message but found nothing).

EDIT: As I see, ForceReply itself (according to Telegram Bot API) does not actually provide this feature; I was actually thinking about ForceReply being the equivalent to what is called "next step handler" on pyTelegramBotAPI (which I used in the past before switching to aiogram): https://github.com/eternnoir/pyTelegramBotAPI/blob/master/examples/step_example.py
I don't know if such a thing is implemented on aiogram.

Thanks in advance!

**Comment by uwinx** [comment]
@David-Lor FSM is what you need. ForceReply is just a type of markup for client applications

**Comment by David-Lor** [comment]
@uwinx for now I was storing the context of ForceReplies on a python dictionary - I guess it could be some sort of in-memory FSM?

**Comment by uwinx** [comment]
@David-lor you have to take a look at examples in aiogram/examples directory. There are different types of storages there.
