### ISSUE TITLE
Document that registering order of handlers matters

### ISSUE THREAD

**Issue by Gowee** [aiogram/aiogram#208]
## Problem
When going to catching deep links passed thru `/start` commands, I start with registering a message handler with something like: `@dispatcher.message_handler(CommandStart(re.compile(r"ACTION\_(?P<whisper_id>.+)")))`.
Then I find that the handler is not capturing any messages. Soon later I realize that there is a more generic handler registered:
`@dispatcher.message_handler(commands=["start"])`.

By looking through the source code roughly, I find [only one matched handler will be triggered per update/message](https://github.com/aiogram/aiogram/blob/bb117f83a579165c79b02ca21035533e6bbcab47/aiogram/dispatcher/handler.py#L121) unless [`raise SkipHandler`](https://github.com/aiogram/aiogram/blob/bb117f83a579165c79b02ca21035533e6bbcab47/aiogram/dispatcher/handler.py#L17). So based on the order in which handlers are registered, more generic handlers may suppress more specific handlers unexpectedly. AFAICS, the doc does not mention the precedence order problem at all.

## Solution
I think it is reasonable and necessary to document that:
- More generic handlers may suppress more specific handlers, based on the order in which handlers are registered.
- The existence of `SkipHandler`.

**Alternative Solution**
- Support explicit specification of precedence of handlers (seemingly unnecessary).

**Comment by uwinx** [comment]
Isn't it obvious?
The rule is "who's first", you register your callback for particular update first, and while dispatching updates each update goes one-by-one through your callbacks, checking their filter until it succeeds in filter checking. 
Correct me if something is missing or your case is different.

**Comment by uwinx** [comment]
@JrooTJunior, I think this is also can be closed.

**Comment by JrooTJunior** [comment]
@Gowee, did you get an answer to your problem?

**Comment by Gowee** [comment]
@JrooTJunior, @uwinx : 
Thanks for the reply. I have already solved my problems.

It is fine to close it.
