### ISSUE TITLE
Routers proposal

### ISSUE THREAD

**Issue by uwinx** [aiogram/aiogram#214]
## Problem

Currently in order to register handlers in project where you module-separated handlers you should play either with `importlib` or do unused `__import__` directly.
## Solution

I believe `Router` object (I haven't decided about name yet, maybe `BluePrint`) might be helpful.

Implementation example is [here](https://github.com/uwinx/pomegranate/tree/dev#-router-and-
migrating-to-garnet-using-router), even that implementation is still raw yet.

## Raw model

```
rtr = Router[aiogram.types.Message]
rtr.middleware(...)  # any callable here or maybe native aiogram callback

...

from .handlers import message_handlers

dp.register_router(message_handlers.rtr)
```

Let's discuss it here.

**Comment by JrooTJunior** [comment]
For 3.0 is planned nested dispatchers.

Something like:
``` python
root_dp = Dispatcher()

dp1 = Dispatcher()
dp2 = Dispatcher()
dp2_1 = Dispatcher()

root_dp.attach(dp1)
root_dp.attach(dp2)
dp2.attach(dp2_1)
```


If you can understand russian language you can found many parts of discussion about that in [aiogram \[ru\]](https://t.me/aiogram_ru) chat

**Comment by uwinx** [comment]
I think, it will bloat `Dispatcher` also `Router` doesn't require anything, whereas `Dispatcher` really depends on `Bot`.
