### ISSUE TITLE
 Wrong video note length

### ISSUE THREAD

**Issue by GetPHP-IR** [aiogram/aiogram#221]
## Context
* Operating System: Debian 10.1 (2019-09-20)
* Python Version: 3.7.3
* aiogram version: 2.3
* aiohttp version: 3.6.1
* uvloop version (if installed): 0.13

## Expected Behavior

Send video note with 1:01min length

## Current Behavior

 Wrong video note length
  
I can not forward video note with 1:01min length

**Comment by JrooTJunior** [comment]
Can you please attach to the issue an code example and file what you trying to forward via bot?

**Comment by JrooTJunior** [comment]
And how do you send video node longer than 60 seconds?
