### ISSUE TITLE
Нужна помощь python

### ISSUE THREAD

**Issue by slavich84** [aiogram/aiogram#224]
Подскажите как реализовать корзину для телеграм бота на python

**Comment by JrooTJunior** [comment]
Вы ошиблись местом где просить подобной помощи.

Для начала опишите более подробно что именно Вы хотите и как это должно выглядеть, далее найдите исполнителя для своей задачи, например используя канал [@tgram_jobs](https://t.me/tgram_jobs) разместив объявление через специального бота.

Я закрываю данный запрос потому что он не связан с фреймворком.
Спасибо за понимание.
