### ISSUE TITLE
Curl and Webhook

### ISSUE THREAD

**Issue by LuckyDenis** [aiogram/aiogram#225]
Good evening. You can run the bot in webhook mode on `localhost`. Logically, you can go to it with `uCurl`, passing the necessary parameters. The question is how to go to the bot using `uCurl`. It would have greatly facilitated testing at the level of the system.

**Comment by JrooTJunior** [comment]
`uCurl` is looks like something very specific. What is that? I don't see any related information about that.
Can you provide more information?

**Comment by LuckyDenis** [comment]
> `uCurl` is looks like something very specific. What is that? I don't see any related information about that.
> Can you provide more information?

I'm sorry. `Curl` or 'HttPie`.

**Comment by uwinx** [comment]
Could you please provide us with code? A webhook requires ssl/tls encryption, ALSO for testing your bots you can use tunnels to your localhost.
Another question is "why not polling"?

**Comment by evgfilim1** [comment]
Works for me

bot:
```python
from aiogram import Bot, Dispatcher
from aiogram.dispatcher.webhook import SendMessage

bot = Bot('token-goes-here')
dp = Dispatcher(bot)

@dp.message_handler(commands=['start'])
async def start(message):
    return SendMessage(text='Hello!').reply(message).to(message)

async def on_startup(d: Dispatcher):
    await d.bot.set_webhook(f'https://my-domain/something')  # Domain and path are handled by nginx

async def on_shutdown(d: Dispatcher):
    await d.bot.delete_webhook()

if __name__ == '__main__':
    executor.start_webhook(dp, '/', on_startup=on_startup, on_shutdown=on_shutdown, host='0.0.0.0',
                           port=3456)
```

console:
```bash
$ curl -X POST -H "Content-Type: application/json" -H "Cache-Control: no-cache" -d '{ "update_id":10000, "message":{ "date":1441645532, "chat":{ "last_name":"Test Lastname", "id":1111111, "first_name":"Test", "username":"Test" }, "message_id":1365, "from":{ "last_name":"Test Lastname", "id":1111111, "first_name":"Test", "username":"Test" }, "text":"/start" } }' "http://0.0.0.0:3456/"
{"method": "sendMessage", "chat_id": 1111111, "text": "Hello!", "reply_to_message_id": 1365}
```

@LuckyDenis if this issue is still relevant, could you provide us more information?

**Comment by evgfilim1** [comment]
@LuckyDenis ping
If the issue is still relevant, please provide us a code snippet where you face this behavior.

For devs: This issue will be considered stale and closed in a week if there won't be any reply.

**Comment by LuckyDenis** [comment]
The issue is resolved.
