### ISSUE TITLE
BytesIO is closed after reading by InputFile

### ISSUE THREAD

**Issue by vasya-polyansky** [aiogram/aiogram#227]
# In English

**Problem**
When you want to upload and to send the same file to multiple chats you want to make one `InputFile` with one `BytesIO` object and send it to chats, but after first iteration `BytesIO` will be closed and you will get `ValueError: I/O operation on closed file.`

**Solution**
Either need some way getting `InputFile` object through bytes type object which you will put in `InputFile`. Or `BytesIO` should not be closed after first iteration.

# На русском

**Проблема**
Когда вы пытаетесь загрузить и отправить один и тот же файл в несолько чатов вы хотите сделать один `InputFile` с одним `BytesIO` и отправить его в чаты, но после первой итерации `BytesIO` будет закрыт и вы получите ошибку `ValueError: I/O operation on closed file.`.

**Решение**
Нужен либо способ получения `InputFile` с помощью объекта класса `bytes` который вы передаете в `InputFile`. Либо `BytesIO` не должен закрываться после первой итерации.

`aiogram.types.input_file.InputFile`
![image](https://user-images.githubusercontent.com/45375305/68413592-fa604200-01a7-11ea-9b3a-3b098bcdddab.png)

**Comment by Olegt0rr** [comment]
We can every call use `self._file.seek(0)` within InputFile class
It should helps to avoid autoclosing with the end of the file

**Comment by JrooTJunior** [comment]
Fixed in v3
