### ISSUE TITLE
"Task exception was never retrieved" prints out when using an Error Handler

### ISSUE THREAD

**Issue by David-Lor** [aiogram/aiogram#228]
## Context

While using the aiogram Error Handler, the exception is correctly handled by it, but Python logs a warning: "Task exception was never retrieved".

## Expected Behavior

Suppress the "task exception was never retrieved" warning, since it's technically already handled by the Error Handler.

## Current Behavior

"Task exception was never retrieved" warning/error is printed by Python.

**Comment by JrooTJunior** [comment]
Can you provide codesnippet where this error can be reproduced?

**Comment by David-Lor** [comment]
Here I uploaded a sample code where this problem is reproduced: https://github.com/David-Lor/aiogram-error-handler-snippet

**Comment by Olegt0rr** [comment]
Reproduced.

Seems aiogram catches the same error:
https://github.com/pytest-dev/pytest-asyncio/issues/32

**Comment by evgfilim1** [comment]
Just `return True` in your exception handler
[Source](https://github.com/aiogram/aiogram/blob/7afe783914bee69df07a9cfef463248c61901ecd/aiogram/dispatcher/dispatcher.py#L229-L233)
[Example](https://github.com/aiogram/aiogram/blob/7afe783914bee69df07a9cfef463248c61901ecd/examples/callback_data_factory.py#L113-L115) (doesn't show a "Task exception was never retrieved" message)

@JrooTJunior I think we need to document this behaviour

**Comment by David-Lor** [comment]
Confirming it works returning True. I don't know if you want to keep this issue opened to document/change the behaviour as @evgfilim1 described.

**Comment by evgfilim1** [comment]
I've made another issue for this.
