### ISSUE TITLE
Invalid link in examples/i18n_example.py

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#236]
## Context

https://github.com/aiogram/aiogram/blob/56662d6bd8052ee835fcfebd928c8a2786fe922c/examples/i18n_example.py#L66

## Expected Behavior

I can open link.

## Current Behavior

I cannot open link. GitHub returns 404.

**Comment by JrooTJunior** [comment]
Thanks for reminder

Repository with Events TrackerBot is hidden from public access (the project was frozen)

**Comment by JrooTJunior** [comment]
Fixed
