### ISSUE TITLE
Don't mutate TelegramObject in to_* as_*

### ISSUE THREAD

**Issue by uwinx** [aiogram/aiogram#247]
## Context

* aiogram version: 2.4

## Expected Behavior

`to_python` should return dictionary representation of API object. Without mutating it.

## Current Behavior

It mutates it to `dict` and also return it. Which unexpected behaviour. It should either mutate it and return nothing or just return result without mutating. Problem with `as_json` is the same, since it calls `to_python underneath`

Maybe I don't get it and it's super obvious behaviour.

**Comment by JrooTJunior** [comment]
I think has no sense change this behavior until 3.0. 
In 3.0 already used `pydantic` for data (de)serialization.

**Comment by JrooTJunior** [comment]
Fixed in `dev-2.x` branch. Need to be tested.
