### ISSUE TITLE
HTML entities missing

### ISSUE THREAD

**Issue by lyteloli** [aiogram/aiogram#249]
Today Telegram Bot API was updated and now bots can parse nested html, and also use strikethrough and underlined text. But aiogram doesn't parse necessary message entities using message.html_text, you should fix it. I am using the latest aiogram, 2.4 I guess.

**Comment by prostomarkeloff** [comment]
https://t.me/aiogram_live/46

**Comment by JrooTJunior** [comment]
Yep. I know it! And waiting this update long time.
New nested entities mechanism is already implemented with all other features and be released to the PyPi today. Thanks for the issue :+1:

**Comment by JrooTJunior** [comment]
Related with #250 #251

**Comment by JrooTJunior** [comment]
Ready for release (final preparations)

**Comment by lyteloli** [comment]
![8AB88963-30A4-480E-B7C4-C43773DC0EDF](https://user-images.githubusercontent.com/41185217/71645260-48904e00-2cde-11ea-8ce9-6b329ef8eafd.jpeg)
How about this?

**Comment by JrooTJunior** [comment]
Do you use aiogram 2.5-2.5.1?

**Comment by JrooTJunior** [comment]
Nested entities works only with aiogram 2.5+

**Comment by lyteloli** [comment]
> Do you use aiogram 2.5-2.5.1?
> Nested entities works only with aiogram 2.5+

Yep, I do, as you see there’s bold link but multiple nesting doesn’t work

**Comment by lyteloli** [comment]
> 
> 
> Do you use aiogram 2.5-2.5.1?
> Nested entities works only with aiogram 2.5+

using the latest hotfix 2.5.2 changed nothing.
![image](https://user-images.githubusercontent.com/41185217/71645751-93619400-2ce5-11ea-8333-f8e98c306b2a.png)

**Comment by JrooTJunior** [comment]
Can you show your code?

**Comment by JrooTJunior** [comment]
```python3
bot = Bot(TOKEN, parse_mode=types.ParseMode.HTML)
dp = Dispatcher(bot)

@dp.message_handler()
async def from_user_handler(message: types.Message):
    await message.answer(f"Text: {message.html_text}")
```
![image](https://user-images.githubusercontent.com/6726423/71646250-e63f4980-2ced-11ea-9055-bcb514724053.png)

**Comment by lyteloli** [comment]
> 
> 
> Can you show your code?

It's just a simple echo just as yours but you send all the entities separately, try nesting them using mobile telegram as in my screenshot (I use IOS)

**Comment by lyteloli** [comment]
![image](https://user-images.githubusercontent.com/41185217/71646323-57cbc780-2cef-11ea-9485-2fccc69ca03a.png)


> 
> 
> Can you show your code?

for example here is bold underlined link

**Comment by JrooTJunior** [comment]
At screenshot i shown words with combining bold, italic and underlined text at the same time. It works as well.

**Comment by lyteloli** [comment]
> At screenshot i shown words with combining bold, italic and underlined text at the same time. It works as well.

Maybe you combined just two styles, try making one word a bold italic hyperlink

**Comment by JrooTJunior** [comment]
Nope. This case was covered by tests: https://github.com/aiogram/aiogram/blob/dev-3.x/tests/test_utils/test_text_decorations.py#L154-L162

Can you join to community chat [@aiogram_ru](https://t.me/aiogram_ru) and explain this situation in details?
