### ISSUE TITLE
Does aiogram also support the telegram client api?

### ISSUE THREAD

**Issue by elmcrest** [aiogram/aiogram#25]
differences would be that the bot would act on my behalf and not as a dedicated bot.

**Comment by JrooTJunior** [comment]
Aiogram maked only for Bot API and not intended for the client API. But I have another project planned - MTProto client for Telegram and with asyncio. But this will not be done soon.

**Comment by JrooTJunior** [comment]
@elmcrest, i think I can close the issue. You can reopen the issue if you have more questions ;)
Or you can ask in the [English](https://t.me/aiogram) or [Russian](https://t.me/aiogram_ru) communities in Telegram
