### ISSUE TITLE
Handler doesn't handle Venue Messages

### ISSUE THREAD

**Issue by soermejo** [aiogram/aiogram#26]
```
@dp.message_handler(content_types=types.ContentType.VENUE)
async def func(message):
    print(message)
```
i tried this code, and it doesent handler Venue messages

if i use a filter on any types like
`@dp.message_handler(content_types=types.ContentType.ANY)` 
This handle Venue in addition to others

**Comment by JrooTJunior** [comment]
Fixed in latest version: https://github.com/aiogram/aiogram/releases/tag/v1.2.1
You can install new version from pypi: `pip install aiogram -U`
