### ISSUE TITLE
Incorrect aiohttp-socks version in requirements

### ISSUE THREAD

**Issue by maximskripnik** [aiogram/aiogram#262]
## Context

* Operating System: mac os 10.15.2
* Python Version: 3.8.0
* aiogram version: 2.5.3
* aiohttp version: 3.6.2

## Expected Behavior

`pip install 'aiogram[proxy]'` works

## Current Behavior

```zsh
pip install 'aiogram[proxy]'
Collecting aiogram[proxy]
  Using cached https://files.pythonhosted.org/packages/e0/bc/0a5ff3e09cb90330ef99e58b585ccc64d3e1efbf452aea5c3c5846b04fe9/aiogram-2.5.3-py3-none-any.whl
Collecting aiohttp<4.0.0,>=3.5.4 (from aiogram[proxy])
  Using cached https://files.pythonhosted.org/packages/c2/f7/f0ad3dbace4762fef5d80aa4124b41bf218e4c4dd6d387a86cede707d9a4/aiohttp-3.6.2-py3-none-any.whl
Collecting certifi>=2019.3.9 (from aiogram[proxy])
  Using cached https://files.pythonhosted.org/packages/b9/63/df50cac98ea0d5b006c55a399c3bf1db9da7b5a24de7890bc9cfd5dd9e99/certifi-2019.11.28-py2.py3-none-any.whl
Collecting Babel>=2.6.0 (from aiogram[proxy])
  Using cached https://files.pythonhosted.org/packages/15/a1/522dccd23e5d2e47aed4b6a16795b8213e3272c7506e625f2425ad025a19/Babel-2.8.0-py2.py3-none-any.whl
Collecting aiohttp-socks<4.0.0,>=3.3; extra == "proxy" (from aiogram[proxy])
  ERROR: Could not find a version that satisfies the requirement aiohttp-socks<4.0.0,>=3.3; extra == "proxy" (from aiogram[proxy]) (from versions: 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2, 0.2.1, 0.2.2, 0.3.1, 0.3.2, 0.3.3, 0.3.4)
ERROR: No matching distribution found for aiohttp-socks<4.0.0,>=3.3; extra == "proxy" (from aiogram[proxy])
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. python3 -m venv .env 
2. source .env/bin/activate
3. pip install 'aiogram[proxy]'

## Comments

Seems that `setup.py` has wrong version for aiohttp-socks dependency in its extra requirements for proxy: https://github.com/aiogram/aiogram/blob/dev-2.x/setup.py#L69. There is no a single version in pypi for this dependency which would satisfy the requirement, hence the error: https://pypi.org/project/aiohttp-socks/

I am guessing that it was expected that aiohttp-socks follows the same version scheme as aiohttp, but there is no even release with major 1 yet. If not, it is not clear where a user should get such dependency versions. Could be just a typo/copypaste issue though

**Comment by JrooTJunior** [comment]
FIxed in `dev-2.x` branch. Will be released today.
