### ISSUE TITLE
Message.get_args does not take into account custom prefixes.

### ISSUE THREAD

**Issue by gabbhack** [aiogram/aiogram#269]
## Context

```python
@dp.message_handler(commands_prefix="!/")
async def test(message):
    message.get_args()  # None
```

Source: https://t.me/aiogram_ru/151739

**Comment by evgfilim1** [comment]
**Message for newcomers**
Possible workaround is here: https://github.com/aiogram/aiogram/issues/574#issuecomment-829341240

**Comment by evgfilim1** [comment]
It's hard to fix this in a convenient way, so use `command` arg inside handler (see my comment above)
