### ISSUE TITLE
Add a separate exception when poll is requested in group chat

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#270]
**Is your feature request related to a problem? Please describe.**
Write a `/start` handler which creates a keyboard with `KeyboardButtonPollType` button and sends it.
Try adding bot to a group and press `/start`
Result: `aiogram.utils.exceptions.BadRequest: Poll can be requested in private chats only`

**Describe the solution you'd like**
Since there are a lot of custom (?) [exceptions](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/utils/exceptions.py) supported in aiogram, I guess there is a place for another one, like **PollRequestError** or like that.

**Comment by JrooTJunior** [comment]
Fixed in `dev-2.x`. Will be released soon
