### ISSUE TITLE
An error occurs when sending an emoticon 'keycap_asterisk'.

### ISSUE THREAD

**Issue by LuckyDenis** [aiogram/aiogram#274]
## Context

* Operating System: ubuntu 19.10
* Python Version: 3.7
* aiogram version: 2.6.1
* aiohttp version: 3.6.2
* uvloop version (if installed): 0.14.0

## Expected Behavior

So that the message is processed normally when it is sent.

## Current Behavior

An error occurs when sending an emoticon.

## Failure Information (for bugs)
```python3
@dp.message_handler(commands=['foo'])
async def foo(message):
    text = emojize(':keycap_asterisk:')
    await bot.send_message(
        message.chat.id,
        text,
        parse_mode=ParseMode.MARKDOWN_V2
    )
```

error: `aiogram.utils.exceptions.CantParseEntities: Can't parse entities: can't find end of bold entity at byte offset 0`

**Comment by JrooTJunior** [comment]
This emoji has 2 symbols: * and ⃣

The symbol * in Markdown V2 should be quoted by back-slash.
That's mean you need to use `escape_md(text)` before send this message. (`from aiogram.utils.markdown import escape_md`)

**Comment by LuckyDenis** [comment]
Yes, that solved the problem. Thank you) Is this reflected in the documentation somewhere?)

**Comment by JrooTJunior** [comment]
>  Is this reflected in the documentation somewhere?)

This case is described in official [Telegram Bot API ductmentatioins](https://core.telegram.org/bots/api#markdownv2-style).

```
...
- In all other places characters '_‘, ’*‘, ’[‘, ’]‘, ’(‘, ’)‘, ’~‘, ’`‘, ’>‘, ’#‘, ’+‘, ’-‘, ’=‘, ’|‘, ’{‘, ’}‘, ’.‘, ’!‘ must be escaped with the preceding character ’\'.
...
```
