### ISSUE TITLE
User.get_mention and Chat.get_mention are different

### ISSUE THREAD

**Issue by gabbhack** [aiogram/aiogram#277]
## Context

* aiogram version: 2.6.1

## Current Behavior

[Chat.get_mention](https://github.com/aiogram/aiogram/blob/3355c64b64bc25ebeca734f90452111477dca689/aiogram/types/chat.py#L67) and [User.get_mention](https://github.com/aiogram/aiogram/blob/20ba5faf5c1d09daff99bd42f393ff15a7f4c677/aiogram/types/user.py#L70) are different

**Comment by JrooTJunior** [comment]
I think this function should be moved to utils package and then re-used inside this methods.
