### ISSUE TITLE
Add httpx as alternative client instead of aiohttp-client

### ISSUE THREAD

**Issue by b0g3r** [aiogram/aiogram#279]

**Comment by JrooTJunior** [comment]
Add an alternative client and not a replacement

**Comment by Olegt0rr** [comment]
FYI

https://gist.github.com/florimondmanca/fbc85b58e9ce61e74b73df1e42829838

**Comment by daneoshiga** [comment]
a [recent post](https://blog.jonlu.ca/posts/async-python-http) that compares httpx and aiohttp
at least in this implementation, httpx is slower, although I personally prefer httpx

**Comment by Olegt0rr** [comment]
That's why I would not recommend setting it as the default client. Alternative only.
