### ISSUE TITLE
Add offline documentation

### ISSUE THREAD

**Issue by goduni** [aiogram/aiogram#286]
I suggest adding documentation via the command line like `python -m pydoc -p 8080`

When launched, a browser opens with a copy of https://aiogram.readthedocs.io/en/latest/

**Comment by uwinx** [comment]
@Bunk100. Thanks for the suggestion. It would be nice if you could give us some use cases.

FYI, you can clone the project and `make docs`

**Comment by JrooTJunior** [comment]
Documentation can be downloaded from ReadTheDocs in pdf, html or epub formats: 
![image](https://github.com/aiogram/aiogram/assets/6726423/87d0bf47-43bf-49c3-9da7-ce1e79b46499)
