### ISSUE TITLE
Display button selection

### ISSUE THREAD

**Issue by Harut0726** [aiogram/aiogram#291]
How can I display selection of InlineKeyboardButton? I want user to see which buttons he selected.

**Comment by MasterGroosha** [comment]
Append/remove "tick" emoji to button text

**Comment by b0g3r** [comment]
![image](https://user-images.githubusercontent.com/19777948/78473347-8fac3600-7748-11ea-99c0-24ae235f1ac8.png)

I used two `·` around button text

**Comment by Olegt0rr** [comment]
@Harut0726,
you can use any marker as you wish in the name of selected button.
For example you can mark selected button with ☑️

```python
markup = InlineKeyboardMarkup()
button_states = {
    'pork': False,
    'beef': True,
    'chicken': False,
}

for meat, state in button_states.items():
    if state is True:
        button_name = f'☑️ {meat}'
    else:
        button_name = f'{meat}'
    markup.add(InlineKeyboardButton(button_name, callback_data=meat))
```

**Comment by evgfilim1** [comment]
@Harut0726 if you still have questions, you can ask them in our [Telegram chat](https://t.me/aiogram)
