### ISSUE TITLE
Get bot's user_id without get_me

### ISSUE THREAD

**Issue by Olegt0rr** [aiogram/aiogram#296]
**Is your feature request related to a problem? Please describe.**
Sometimes I need to check bot's user_id without using async methods

**Describe the solution you'd like**
We can get bot's user_id from token :)
To make it more handy we can add to bot 'id' param and call bot.id if we need to get it :)

**Comment by evgfilim1** [comment]
Another possible solution can be making `bot.me` cache-only property, so it becomes sync. And to update cache one can use `await bot.get_me()` (or even the bot itself on startup).
Also, this method is always called when executor starts polling or listening on webhook.
https://github.com/aiogram/aiogram/blob/5de9c9853e3af4611c59d144db858d76ea4ce5f3/aiogram/utils/executor.py#L346

**Comment by Olegt0rr** [comment]
```int(token.split(sep=':')[0])```

Solution with id from token looks ugly, but 
- requires NO calls to api
- requires NO started polling/webhook

Solution with changing `bot.me` behaviour can break compatibility.
To add chache-only property we should use another name, not used before. For example: `bot.user`

**Comment by evgfilim1** [comment]
@Olegt0rr IMO it would be nice to get not only bot ID, but also bot username :thinking: 
But it's not possible without an additional request to the API.
And yes, it breaks compatibility. Maybe we can implement my suggestion in 3.x?
