### ISSUE TITLE
Change default parse_mode argument for send_* methods

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#302]
## Description
It'll be better to change default `parse_mode` argument for all `send_*` methods to be able to explicitly remove `parse_mode` in single request by passing `None` there: 

## Actual behaviour
```python
In[3]: bot = Bot(TOKEN, parse_mode=types.ParseMode.HTML)
In[4]: await bot.send_message(231030383, "Hello, <world>", parse_mode=None)
...
CantParseEntities: Can't parse entities: unsupported start tag "world" at byte offset 7
```

## Expected behaviour
```python
In[4]: str(await bot.send_message(231030383, "Hello, <world>", parse_mode=None))
Out[4]: '{"message_id": 7442, "from": {"id": ***, "is_bot": true, "first_name": "Test Bot", "username": "***"}, "chat": {"id": 230130383, "first_name": "Evgen", "last_name": "Fil //", "username": "evgfilim1", "type": "private"}, "date": 1586623103, "text": "Hello, <world>"}'
```

## Current workaround
```python
In[4]: str(await bot.send_message(231030383, "Hello, <world>", parse_mode=''))
Out[4]: '{"message_id": 7442, "from": {"id": ***, "is_bot": true, "first_name": "Test Bot", "username": "***"}, "chat": {"id": 230130383, "first_name": "Evgen", "last_name": "Fil //", "username": "evgfilim1", "type": "private"}, "date": 1586623103, "text": "Hello, <world>"}'
```

## Suggested solution
Something like in aiohttp (`None` value for timeout means no timeout at all): [Passing arg](https://github.com/aio-libs/aiohttp/blob/dbf7f2ca038d3c622338305d7151e250403a39ea/aiohttp/client.py#L201), [checking arg](https://github.com/aio-libs/aiohttp/blob/dbf7f2ca038d3c622338305d7151e250403a39ea/aiohttp/client.py#L235-L238)

**Comment by evgfilim1** [comment]
PR was merged into dev-3.x

**Comment by Y-Irash** [comment]
parse_mode=""
