### ISSUE TITLE
Chat.get_url() improvements

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#321]
Currently [get_url](https://github.com/aiogram/aiogram/blob/8f07b1248e9e69fd64edefd80f2b5b2d2f808dc9/aiogram/types/chat.py#L89) method for Chat object may return None if requested in private channel.

Suggestion: try making a new invite link in this method.

However, this will introduce a new problem: `export_chat_invite_link` may throw `aiogram.utils.exceptions.BadRequest: Not enough rights to export chat invite link`, which makes code more prone to errors (`get_url` currently does not throw any exceptions).

Also, a new Exception should be introduced: NotEnoughRights (there is currently NotEnoughRightsToRestrict, which may be combined to just NotEnoughRights)

**Comment by Olegt0rr** [comment]
This method didn't use `export_chat_invite_link` inside.
`get_url` - just handy shortcut to get already generated link (if it exists).
To generate link use `export_chat_invite_link` method instead.

**Comment by draklowell** [comment]
@evgfilim1, @JrooTJunior, I think we need to close the issue. Commit [09f540c](https://github.com/aiogram/aiogram/commit/09f540cc68ba78fa7f9fd470c76885aa97b48634) adds this feature.
