### ISSUE TITLE
with_token меняет токен для ВСЕХ ботов в текущем контексте, а н етолько для того, для которого вызван

### ISSUE THREAD

**Issue by Tishka17** [aiogram/aiogram#323]
Ожидается что with_token поменяет токен для текущего бота или создаст нового бота с текущими настройками и новым токеном.

Вместо этого он меняет токен для всех ботов в текущем контексте.

**Comment by JrooTJunior** [comment]
Не ожидается. Эта фича для очень узкого кейса, когда нужно выполнить запрос к API (например отправить сообщение), но не более. Он работает именно так как и планировался. И вообще ветка 2.х не предназначена для "мультиботов" из коробки.
