### ISSUE TITLE
StateGroup.next не возвращает следующий стейт относительно текущего, а делает что-то странное

### ISSUE THREAD

**Issue by Tishka17** [aiogram/aiogram#324]
Предполагается, что FSMContext - управляет стейтами, а StateGroup - набор стейтов для управления переходами. 
Ожидается что StateGroup.next должен вернуть следующий стейт относительно переданного. Вместо этого оно само обращается в неизвестный экземпляр FSMContext 

В сценарии с формами ввода для каждого шага удобно зафиксировать дополнительные данные  (например, название шага) и в этом случае нужно получать следующий и предыдущий шаг без изменения. Тем более, для изменения уже есть FSMContext

**Comment by p82o** [comment]
Вы неправильно поняли логику работы StateGroup.next. Тут происходит **смена текущего состояния на следующее**, с возвратом строкой имени нового состояния.

**Comment by uwinx** [comment]
@Tishka17, `StatesGroup.next` меняет текущее состояние на следующее, если оно имеется, иначе на состояние по-умолчанию (`None`). Кроме замены на следующее состояние, метод возвращает `Optional[str]`, что означает следующее состояние или состояние по-умолчанию (`None`)

Если есть предложение, то ждём предложений или нового PR.

[алгоритм получения следующего состояния из контекста.](https://github.com/aiogram/aiogram/blob/4863675d28e841fb0ec8b85e77940599d7b5f013/aiogram/dispatcher/filters/state.py#L146)
