### ISSUE TITLE
[3.x] Customizable get_url() method on Message object

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#335]
**Is your feature request related to a problem? Please describe.**
This is a continuation of #334.
Currently an `url` property of Message object returns public t.me link if group has `@username` and private link in all other cases. However, sometimes user may want to get a private url even for public supergroup/channel. For example, when username is subject to change or chat is going to become private.

**Describe the solution you'd like**
I personally discourage adding a `private_link` property to aiogram 2.x since it would introduce unnecessary code duplication. For example, if Telegram decides to change `t.me/c/` path to something else, we will have to edit 2 lines instead of 1.
However, since 3.x branch is not yet ready for production and is subject to have breaking changes, it's possible to replace `url` property with `get_url()` method:

```python
def get_url(self, force_private=False) -> str:
    """
    Get URL for the message
    :param force_private: Force generate a private URL even when username is available
    :return: str
    """
    if ChatType.is_private(self.chat):
        raise TypeError('Invalid chat type!')

    url = 'https://t.me/'
    if not self.chat.username or force_private:
        # Generates private link available for chat members
        url += f'c/{self.chat.shifted_id}/'
    else:
        # Generates public link
        url += f'{self.chat.username}/'
    url += f'{self.message_id}'

    return url
```

**Describe alternatives you've considered**
We can just add `privale_url` property, but as I said before it will lead to code duplication, which is not good in the long run.

**Comment by igorsereda** [comment]
You can avoid using ["magic numbers"](https://en.wikipedia.org/wiki/Magic_number_(programming)) in your method and define a template for generating links somewhere in constants.

**Comment by MasterGroosha** [comment]
@igorsereda where do you see a magic number here?

**Comment by MasterGroosha** [comment]
Closing as I did it myself: #585
