### ISSUE TITLE
answer_audio (sendAudio) method missing thumb parameter

### ISSUE THREAD

**Issue by JohnyXXX** [aiogram/aiogram#357]
### In sendAudio method missing thumb parameter.
```python
async def answer_audio(self,
                       audio: Union[InputFile, String],
                       caption: Optional[String] = None,
                       parse_mode: Optional[String] = None,
                       duration: Optional[Integer] = None,
                       performer: Optional[String] = None,
                       title: Optional[String] = None,
                       disable_notification: Optional[Boolean] = None,
                       reply_markup: Union[InlineKeyboardMarkup, ReplyKeyboardMarkup, ReplyKeyboardRemove, ForceReply, None] = None,
                       reply: Boolean = False) -> Coroutine[Any, Any, Message]
```
## In source: https://core.telegram.org/bots/api#sendaudio
Parameter | Type | Required | Description
---------- | ----- | --------- | ------------
thumb | [InputFile](https://core.telegram.org/bots/api#inputfile) or String | Optional | Thumbnail of the file sent; can be ignored if thumbnail generation for the file is supported server-side. The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320. Ignored if the file is not uploaded using multipart/form-data. Thumbnails can't be reused and can be only uploaded as a new file, so you can pass “attach://<file_attach_name>” if the thumbnail was uploaded using multipart/form-data under <file_attach_name>. [More info on Sending Files »](https://core.telegram.org/bots/api#sending-files)

**Comment by ixearth** [comment]
I also experienced this issue but with `reply_audio`, and seems it works for me after [add thumbs parameter](https://github.com/ixearth/cpop_bot/blob/0c33258cb1bdf0367da73a5ba540f3b5e450d197/patch/aiogram-fix-reply-audio-thumb.patch).

https://github.com/aiogram/aiogram/blob/8d30c1dc1b9a494178835ec09e389444cd6fcbbd/aiogram/types/message.py#L436

The documentation also need update, the official [Telegram Bot API website](https://core.telegram.org/bots/api#inputmediaanimation) says

> The thumbnail should be in JPEG format and less than 200 kB in size. A thumbnail's width and height should not exceed 320.

**Comment by Birdi7** [comment]
Hello @ixearth & @JohnyXXX. Thank you both for your requests: there are a couple of missing parameters in these methods. Looks like it's an easily fixable issue: just add a new parameter to `answer_audio`, and then pass it to the inner calling of `bot.send_audio`. The patch from @ixearth is totally correct, as far as I am concerned. Would you mind to create PRs to fix your issues, guys?

**Comment by ixearth** [comment]
@Birdi7 I've opened the PR but I didn't test the code.

**Comment by Birdi7** [comment]
That's ok for PRs, which target dev-2.x branch, as there is a lack of tests
inside it already :D

**Comment by JohnyXXX** [comment]
Thanks guys. My problem is resolved :)
