### ISSUE TITLE
markdown.escape_md() doesn't escape '=' sign

### ISSUE THREAD

**Issue by unintended** [aiogram/aiogram#360]
## Context

From the [docs](https://core.telegram.org/bots/api#markdownv2-style):

> In all other places characters '_', '*', '[', ']', '(', ')', '~', '`', '>', '#', '+', '-', '=', '|', '{', '}', '.', '!' must be escaped with the preceding character '\'.

* aiogram version: 2.9.2

## Expected Behavior

markdown.escape_md() escapes '=' sign

## Current Behavior

'=' sign is not escaped

## Failure Information (for bugs)
trying to send such text results in the error:

> aiogram.utils.exceptions.CantParseEntities: Can't parse entities: character '=' is reserved and must be escaped with the preceding '\'

**Comment by Birdi7** [comment]
Will be closed in #359
