### ISSUE TITLE
[question] chat list

### ISSUE THREAD

**Issue by toxicmender** [aiogram/aiogram#364]
I'm obviously new to using this module and telegram bot API so apologies in advance for asking stupid questions.

Question: How do you get the list of chats (list of chat_id or chat_url) in which your Bot has been invited or joined programmatically using the API? 

for example to intimate the users of any breaking changes or additional features you've added to the bot

**Comment by evgfilim1** [comment]
@toxicmender Hello. You cannot simply get all the chats your bot is part of. But you can record all incoming commands, messages and their chat ids in some kind of database.

P.S. We have a Telegram chat: [@aiogram](https://t.me/aiogram). You can join us and ask further questions there (if any) :)
