### ISSUE TITLE
How to get all members 

### ISSUE THREAD

**Issue by draklowell** [aiogram/aiogram#366]
Can I get all members in chat/channel. Or handle new user join?

**Comment by evgfilim1** [comment]
@draklowell Hello. It's not possible to handle new user join in channels and big (50+ members AFAIK) chats via Bot API. Also it's not possible to get all members in chat/channel.

P.S. You can join our Telegram chat: [@aiogram](https://t.me/aiogram). I think it's better to discuss there.
