### ISSUE TITLE
get default chat permissions for all members

### ISSUE THREAD

**Issue by evjeny-23** [aiogram/aiogram#382]
I sometimes need to get default chat permissions for all members. But there isn't any option to do this (or at least it isn't described in the documentation). It would be very nice to see that feature.

**Comment by gabbhack** [comment]
Can you explain in more detail?

You can get default permissions like this.
```python
chat = await bot.get_chat(chat_id)
# chat.permissions
```

**Comment by WhiteMemory99** [comment]
> chat.permissions are permissions set for bot. I would like to get permissions that are default for all users.

TF? They are not for the bot. You can get your bot permissions with getChatMember, but chat.permissions is default for users.

**Comment by Olegt0rr** [comment]
> > Can you explain in more detail?
> > You can get default permissions like this:
> > ```python
> > chat = await bot.get_chat(chat_id)
> > # chat.permissions
> > ```
> 
> chat.permissions are permissions set for bot. I would like to get permissions that are default for all users.

No.
Please read the docs: https://core.telegram.org/bots/api#chat

**permissions**
Default chat member permissions, for groups and supergroups.
