### ISSUE TITLE
Typo in message_handler examples 

### ISSUE THREAD

**Issue by csd-oss** [aiogram/aiogram#385]
## Context

I tried to use rexexp as param for message_handler cos it is written so in dispatcher.py file and https://docs.aiogram.dev/en/dev-1.x/dispatcher/main.html but it is not working. Changed rexexp to regexp and everything working

* Operating System: MacOS 10.15.2 
* Python Version: Python 3.7.7
* aiogram version: 2.9.2            
* aiohttp version: 3.6.2
* uvloop version (if installed): 

## Expected Behavior

Examples should work, when I am trying to use them.

## Current Behavior

Examples doesn'e work, when I am trying to use them.

### Steps to Reproduce

1. Open dispatcher.py file
2. Find @dp.message_handler(rexexp='^[a-z]+-[0-9]+')
3. Try to use it in your code 
4. ``
Traceback (most recent call last):
  File "tgReciver.py", line 37, in <module>
    async def tg_reciver(message: types.Message):
  File "/Users/mk/Library/Python/3.7/lib/python/site-packages/aiogram/dispatcher/dispatcher.py", line 486, in decorator
    state=state, run_task=run_task, **kwargs)
  File "/Users/mk/Library/Python/3.7/lib/python/site-packages/aiogram/dispatcher/dispatcher.py", line 409, in register_message_handler
    **kwargs)
  File "/Users/mk/Library/Python/3.7/lib/python/site-packages/aiogram/dispatcher/filters/factory.py", line 53, in resolve
    {k: v for k, v in full_config.items() if v is not None}))
  File "/Users/mk/Library/Python/3.7/lib/python/site-packages/aiogram/dispatcher/filters/factory.py", line 73, in _resolve_registered
    raise NameError("Invalid filter name(s): '" + "', ".join(full_config.keys()) + "'")
NameError: Invalid filter name(s): 'rexexp'
``

**Comment by csd-oss** [comment]
Can't really understand how to run all the tests at once is it possible?

**Comment by JrooTJunior** [comment]
Typo in filter name.
Correct name is `regexp`

regexp - regular expression.

**Comment by JrooTJunior** [comment]
Why do you use docs for 1.x version?
1.x is no more supported. Just use 2.x (2.9.2)

**Comment by csd-oss** [comment]
Cos initially I just used cmd+click to see how the decorator is written and info was there. 

Using web docs for the second version was giving me an error, cos I switched from Dispatcher page, haven't noticed it.
![image](https://user-images.githubusercontent.com/58642039/88013258-a2dee800-cb24-11ea-8602-b07a1c750c03.png)
