### ISSUE TITLE
Fsm storage must work for a group basis so fsm listner can listen every user message

### ISSUE THREAD

**Issue by MuzaffarAliShah** [aiogram/aiogram#392]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by uwinx** [comment]
@MuzaffarAliShah, can you describe problem you're encountering?

**Comment by evgfilim1** [comment]
I'm closing this issue as stale. Feel free to reopen it if needed.
