### ISSUE TITLE
Switch downloads badge source to pepy.tech

### ISSUE THREAD

**Issue by JrooTJunior** [aiogram/aiogram#403]
pypistats.org returns a 502 error in the last week so i think need to migrate to another statistics service like https://pepy.tech/project/aiogram

**Comment by JrooTJunior** [comment]
https://github.com/crflynn/pypistats.org/issues/29

**Comment by uwinx** [comment]
https://github.com/crflynn/pypistats.org/issues/29#issuecomment-674453959
