### ISSUE TITLE
Documentation for advanced use of Dispatcher in callbacks

### ISSUE THREAD

**Issue by iuriguilherme** [aiogram/aiogram#412]
(this is for aiogram version 2)

I couldn't find documentation for mixins while trying to figure out how to find a bot from the context of a handler callback.

In the [Dispatcher docs](https://docs.aiogram.dev/en/latest/dispatcher/index.html#aiogram.Dispatcher) we can see that it's an object which bases are **aiogram.utils.mixins.DataMixin, aiogram.utils.mixins.ContextInstanceMixin**.

In the [Middleware and Antiflood example](https://docs.aiogram.dev/en/latest/examples/middleware_and_antiflood.html) is mentioned that a dispatcher can be instantiated from the context of the callback:

``` python
# Get dispatcher from context
dispatcher = Dispatcher.get_current()
```

Having access to this allows for a self contained callback function which doesn't have to import the **Bot()** from elsewhere if the callback code is imported from a module or package (multiple files).

I assume the **.get_current()** method is inherited from the mixin object, but maybe it's from elsewhere.

Example, SnitchBot (modified EchoBot):

``` python
@dp.message_handler(commands=['start', 'help'])
async def send_welcome(message: types.Message):
    """
    This handler will be called when user sends `/start` or `/help` command
    """
    this_dispatcher = Dispatcher.get_current()
    this_bot = this_dispatcher.bot
    await message.reply("Hi {first_name},  I'm EchoBot\!\nYour *telegram\_id* is `{chat_id}`\.\nPowered by aiogram\.".format(first_name = message.from_user.first_name, chat_id = message.from_user.id), parse_mode="MarkdownV2")
    ## Snitch to someone else that this user sent a command to the bot
    await this_bot.sendMessage(someone_else_chat_id, "@{username} just sent me {command}.".format(username = message.from_user.username, command = message.get_command()))
```

**Comment by JrooTJunior** [comment]
Stale issue

v2.x will no longer be supported in due to 3.0 is coming
---

You can get Bot instance as the handler arumgents directly
