### ISSUE TITLE
[2.x] Add a new ParseMode enum option representing "no parse mode"

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#416]
**Is your feature request related to a problem? Please describe.**
Currently [ParseMode enum](https://github.com/aiogram/aiogram/blame/dev-2.x/aiogram/types/message.py#L2306) is missing "none" or "plaintext" option.
For example, if your bot has a default parse mode set to HTML, but you want to send a message without parse mode, you'll have to explicitly set it to `parse_mode=""`.

**Describe the solution you'd like**
 I suggest adding a new ParseMode type: ParseMode.NONE or ParseMode.PLAIN / ParseMode.PLAINTEXT.

Also documentation for this object is missing MarkdownV2 description :)

**Describe alternatives you've considered**
Setting parse mode manually as `parse_mode=""`

Additional Info: 
As far as I see, this enum's values are converted automatically to strings. MARKDOWN_V2 -> "MarkdownV2".
However, the case of "none" must be handled separately.

**Comment by evgfilim1** [comment]
Already implemented in 3.0: #303 

Do you want this feature in 2.x too?

**Comment by MasterGroosha** [comment]
It depends in 3.0 release schedule. Personally I can live without this feature. Let the community decide.

**Comment by JrooTJunior** [comment]
Implemented in v3
