### ISSUE TITLE
Не работает skip_updates в чатах. / Skip_updates does not work in chats.

### ISSUE THREAD

**Issue by homus32** [aiogram/aiogram#418]
## Context
RUS:
У меня есть бот в беседе тг и если бот оффлайн и есть сообщения которые бот не видел то бот среагирует на них даже если установлен skip_updates на Ture
Я ешё новичок в этом фреймворке
___
ENG:
I have a bot in a  tg conversation and if the bot is offline and there are messages that the bot did not see, then the bot will react to them even if skip_updates is set to Ture
I am still new to this framework
___

* Operating System: Ubuntu 18.04
* Python Version: 3.8
* aiogram version: 2.9.2
* aiohttp version: 3.6.2
* uvloop version (if installed): yes 

## Expected Behavior

Бот должен пропускать все отправленные сообщения в беседе
___
The bot should skip all sent messages in the conversation

## Current Behavior

Бот реагирует на старые сообщения в беседе.
___
The bot reacts to old messages in the conversation.

### Steps to Reproduce

1. download script
2. invite the bot to chat
3. write messages to chat
4. start bot
the bot will write your message
```python
import logging

from aiogram import Bot, Dispatcher, executor, types
from aiogram.types.message import ContentTypes

# Configure logging
logging.basicConfig(level=logging.INFO)


# Initialize bot and dispatcher
tg_bot = Bot(token='')
tg_dp = Dispatcher(tg_bot)


@tg_dp.message_handler(content_types=ContentTypes.TEXT)
async def test(message: types.Message):
    await message.answer(message.text)


if __name__ == '__main__':
    executor.start_polling(tg_dp, skip_updates=True)
````

**Comment by homus32** [comment]
Сейчас оно отправляет последнее сообщение, но раньше отправляла всю переписку...

**Comment by WhiteMemory99** [comment]
Оно отвечает только на те сообщения, которые отправлены совсем недавно относительно запуска бота, когда skip_updates активен

**Comment by homus32** [comment]
> Оно отвечает только на те сообщения, которые отправлены совсем недавно относительно запуска бота, когда skip_updates активен.
> Это идёт в плюс с точки зрения работы бота.
> На старые апдейты он отвечать не будет.

@WhiteMemory99 
я сейчас опять вкючил бота он и не проигнорировал сообщение котор было отправлено 7 часов назад...

**Comment by evgfilim1** [comment]
Ещё актуально?

**Comment by khumoyun2008** [comment]
same

**Comment by waslost0** [comment]
ye, same

**Comment by gabbhack** [comment]
> By default, updates starting with the earliest **unconfirmed** update are returned. An update is considered **confirmed** as soon as getUpdates is called with an **offset higher than its update_id**.[0]

Workaround:
Call [deleteWebhook](https://core.telegram.org/bots/api#deletewebhook) before starting the bot[1]
```py
await bot.delete_webhook(drop_pending_updates=True)
```
or
play with the offsets as it says in the documentation[2]
```py
u = await bot.get_updates(offset=-1, timeout=1)
if u:
    await bot.get_updates(offset=u[0].update_id+1, timeout=1)
```

I think we need to change the behavior of `skip_updates` in future versions of aiogram.
[0]: https://core.telegram.org/bots/api#getupdates
[1]: https://t.me/aiogram_ru/997810
[2]: https://t.me/aiogram_ru/997829
