### ISSUE TITLE
Finite state machine example

### ISSUE THREAD

**Issue by Sultan91** [aiogram/aiogram#425]
## Context
Trying to run [this example](https://github.com/aiogram/aiogram/blob/dev-2.x/examples/finite_state_machine_example.py) for bot inside a group chat but it doesn't work

* Operating System: Ubuntu 20
* Python Version: 3.7
* aiogram version: 2.10.1
* aiohttp version:  3.6.2
* uvloop version (if installed): 

## Expected Behavior
State propagation as in private 1 on 1 chat
Please describe the behavior you are expecting
Stuck on first state, not going further
## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by Olegt0rr** [comment]
Can't reproduce.
Make sure you reply to bot with quoting or disable privacy mode

**Comment by evgfilim1** [comment]
I'm closing this issue as stale. Feel free to reopen it if needed.
