### ISSUE TITLE
dp.loop now return NoneType

### ISSUE THREAD

**Issue by giovanni5** [aiogram/aiogram#426]
## Context
I downgraded aiogram to 2.9.2 beacause now dp.loop doesn't return the current event loop.
aiogram 2.10.1
## Expected Behavior
dp.loop return the event loop
## Current Behavior
dp.loop return NoneType
## Failure Information (for bugs)

`AttributeError: 'NoneType' object has no attribute 'create_task'`

**Comment by uwinx** [comment]
@giovanni5, you should've never used `dp.loop`. it was an internal event loop which aiogram used wrongly.

if you're using `_MainThread`'s loop intentionally, I recommend you to pass `Dispatcher(loop=<here>)` and reuse that loop.

**Comment by giovanni5** [comment]
I will do as you say, thank you for your quick answer.
