### ISSUE TITLE
InlineKeyboardExpected after try edit message.

### ISSUE THREAD

**Issue by LulzLoL231** [aiogram/aiogram#428]
## Context

Recived InlineKeyboardExpected error after try send reply_markup in edit_text func.

* Operating System: Debian 10
* Python Version: Python 3.7.3
* aiogram version: 2.10.1
* aiohttp version: 3.6.2
* uvloop version (if installed): None

## Expected Behavior

bot send first msg, edit it and add reply keyboard.

## Current Behavior

bot send first msg, but after trying edit it and add reply keyboard recive InlineKeyboardExpected error.

### Steps to Reproduce

Code:
```python
@dp.message_handler(lambda m: True)
async def start(msg: types.Message):
    event = msg.answer('Hello!')  # send "Hello!" to user pm.
    key = types.ReplyKeyboardMarkup().add(msg.chat.mention)  # make reply keyboard with user mention text in it.
    await event.edit_text('Hi!', reply_markup=key)  # try edit sended msg, and add relpy_markup to it.
```

1. user send any msg to bot.
2. bot send msg with text "Hello"
3. bot trying edit text for sended msg, and add reply keyboard with it. But failed and recived InlineKeyboardExpected error.

### Failure Logs

traceback pastebin: https://pastebin.com/X2p2xVRW

**Comment by JrooTJunior** [comment]
You'r problem is not related to `aiogram`. Just read the docs of Telegram Bot API about [editMessageText](https://core.telegram.org/bots/api#editmessagetext).

![image](https://user-images.githubusercontent.com/6726423/93717186-c651fd80-fb7c-11ea-800c-4c6d0e33bc6f.png)
