### ISSUE TITLE
base.Integer doesn't support `==` etc

### ISSUE THREAD

**Issue by lilydjwg** [aiogram/aiogram#441]
## Context

* Operating System: Arch Linux
* Python Version: 3.8.6
* aiogram version: current dev-2.x 1e2fe72aca12a3fc6f2d1f66c71539af5a84ea00 with added `py.typed` marker file
* mypy 0.782

This is a bug report against the type annotations, not the functionality.

## Expected Behavior

`base.Integer` should support comparison and integer arithmetic. 

## Current Behavior

It doesn't support these operations.

## Failure Information (for bugs)

I cannot compare if two `User.id`s are the same one:
```
xxx: error: Unsupported left operand type for != (base.Integer?)
```

I cannot do arithmetic with `MessageEntity.offset` and `MessageEntity.length`.

### Steps to Reproduce

Just `mypy` your bot with typing enabled (#440); you'll get them.

**Comment by JrooTJunior** [comment]
Can't be fixed in 2.x versions and already fixed in alpha versions of 3.0
