### ISSUE TITLE
Fetching user from message

### ISSUE THREAD

**Issue by Yuhanun** [aiogram/aiogram#444]
Hello,

I'm working on a telegram bot, and was wondering how I could get the userID of a mention.

For example:

```py
@dp.message_handler(commands='test')
async def test_(message: types.Message):
    # message is: `/test @user`.

    # Get the id of user??
```

I have no clue how to do this,

Sorry for asking here.

**Comment by gabbhack** [comment]
Unfortunately, you can't get the user id from the username (https://core.telegram.org/bots/api#messageentity)

**Comment by Yuhanun** [comment]
Hello, 

My issue was with: https://dev-docs.aiogram.dev/api/types/message_entity/

When the type is `mention`, none of the fields seem to be populated, just with `text_mention`, am I overlooking something?

Or is telegram's api really set up in a way where only for text_mention information is provided?

**Comment by Yuhanun** [comment]
I basically need a user to select another user, and this should work regardless of whether they have their username set or not.

Please let me know.

**Comment by evgfilim1** [comment]
@Yuhanun I can suggest you to use some kind of storage (database) and save mention to user_id mapping, that's the only way for now with Bot API. If you really want, you can dig into MTProto API, IIRC it has method to resolve username to user object.
