### ISSUE TITLE
Text entities passed into sendMessage are not JSON-ised when POST-ing

### ISSUE THREAD

**Issue by sabbyX** [aiogram/aiogram#457]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:  Windows 10 20H2
* Python Version:  3.8.3
* aiogram version:  2.11
* aiohttp version: 
* uvloop version (if installed): 

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by sabbyX** [comment]
![image](https://user-images.githubusercontent.com/61574665/98470260-7a314a00-220a-11eb-90ae-1eeb6171b2d2.png)
This shows the value of field `entities` in `FormData`, yet BotAPI fail to apply the entity into text, no errors were thrown.

**Comment by JrooTJunior** [comment]
Fixed in https://github.com/aiogram/aiogram/commit/d0bfa8a13bb5dc006908be4df447b656d175503b
Will be released tomorrow.

**Comment by sabbyX** [comment]
> Fixed in [d0bfa8a](https://github.com/aiogram/aiogram/commit/d0bfa8a13bb5dc006908be4df447b656d175503b)
> Will be released tomorrow.

Yeah, I tested it. look like aiogram is passing `parse_mode` field when entities are given (causes botAPI parse text based on parse mode instead). Should I create new issue?

**Comment by JrooTJunior** [comment]
I see that when check previous problem but i don't think that is an bug.
But i think default parse mode logic should be changed...

Maybe it makes sense to backport sentinel parse mode from `dev-3.x` branch, where parse_mode=None can override globally configured parse mode.

Yep, please create an issue for this problem.
I think that will not be fixed in 2.11.1 version but soon

**Comment by JrooTJunior** [comment]
Fixed in `v2.11.1`
