### ISSUE TITLE
Cannot send playlist of audio files

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#464]
* aiogram version: 2.11.2

## Details about bug
A user [reported](https://t.me/aiogram_ru/344398) that he cannot send audio files as media group. Further investigation lead to [attach](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/input_media.py#L258) method of `MediaGroup` class which still treats audio files and documents as unsupported types for media groups. Though the ability to use such files in media groups was introduced in [Bot API 5.0](https://core.telegram.org/bots/api-changelog#november-4-2020) update.

Since the commit 2b060d9ad4e7e072fc1e6ed301867e90c6b4cdbc is missing any info about the subject, perhaps it was forgotten by accident.

## Expected Behavior
Being able to send a mediagroup of audio files and documents. 

## Current Behavior
`ValueError: This type of media is not supported by media groups!`

## Failure Information (for bugs)
See https://t.me/aiogram_ru/344398

### Steps to Reproduce
See https://t.me/aiogram_ru/344398

**Comment by Stas048** [comment]
> * aiogram version: 2.11.2
> 
> 
> 
> ## Details about bug
> 
> A user [reported](https://t.me/aiogram_ru/344398) that he cannot send audio files as media group. Further investigation lead to [attach](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/input_media.py#L258) method of `MediaGroup` class which still treats audio files and documents as unsupported types for media groups. Though the ability to use such files in media groups was introduced in [Bot API 5.0](https://core.telegram.org/bots/api-changelog#november-4-2020) update.
> 
> 
> 
> Since the commit 2b060d9ad4e7e072fc1e6ed301867e90c6b4cdbc is missing any info about the subject, perhaps it was forgotten by accident.
> 
> 
> 
> ## Expected Behavior
> 
> Being able to send a mediagroup of audio files and documents. 
> 
> 
> 
> ## Current Behavior
> 
> `ValueError: This type of media is not supported by media groups!`
> 
> 
> 
> ## Failure Information (for bugs)
> 
> See https://t.me/aiogram_ru/344398
> 
> 
> 
> ### Steps to Reproduce
> 
> See https://t.me/aiogram_ru/344398
> 
> 
> 
>
