### ISSUE TITLE
MediaGroup class missing attach_audio and attach_document methods

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#467]
aiogram 2.11.2
These methods are commented out, but they probably should be un-commented, right?

https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/input_media.py#L313
https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/input_media.py#L341

**Comment by Olegt0rr** [comment]
lol, yes

anything else?)

**Comment by MasterGroosha** [comment]
Haven't found anything else yet :(
