### ISSUE TITLE
Does aiogram support multi-threading

### ISSUE THREAD

**Issue by draklowell** [aiogram/aiogram#472]
If server have 2 cpu, Does aiogram run on them? Or only one?

**Comment by Olegt0rr** [comment]
1. `multi-threading` is not equal `using of several cpu`.
1. Read something about `process load` and `cpu load` difference.
1. Read something about `multiprocessing`.
1. `aiogram` by default living in 1 process, but `C`-libraries like `uvloop`, `ujson` not blocked by GIL and use all available CPUs. 
1. Hardest `cpu-bound` operation in `aiogram` is serialization - it's covered by `ujson`
1. If you need your application more stable - balance `webhooks` for some instances of your app.
1. If you wanna use one instance of `aiogram` in multiprocessing mode you should use another web-server, like `sanic`

**Comment by draklowell** [comment]
Thx for answer! I think it is enough)
