### ISSUE TITLE
Util `get_start_link` rejects payload even with encoding

### ISSUE THREAD

**Issue by Olegt0rr** [aiogram/aiogram#480]
## Context

Trying to generate `?start` link with complex payload...
```python
from aiogram.utils.deep_linking import get_start_link

result = await get_start_link("hello:world")

# Result:
# ValueError: Wrong payload! Only A-Z, a-z, 0-9, _ and - are allowed. 
# We recommend to encode parameters with binary and other types of content
```

Okay, let's encode it.

```python
result = await get_start_link("hello:world", encode=True)

# Result:
# ValueError: Wrong payload! Only A-Z, a-z, 0-9, _ and - are allowed. 
# We recommend to encode parameters with binary and other types of content
```

## Expected Behavior

with `encode=True` param, payload shouldn't be filtrered with `filter_payload` function before encoding

P.S.: also don't forget to remove `=` after encoding!
It will not pass the `filter_payload `!

**Comment by JrooTJunior** [comment]
Does this problem still occur on 3.0? Seems like no

**Comment by Olegt0rr** [comment]
I'll check it during migration

**Comment by Olegt0rr** [comment]
Can't reproduce
