### ISSUE TITLE
Losing first word of message with Markdown pre encoding

### ISSUE THREAD

**Issue by wofka72** [aiogram/aiogram#481]
## UPD. See [the comment below](https://github.com/aiogram/aiogram/issues/481#issuecomment-747653124) for real issue

=== Original issue text starts here ===
## Context
* Operating System: Ubuntu 18.04
* Python Version: 3.8.0
* aiogram version: 2.9.2
* aiohttp version: 3.6.2
* uvloop version (if installed): Not installed

## Expected Behavior
Message sended with `parse_mode=ParseMode.MARKDOWN` and wrapped with ` ``` `-braces loses first line (text till linebreak) if it have more than one line. 

## Current Behavior
First line should be sent too.

### Steps to Reproduce
```
from aiogram import Bot
from aiogram.dispatcher import Dispatcher
from aiogram.types import ParseMode, Message
from aiogram.utils import executor

bot = Bot(token="<your_token>")
dp = Dispatcher(bot)

@dp.message_handler()
async def echo_message(msg: Message):
    await bot.send_message(msg.from_user.id, "```123\n456```", parse_mode=ParseMode.MARKDOWN)

executor.start_polling(dp)
```
loses first line:
![image](https://user-images.githubusercontent.com/10855340/102528393-8a610280-40af-11eb-90b4-38639525dcd4.png)

```
async def echo_message(msg: Message):
    await bot.send_message(msg.from_user.id, "```123```", parse_mode=ParseMode.MARKDOWN)
```
works well:
![image](https://user-images.githubusercontent.com/10855340/102528551-c4ca9f80-40af-11eb-802f-872b7e31a350.png)

## Possible workaround before fix
1) Adding extra linebreak to the beginning of message.
```
await bot.send_message(msg.from_user.id, "```\n123\n456```", parse_mode=ParseMode.MARKDOWN)
```
![image](https://user-images.githubusercontent.com/10855340/102528628-dd3aba00-40af-11eb-8182-4b6e5da9df3d.png)

2) Using HTML encoding.
```
await bot.send_message(msg.from_user.id, "<pre>123\n456</pre>", parse_mode=ParseMode.HTML)
```

**Comment by evgfilim1** [comment]
Hello and thanks for your report. However, it is upstream feature for specifying language in code block (like [it is in GitHub](https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting)).

Screenshot from Bot API documentation (picture is clickable):
[![image](https://user-images.githubusercontent.com/17182159/102530138-b934a400-40c2-11eb-85f1-3c575b489f71.png)](https://core.telegram.org/bots/api#formatting-options)

**Comment by wofka72** [comment]
[Method `pre`](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/utils/text_decorations.py#L188-L189) of `aiogram.utils.text_decoration.MarkdownDecoration` class just wraps text with tripple-quotes ` ``` `.
And sending such messages omits first word too.

```python
from aiogram.utils.markdown import markdown_decoration as markdown  # use the object of class specified above
await bot.send_message(msg.from_user.id, markdown.pre("Answer: 42"), parse_mode=ParseMode.MARKDOWN)
```
![image](https://user-images.githubusercontent.com/10855340/102534164-630e3380-40b7-11eb-94c4-f5e7c8e43d68.png)

I trapped little bit to this type of behaviour. I think that it could be strange and not obvious for new users. And on the other side it's small and some code could consider this behaviour. So I think that it shouldn't be changed on this stage of the project.
Just writing here about this feature :)

**Comment by evgfilim1** [comment]
> And sending such messages omits first word too.

Oh, now it looks like a _small_ bug in our side. I'll reopen this issue and update the description. Thanks for clarification, @wofka72.

**Comment by p82o** [comment]
label upstream can be removed
