### ISSUE TITLE
Add support for third-party logging (e.g loguru)

### ISSUE THREAD

**Issue by aalekseevx** [aiogram/aiogram#483]
**Is your feature request related to a problem? Please describe.**
Yes, I want to integrate aiogram with loguru in my project.

**Describe the solution you'd like**
Third-party logging classes can be used with LoggingMiddleware

**Additional context**
I will submit a tiny PR solving the issue very-very shortly.

**Comment by JrooTJunior** [comment]
Doesn't require any changes in their code because just [read the docs of loguru](https://github.com/Delgan/loguru#entirely-compatible-with-standard-logging)

**Comment by aalekseevx** [comment]
I see, thanks! Should I close PR and issue or it may be useful for non-compatible logger classes?
