### ISSUE TITLE
Cannot reply twice

### ISSUE THREAD

**Issue by Zverik** [aiogram/aiogram#485]
## Context

* Operating System: Fedora Linux 32
* Python Version: 3.8.6
* aiogram version: 2.11.2
* aiohttp version: 3.7.3
* uvloop version (if installed): not installed

## Expected Behavior

I send the bot a line and it replies with two lines.

## Current Behavior

When I make a simple echo-bot like in the example, everything works. When I add another `await message.answer()`, the bot replies the first time, but not again.

## Failure Information (for bugs)

This locking occurs when there is a second `await` in the processing function, whether it's calling a method of `aiogram`, `aiosqlite` or even another async function with nothing aio-related inside.

### Steps to Reproduce

```python
from aiogram import Bot, Dispatcher, executor

bot = Bot(token='my_token')
dp = Dispatcher(bot)


@dp.message_handler()
async def echo(message):
    await message.reply('ok!')
    await message.answer('op')


if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True)
```

### Failure Logs

There is nothing relevant in the logs.

**Comment by Zverik** [comment]
To clarify, this behaves the same:

```python
async def nothing():
    return None


@dp.message_handler()
async def echo(message):
    await nothing()
    await message.answer('op')
```

**Comment by Zverik** [comment]
Update: did some testing, and after 2 minutes (!) since sending a message I get a reply. And then all my queries are returned immediately.

I don't see `120` for a constant in the code. Why could that be?

**Comment by evgfilim1** [comment]
Can't it be related to #246?

@Zverik try to disable IPv6, maybe it'll help you

**Comment by evgfilim1** [comment]
@Zverik Is it still reproducible?

**Comment by evgfilim1** [comment]
Closing as inactive. Feel free to comment here if it's still reproducible.
