### ISSUE TITLE
fix provider_data in send_invoice

### ISSUE THREAD

**Issue by SOAPkelele** [aiogram/aiogram#499]
## Failure Information (for bugs)

provider_data in send_invoice method should be encoded to JSON or should be str like it is in the docs, currently it is Optional[Dict]

**Comment by evgfilim1** [comment]
Hello, @SOAPkelele. Thanks for reporting! However, all fields are encoded to JSON anyway when sending to Bot API endpoint. Just pass a dictionary there, everything will be done for you.

**P.S.** While I was looking into the issue, I've found that `provider_data` is not JSON-encoded when sending to Bot API. I'll fix that a bit later.

**Comment by evgfilim1** [comment]
I'm closing this as 1f57a40c45f6d94d010e928bd18ab16a9720df69 fixed the issue
