### ISSUE TITLE
BotKicked exception match string outdated?

### ISSUE THREAD

**Issue by wetterkrank** [aiogram/aiogram#500]
Looks like the error message string expected by BotKicked exception isn't matching the current Telegram API response.
So the `BotKicked` exception is never raised.

## Expected Behavior

`BotKicked` exception should be raised.

## Current Behavior

`TelegramAPIError` exception is raised with the following message: "Forbidden: bot was kicked from the group chat".
However, `BotKicked` exception isn't raised (it expects 'bot was kicked from a chat').

### Steps to Reproduce

1. Add bot to the group
2. Remove bot from the group
3. Send a message from the bot to this group

### Failure Logs

Here's the actual response from the Telegram API:
```
{
    "ok": false,
    "error_code": 403,
    "description": "Forbidden: bot was kicked from the group chat"
}
```

The [API source code](https://github.com/tdlib/telegram-bot-api/blob/master/telegram-bot-api/Client.cpp) has 3 situations for BotKicked:
- Forbidden: bot was kicked from the group chat
- Forbidden: bot was kicked from the supergroup chat
- Forbidden: bot was kicked from the channel chat

**Comment by darksidecat** [comment]
#445 close this issue, now exception work properly

@wetterkrank, does the problem still exist?

**Comment by wetterkrank** [comment]
Hi @evgfilim1: just ran a test, the BotKicked exception works as expected now. Thank you!
