### ISSUE TITLE
Problems while using an example

### ISSUE THREAD

**Issue by ENG-Rabbit** [aiogram/aiogram#503]
In Throttling example, I encounter the same error. My database is Monogodb.

`bson.errors.InvalidDocument: cannot encode object: <aiogram.types.chat.Chat object at 0x05993388>, of type: <class 'aiogram.types.chat.Chat'>`

**Comment by Olegt0rr** [comment]
It seems you're trying to save Chat object to your database.
Use `chat.to_python()` first

**Comment by ENG-Rabbit** [comment]
I found the problem ([here](https://github.com/aiogram/aiogram/blob/9de257efec17cc7d8c3b945421ef0caa56c5c278/aiogram/dispatcher/dispatcher.py#L1161)) and tried to fix it.  I edited it like the following.
```
user_id = types.User.get_current().id
chat_id = types.Chat.get_current().id
```
