### ISSUE TITLE
Inline Query switch_pm_text breaks the handler

### ISSUE THREAD

**Issue by Brandon2255p** [aiogram/aiogram#506]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Windows 10
* Python Version: 3.8.4
* aiogram version: 2.11.2
* aiohttp version: 3.7.3
* uvloop version (if installed): 

## Expected Behavior
I setup an @dp.inline_handler() and sending results works well and so does sending switch_pm_text with switch_pm_parameter.
When clicking the switch_pm button that appears it takes me to the bot chat and it sends the parameter. I expect that when I do the same inline query then it should behave as it did before so that I can repeat those steps.

## Current Behavior
Currently, after clicking the switch_pm button, it takes me to the bot and sends the parameter. But if I try the same inline query, it never activates the @db.inline_handler anymore. That function never gets called again and the whole inline query is broken until I restart the server

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. await bot.answer_inline_query(inline_query.id, results=[], cache_time=1, switch_pm_text="amount", switch_pm_parameter="info")

2. click the inline query button called "amount"
3. you are taken to the bot chat
4. try the inline query again and now the button does not appear anymore

### Failure Logs

Working:
```
DEBUG:aiogram:Response for getUpdates: [200] "'{"ok":true,"result":[{"update_id":152705188,\n"inline_query":{"id":"2313446119847705504","from":{"id":538641149,"is_bot":false,"first_name":"Brandon","username":"#####","language_code":"en"},"query":"0.001","offset":""}}]}'"
DEBUG:aiogram.dispatcher.dispatcher:Received 1 updates.
DEBUG:root:INLINE QUERY
DEBUG:root:{"id": "6779f1e2567b875807b693b1bb20738c", "title": "Send", "input_message_content": {"message_text": "I am sending you 0.001"}, "type": "article"}
DEBUG:aiogram:Make request: "answerInlineQuery" with data: "{'inline_query_id': '2313446119847705504', 'results': '[{"id": "6779f1e2567b875807b693b1bb20738c", "title": "Send", "input_message_content": {"message_text": "I am sending you 0.001"}, "type": "article"}, {"id": "b4cfa17e5ff11cad2d7d445281322745", "title": "Request", "input_message_content": {"message_text": "Please send me 0.001"}, "type": "article"}]', 'cache_time': 1}" and files "None"
DEBUG:aiogram:Make request: "getUpdates" with data: "{'offset': 152705189, 'timeout': 20}" and files "None"
DEBUG:aiogram:Response for answerInlineQuery: [200] "'{"ok":true,"result":true}'"
```

Broken
```
DEBUG:aiogram:Response for getUpdates: [200] "'{"ok":true,"result":[{"update_id":152705186,\n"inline_query":{"id":"2313446119779655998","from":{"id":538641149,"is_bot":false,"first_name":"Brandon","username":"#####","language_code":"en"},"query":"0.001","offset":""}}]}'"
DEBUG:aiogram.dispatcher.dispatcher:Received 1 updates.
DEBUG:aiogram:Make request: "getUpdates" with data: "{'offset': 152705187, 'timeout': 20}" and files "None"
```

**Comment by MasterGroosha** [comment]
Can you provide a minimal reproducible example? I mean, a complete piece of code which can by run by anyone with slight modifications only (e.g. put your own bot token)

**Comment by Brandon2255p** [comment]
I think it was a lack of understanding of how the switch_pm works. I am closing the issue
