### ISSUE TITLE
Error handlers unexpected behavior

### ISSUE THREAD

**Issue by vorlov-bash** [aiogram/aiogram#507]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Mac OS Catalina
* Python Version: 3.8.5
* aiogram version: 2.11.2
* aiohttp version: 3.7.3
* uvloop version (if installed): 

## Expected Behavior

Only 1 error handler worked.

## Current Behavior

All error handlers worked.

## Failure Information (for bugs)

There are 2 registered error handlers. The first with a specific error filter `exception=MedCaseNotFound`, which returns `True`, the second without an error filter, also returns `True`. The problem is that both handlers are processed even when one of them returns `True`.
In the source codes, I saw that `return True` does not stop the loop in the handler. Thus, unexpected behavior appears in the error loop.

### handler.py:
```
response = await handler_obj.handler(*args, **partial_data)
if response is not None:
    results.append(response)
if self.once:
    break
```
### dispatcher.py:
```
self.errors_handlers = Handler(self, once=False, middleware_key='error')
```

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. register 2 error handlers with return True in the body of both functions
2. raise Exception

**Comment by evgfilim1** [comment]
Hello, @vorlov-bash. Thanks for reporting. For now you can try one of these workarounds:
1) https://gist.github.com/Forevka/c4d00a9f716b5c79123786383b06f4c0
1) `dp.errors_handlers.once = True`

**Comment by Olegt0rr** [comment]
Core developers discussion: https://t.me/c/1173777615/8552

**Comment by evgfilim1** [comment]
> Core developers discussion: https://t.me/c/1173777615/8552

@Olegt0rr Just in case
![image](https://user-images.githubusercontent.com/17182159/143013953-37840b92-7f84-4d88-9a50-e9db8ead9ce3.png)

**Comment by Olegt0rr** [comment]
# Solution
 - add docs and examples for current behaviour 
 - add info about changed behaviour in v3.0
