### ISSUE TITLE
update_chat() method of Chat type doesn't handle errors properly

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#516]
## Context

aiogram's [update_chat()](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/chat.py#L114) method currently uses the following procedure for updating chat info:
```python
other = await self.bot.get_chat(self.id)
for key, value in other:
    self[key] = value
```
Recently Telegram silently added a new field `message_auto_delete_time` to Chat object which will cause KeyError, since there is no such field in aiogram's [Chat type](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/chat.py#L17) with all versions up to 2.11.2 (including that one).

* aiogram version: 2.11.2

## Expected Behavior

Such situations should be handled, so they don't cause KeyError flood in stdout or logs or whatever. One approach is to just ignore such field and throw a warning which can be suppressed on framework user side. Also there should be a separate check for class attribute existence.

## Current Behavior

KeyError exception is thrown

### Steps to Reproduce

1. Enable messages auto-delete timer
2. Restart bot
3. Use the following handler:
```python
@dp.message_handler(content_types=types.ContentTypes.ANY)
async def any_msg(message: types.Message):
    await message.chat.update_chat()
```

### Failure Logs

```
  File "/home/groosha/PycharmProjects/other-things/aiogram-anything.py", line 20, in any_msg
    await message.chat.update_chat()
  File "/home/groosha/PycharmProjects/other-things/venv/lib/python3.8/site-packages/aiogram/types/chat.py", line 123, in update_chat
    self[key] = value
  File "/home/groosha/PycharmProjects/other-things/venv/lib/python3.8/site-packages/aiogram/types/base.py", line 227, in __setitem__
    raise KeyError(key)
KeyError: 'message_auto_delete_time'
```

**Comment by andrew000** [comment]
### This is a temporary solution in the form of MonkeyPatch

Make a patch in a function `on_startup` in `executor.start_polling(dp, on_startup=on_startup)`

```python3
import typing

from aiogram import Dispatcher
from aiogram.types import Chat, fields
from aiogram.types.base import TelegramObject

def monkey_set_item(self, key: str, value: typing.Any) -> None:
    if key in self.props:
        return self.props[key].set_value(self, value, self.conf.get('parent', None))

async def on_startup(dp: Dispatcher):
    Chat.message_auto_delete_time = fields.Field()  # Monkey patch
    TelegramObject.__setitem__ = monkey_set_item  # Monkey patch
```

**Comment by JrooTJunior** [comment]
Fixed (ready for release)
