### ISSUE TITLE
Add built-in filter for variable in command

### ISSUE THREAD

**Issue by Andrexxelles** [aiogram/aiogram#517]
**Is your feature request related to a problem? Please describe.**

- No

**Describe the solution you'd like**

I want to add a built-in filter that would accept a non-constant variable in the command.
Exemple : /weather {city}
 
**Describe alternatives you've considered**

Splitting a sentence into a list and getting the desired item

**Additional context**

![Screenshot_10](https://user-images.githubusercontent.com/52934588/110249647-22bca400-7f88-11eb-8d0b-44f7bcc00c57.png)

**P.s I use a translator, the answer may not be accurate**

**Comment by evgfilim1** [comment]
Hello, @Andrexxelles! Thanks for suggesting this nice feature. However, there are two possible alternatives already.

- Using [`aiogram.dispatcher.filters.RegexpCommandsFilter`](https://github.com/aiogram/aiogram/blob/75222b8af020506b61af5227af2a51c7cd32d190/aiogram/dispatcher/filters/builtin.py#L438):
  ```python
  @dp.message_handler(regexp_commands=r'/w(?:eather)? (?P<city>\w+)')
  async def echo_city(message: types.Message, regexp_command: typing.Match[str]):
      city = regexp_command['city']
      await message.answer(f'Your city — {city}')
  ```
- Using [`aiogram.types.Message.get_args`](https://github.com/aiogram/aiogram/blob/75222b8af020506b61af5227af2a51c7cd32d190/aiogram/types/message.py#L204):
  ```python
  @dp.message_handler(commands=['w', 'weather'])
  async def echo_city(message: types.Message):
      city = message.get_args().split()[0]
      await message.answer(f'Your city — {city}')
  ```

So I think your suggested feature needs some discussion.

**Comment by moHAXmoHAX** [comment]
what if I want to set a prefix through a variable?

`@dp.message_handler(filters.Text(equals=f'{prefix}asd'), state='*')
async def start_command(msg: types.Message, state: FSMContext):
    await msg.answer(text=f"prefix - {prefix}")`

**Comment by evgfilim1** [comment]
> what if I want to set a prefix through a variable?

@moHAXmoHAX this should help you:
```python
@dp.message_handler(filters.Command(commands=f'asd', commands_prefix=prefix), state='*')
async def start_command(msg: types.Message, state: FSMContext):
    await msg.answer(text=f"prefix - {prefix}")
```

Better don't use text filter for matching commands.

**Comment by JrooTJunior** [comment]
Mostly implemented in v3 via magic filter
