### ISSUE TITLE
Handle messages from a group

### ISSUE THREAD

**Issue by alex-deus** [aiogram/aiogram#524]
Hello everyone,

How can I handle messages from a group? (I didn't receive messages in the `process_messages`)

- created a bot
- set privacy mod to DISABLED at BotFather:
```
> User
/setprivacy

> BotFather
Choose a bot to change group messages settings.

> User
@name_bot

> BotFather
'Enable' - your bot will only receive messages that either start with the '/' symbol or mention the bot by username.
'Disable' - your bot will receive all messages that people send to groups.
Current status is: DISABLED

> User
Disable

> BotFather
Success! The new status is: DISABLED. /help
``` 
- create a group
- added the bot to the group as an admin
- ran the code:
```python
from aiogram import Bot, Dispatcher, executor, types

bot = Bot(token="<API token>")
dp = Dispatcher(bot)


@dp.message_handler(chat_type=[types.ChatType.GROUP, types.ChatType.CHANNEL])
async def process_messages(msg: types.Message):
    ...  # TODO: to process the message

executor.start_polling(dp)
```

Permissions of the bot in the channel:
![image](https://user-images.githubusercontent.com/77075714/111037742-2c358880-842e-11eb-86bf-b3ab014d33c1.png)

**Comment by Olegt0rr** [comment]
Are you sure your gpoup type is not SUPERGROUP?

**Comment by alex-deus** [comment]
> Are you sure your gpoup type is not `supergroup`?
> 
> Try to add `ChatType.SUPERGROUP` to your `chat_type` filter list.
> 
> Also you may filter PRIVATE messages another way:
> 
> ```python
> @dp.message_handler(chat_type=types.ChatType.PRIVATE)
> async def handle_private_messages(msg: types.Message):
>     pass
> 
> @dp.message_handler()
> async def process_messages(msg: types.Message):
>     """ 
>     Catches all chat types except PRIVATE, 
>     cause it's already hadled by handle_private_messages
>     """
>     pass
> ```

Many thanks!
