### ISSUE TITLE
A Simple way to restart aiogram when internet is lost.

### ISSUE THREAD

**Issue by fenchai23** [aiogram/aiogram#536]
**Is your feature request related to a problem? Please describe.**
When Internet is lost, aiogram sends a timeout along with a bunch of other errors.

**Describe the solution you'd like**
need to find a way to detect loss of connection to telegram server and auto restart with some timeout parameter in the bot.start_polling function?

**Describe alternatives you've considered**
I have googled and have not found anyone asking for this, maybe I am a noob.

**Comment by evgfilim1** [comment]
Hello, @fenchai23. There's no need to restart the bot after internet connection is lost because aiogram is smart enough to continue polling process.

**Comment by fenchai23** [comment]
ok can confirm it is automatic, but it seems on vscode it spawns a bunch of network errors and stops. Running it with double click works.

thanks a lot!
