### ISSUE TITLE
TypeError: Value should be instance of 'User' not 'NoneType' when blocking/restarting a bot

### ISSUE THREAD

**Issue by espdev** [aiogram/aiogram#537]
## Context

* Ubuntu 20.04
* Python 3.9
* aiogram 2.12 (latest from PyPI)
* uvloop 0.15.2
* aiohttp 3.7.4.post0

## Expected Behavior

When I block or/and restart a bot I do not expect `Value should be instance of 'User' not 'NoneType'` exception. I do not understand what is going on. I need to handle these events (block and restart bot) but the exception looks strange.

## Current Behavior

I get the following exception:

```
2021-03-22 13:55:02 | ERROR    | (asyncio) - Task exception was never retrieved
future: <Task finished name='Task-10' coro=<Dispatcher._process_polling_updates() done, defined at .../python3.9/site-packages/aiogram/dispatcher/dispatcher.py:395> exception=TypeError("Value should be instance of 'User' not 'NoneType'")>
Traceback (most recent call last):
  File ".../python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 403, in _process_polling_updates
    for responses in itertools.chain.from_iterable(await self.process_updates(updates, fast)):
  File ".../python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 232, in process_updates
    return await asyncio.gather(*tasks)
  File ".../python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
  File ".../python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 298, in process_update
    types.User.set_current(update.my_chat_member.from_user)
  File ".../python3.9/site-packages/aiogram/utils/mixins.py", line 49, in set_current
    raise TypeError(f'Value should be instance of {cls.__name__!r} not {type(value).__name__!r}')
TypeError: Value should be instance of 'User' not 'NoneType'
```

### Steps to Reproduce

1. Create a bot via BotFather
2. Start the bot
3. Stop and block the bot
4. Restart the bot

**Comment by evgfilim1** [comment]
Hello @espdev and thanks for reporting. Your bug is related to #527. Wait until 2.12.1 is released (approximately today at evening UTC), then update.
Other possilble solution is to upgrade to git version of aiogram (`pip install -U 'git+https://github.com/aiogram/aiogram.git@dev-2.x'`) or downgrade to 2.11.2

**Comment by espdev** [comment]
@evgfilim1 Thank you for your quick reply! I will wait for the update.

**Comment by evgfilim1** [comment]
@espdev resolved, check it out

**Comment by espdev** [comment]
@evgfilim1, it works fine in `v2.12.1`. Thanks!
