### ISSUE TITLE
Incorrect work of ReplyKeyboardMarkup

### ISSUE THREAD

**Issue by totchka** [aiogram/aiogram#543]
Using aiogram.types.reply_keyboard.ReplyKeyboardMarkup messages in groups are sent as aiogram.types.force_reply.ForceReply

**Comment by evgfilim1** [comment]
Hello, @totchka. Can you describe your issue in detail?

**Comment by evgfilim1** [comment]
Closing as inactive. Feel free to comment here if you have more details to add.
