### ISSUE TITLE
I18nMiddleware.get_user_locale() cant get user for some actions (Poll closing)

### ISSUE THREAD

**Issue by darksidecat** [aiogram/aiogram#544]
When user closing Poll we get update without information that can give us current User object, so we cant get user.locale

```python:
async def get_user_locale(self, action: str, args: Tuple[Any]) -> str:
    user: types.User = types.User.get_current()
    locale: Locale = user.locale <--- raised exception here "NoneType" object 
                                      has no attribute 'locale'
```

how it can be fixed:
* adding check for this `pre_process_poll` action to I18nMiddleware.trigger()
`and  'poll' not in action`

maybe need investigation for other actions

aiogram 2.12.1
python 3.9.2
Manjaro 21.0

**Comment by darksidecat** [comment]
> `and 'poll' not in action` 

poll_answer action may be affected too, so need other check

**Comment by Olegt0rr** [comment]
> * adding check for this `pre_process_poll` action to I18nMiddleware.trigger()
>   `and  'poll' not in action`

There're may be some Update types without User object.
We shouldn't add it every time to exception cases.
It's just a typing check bug. User is Optional. 
So we need to check User is not None first (before ask any attributes).
