### ISSUE TITLE
'args' attribute of 'Command.CommandObj' seems not working

### ISSUE THREAD

**Issue by y-young** [aiogram/aiogram#556]
## Context

* Operating System: Windows 10
* Python Version: 3.8.1
* aiogram version: 2.12.1
* aiohttp version: 3.7.3
* uvloop version (if installed): 

## Expected Behavior

`command.args` returns arguments of command

## Current Behavior

`command.args` returns `None`

## Failure Information (for bugs)

It seems the `args` attribute is not working.

Digging into `dispatcher/filters/builtin.py`, I found nothing about setting this attribute, but after adding `args = text.split()[1]` and pass it to the construtor of `CommandObj`, it seems to work.

I wonder if this is the intended behavior or am I getting it wrong?

I would be glad to open a PR if it's a mistake :)

### Steps to Reproduce

```python
@dp.message_handler(commands=['test'])
async def test(message: Message, command: Command.CommandObj):
    print(command, command.args)
```

Test command: `/test abc`

### Failure Logs

Output: `Command.CommandObj(prefix='/', command='test', mention='') None`

**Comment by darksidecat** [comment]
> ```args = text.split()[1]```
>
This can raise IndexError exception when the command has no arguments. Also a command can have multiple arguments, so it makes sense to use a slice to handle such cases.
```args = text.split()[1:]```

**Comment by y-young** [comment]
> > `args = text.split()[1]`
> 
> This can raise IndexError exception when the command has no arguments. Also a command can have multiple arguments, so it makes sense to use a slice to handle such cases.
> `args = text.split()[1:]`

Yes that's a mistake.
So is this a bug or an intended behavior?

**Comment by darksidecat** [comment]
> So is this a bug or an intended behavior?

Looks like a bug. I think you can be free to make pull request.
@evgfilim1 WDYT?
