### ISSUE TITLE
New exceptions

### ISSUE THREAD

**Issue by Olegt0rr** [aiogram/aiogram#559]
### New exceptions

- BadRequest: Have no rights to send a message
- BadRequest: Group chat was deactivated
- BadRequest: Channel_private
- BadRequest: Have no rights to send a message
- Unauthorized: Forbidden: bot is not a member of the supergroup chat
- Unauthorized: Forbidden: bot is not a member of the group chat
- Unauthorized: Forbidden: chat_write_forbidden

### Task
Wrap this exceptions

**Comment by darksidecat** [comment]
Some additional information:

It seems that "BadRequest: Group chat was deactivated" is change the exception message  in an existing exception
[GroupDeactivated](https://github.com/aiogram/aiogram/blob/79c59b34f9141427d221842662dcef2eb90a558f/aiogram/utils/exceptions.py#L370)
```python:
class GroupDeactivated(BadRequest):
    match = 'group is deactivated'
```

There also seems to be another one new exception:

- Unauthorized: Forbidden: bot is not a member of the channel chat
[found here](https://github.com/tdlib/telegram-bot-api/blob/bf371b21b97c4c8d0b2e2646db05c654cb05480e/telegram-bot-api/Client.cpp#L3677)

**Comment by kamikazebr** [comment]
I think I can help with that, but i need some more information about where find the references of erros

https://core.telegram.org/api/errors

I tried there, and compared with the code https://github.com/aiogram/aiogram/blob/79c59b34f9141427d221842662dcef2eb90a558f/aiogram/utils/exceptions.py#L370

And not see matching.

**Comment by evgfilim1** [comment]
> And not see matching.

Yes, that's because errors you provided are from MTProto API, not Bot API.
If you want to help, you can read [Bot API sources](https://github.com/tdlib/telegram-bot-api), find errors there and fix/add them in aiogram.
