### ISSUE TITLE
aiogram and aiomysql 

### ISSUE THREAD

**Issue by AnatoliiA** [aiogram/aiogram#567]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: ubuntu
* Python Version:  3.7 
* aiogram version: 2.11.2
* aiohttp version: no 
* uvloop version (if installed):  no

## Expected Behavior

I expected getting a data from the mysql base used aiomysql
im async way for aiogram bot:

import asyncio, aiomysql
async def execute(loop, sttr) :
    connection(*param)
    cur = await conn.cursor()
    await cur.execute(sttr)
    result = await cur.fetchone()
    conn.close()

// handler catch update
@dp.message_handler(state=docregistration.name)
async def enter_name(message: types.Message, state: FSMContext):
        task = loop.create_task(execute_one(sttr))
        p = loop.run_until_complete(task)
        loop.close()
## Current Behavior
raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
<b>Because function enter_name() finished before complete event loop even though sleep()<b>

<H1><i>Any suggestion when I wrong</i></H1>

**Comment by Olegt0rr** [comment]
It's not relevant to aiogram at all.

Please, use asyncio docs to learn how to use task properly, or ask stackoverflow for that case.

Hints:
You shouldn't use loop directly.
Use await to await task.
Don't create/close connection on every update.
