### ISSUE TITLE
message handler not firing for a message containing media

### ISSUE THREAD

**Issue by DavMrc** [aiogram/aiogram#570]
## Context

* Operating System: Windows 10
* Python Version: 3.8.5
* aiogram version: 2.11.2

I am encountering an issue in the simplest callback: it does activate when the message is text only, but fails whenever any media is attached. This includes photos, videos, audios, stickers and GIFs, with or without caption.

I hope I'm not missing out on something.

```python
import aiogram


class TelegramBot(object):
    def __init__(self):
        self.bot = aiogram.Bot(token="TOKEN")
        self.dispatcher = aiogram.Dispatcher(bot=self.bot)
        self.dispatcher.register_message_handler(self.on_msg,)

    async def on_msg(self, msg: aiogram.types.Message):
        print("Message received in telegram")
```

## Expected Behavior
The callback is fired for every type of message.

## Current Behavior
The callback is fired only for text messages.

**Comment by darksidecat** [comment]
This is expected behavior.
https://github.com/aiogram/aiogram/blob/cce29ba532b4956557dead60edf14e5d0e5340e0/aiogram/dispatcher/filters/builtin.py#L472

The standard filter only works on text messages. If you need to work with all types use this
```content_types=types.ContentType.ANY```

**Comment by DavMrc** [comment]
I knew I was missing out on something, sorry for bothering and thanks for the answer!
