### ISSUE TITLE
on_shutdown not working on pycharm windows

### ISSUE THREAD

**Issue by BeastImran** [aiogram/aiogram#582]
## on_shutdown method not working while using pycharm on windows 10

on_shutdown method executes and exits with a sweet Goodbye message when done through shell (cmd, PowerShell and Linux terminal) and also works fine when using pycharm on ubuntu (mine 20.04) 

but when using pycharm in windows 10 (mine home), the on_shutdown method doesn't executes and there is no Goodbye message also.

* Operating System: Windows 10
* Python Version: 3.9, 3.8
* aiogram version: 2.13, 2.12.1 (problem on both versions as I tested)
* aiohttp version: 
* uvloop version (if installed): 

## Expected Behavior

Should execute on_shutdown when exiting.

## Current Behavior

Not working when using pycharm in windows 10

### Steps to Reproduce

(using pycharm in windows 10)

1. Configure on_shutdown method
2. Run the bot/app in pycharm windows 10 using ctrl+f11 or run button
3. Stop the bot in pycharm using ctrl+f2 or stop button beside run window/pane.

Should be able to see the problem.

**Comment by Olegt0rr** [comment]
It's not an aiogram bug.

```python
import time

try:
    while True:
        print(time.time())
        time.sleep(1)
except (KeyboardInterrupt, SystemExit) as e:
    print(f"{type(e).__name__}: {e}")
finally:
    print("Bye-bye")
```

With pycharm (start / stop):
```
1620809932.698393
1620809933.699169
1620809934.699206
1620809935.6995654

Process finished with exit code -1
```

With python (run / Ctrl+C):
```
1620809771.6497056
1620809772.650166
1620809773.6504912
KeyboardInterrupt:
Bye-bye
```

**Comment by BeastImran** [comment]
Okay 🙂, thank you for your comment.

**Comment by evgfilim1** [comment]
> Unfortunately, i _didn't_ find relatable issue on jetbrains tracker.

You could've opened a new issue :thinking:

**Comment by BeastImran** [comment]
> > Unfortunately, i _didn't_ find relatable issue on jetbrains tracker.
> 
> You could've opened a new issue

Will open for sure and will share the link here ASAP when i do it.  Actually i was going through existing ones so i wouldn't create any duplicates.

**Comment by Olegt0rr** [comment]
@BeastImran, don't worry! JetBrains managers will link all duplicated issues

**Comment by BeastImran** [comment]
posted this issue on jetbrains site

https://youtrack.jetbrains.com/issue/PY-48937

**Comment by Olegt0rr** [comment]
## Workaround
You can enable `kill.windows.processes.softly` registry option and restart IDE.

To access registry, go to Help | Find Action... and search for "Registry..."
