### ISSUE TITLE
my_chat_member shouldn't be excluded from default allowed_updates

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#588]
## Context

According to the [Bot API docs](https://core.telegram.org/bots/api#update), `my_chat_member` update is turned **on** by default, unlike just `chat_member`. 
However, aiogram [excludes both updates](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/types/update.py#L81) from "default" list.

Suggested fix: keep only `chat_member` in excluded

* aiogram version: 2.13

**Comment by Olegt0rr** [comment]
@JrooTJunior 

Docs: `Specify an empty list to receive all update types except chat_member (default)`
Why don't we use `[]` as default?
