### ISSUE TITLE
"date" field in Message object is returned incorrectly

### ISSUE THREAD

**Issue by MasterGroosha** [aiogram/aiogram#59]
As seen in [documentation](https://core.telegram.org/bots/api#message):
`date | Integer | Date the message was sent in Unix time`

Aiogram returns formatted datetime instead which is incorrect (expected integer as seen in docs) and makes harder to port code from other libraries.

Test case:
```python
@dp.message_handler()
async def show_datetime(message: types.Message):
    print(message.date)
    return
```
Expected output:
`>>> 1532863711`

Got output:
`>>> 2018-07-29 11:28:31`

**Comment by MasterGroosha** [comment]
P.S. Since you're making a wrapper for Telegram Bot API, please, don't put your fantasies to the code.
According to API, Message->Date is **INTEGER**, not a **STRING**. So please, make it INTEGER, leaving convertion to string as a separate method (aka helper method for this library).

**Comment by surik00** [comment]
This attribute returns not string but a `datetime.datetime` object :)
It's not about being readable, it's about doing less conversions in **your** code
in my opinion it's more convenient when if in PYTHON you see DATE field and it returns a datetime object, which you can use.
if you want a unix timestamp, just call date.timestamp

It's also stated in API that all methods are `lowerCamelCase`, but in aiogram they all are `snake_case` because it's Python-way

**Comment by MasterGroosha** [comment]
> It's also stated in API that all methods are lowerCamelCase, but in aiogram they all are snake_case because it's Python-way

Python has its own language desing principles, also for camelcase and so on. But changing integer to string (one base type to another base type) is unacceptable for any programming language. You sarcasm is irrelevant.

**Comment by surik00** [comment]
It's not a string, you were just printing it
Look for `class datetime.datetime` in https://docs.python.org/3/library/datetime.html

Here's an example

```python
>>> from datetime import datetime
>>> now = datetime.now()
>>> now
datetime.datetime(2018, 7, 29, 13, 15, 17, 258696)
>>> print(now)
2018-07-29 13:15:17.258696
>>> now.timestamp
<built-in method timestamp of datetime.datetime object at 0x1075a45a8>
>>> now.timestamp()
1532859317.258696
```

(You can copy-paste this snippet)
```
from datetime import datetime
now = datetime.now()
now
print(now)
now.timestamp
now.timestamp()
```

**Comment by MasterGroosha** [comment]
You still cannot pass `Message.date` to `restrict_chat_member` and other similar methods. A good implementation would leave Message.date as integer and everything will work fine.

**Comment by surik00** [comment]
Yeah, this is an issue, that @JrooTJunior has to fix (or anyone else)
+ `forward_date: base.Integer = fields.Field()`

**Comment by JrooTJunior** [comment]
> You still cannot pass Message.date to restrict_chat_member and other similar methods.

@MasterGroosha, Why not? You can use datetime and/or timedelta for `until_date` argument and it will be [automatically converted](https://github.com/aiogram/aiogram/blob/master/aiogram/utils/payload.py#L53-L57) to unixtime.

Example:
```python3
await bot.restrict_chat_member(
    message.chat.id, message.from_user.id, 
    until_date=message.date + datetime.timedelta(days=7), ...)
```

**Comment by MasterGroosha** [comment]
@JrooTJunior 
Of course, I can write any number of "helper" methods. The thing is: you're making a simple API complex **just because you want to**. But this is not your project (originally). All you had to do was to 
1) Replicate Bot API methods "as is"
2) Do whatever you want since you're creator of library.

I appreciate your "2)", but you've completely failed "1)". I see you (and community behind you) don't see any problems here and don't even feel guilty, so I'll just close the issue. Good luck making simple things harder because of your fantasies.
