### ISSUE TITLE
How to forward a user's message as it is done in pyrogram?

### ISSUE THREAD

**Issue by ItsIm** [aiogram/aiogram#595]
Hello everyone.
Tormented by the problem: I can not forward the user's message through the bot in its original form. I.e., it is forwarded as if the user wrote it himself.

![photo_2021-06-03_07-53-18](https://user-images.githubusercontent.com/58345111/120588962-c828cc00-c440-11eb-936b-7ea89149b425.jpg)

And this is what forwarding looks like if you use the aiogram forward method. **Does anyone know how to do this?**

![photo_2021-06-03_07-53-13](https://user-images.githubusercontent.com/58345111/120589098-03c39600-c441-11eb-97ab-1e7dabbf718d.jpg)

**Comment by evgfilim1** [comment]
Hi @ItsIm! 

I don't think it's called "forwarding" in Pyrogram. Forwarding is when the message has "forwarded from" field in its body, like aiogram (and official clients) does:
![image](https://user-images.githubusercontent.com/17182159/120604244-49df2080-c466-11eb-9f37-829f750e0d64.png)

I guess you meant "sending as copy". Aiogram has this feature. Use [`message.send_copy`](https://github.com/aiogram/aiogram/blob/5f6e5a646b9a86bb1146244548a0d688bfaf4867/aiogram/types/message.py#L2833) or [`bot.send_copy`](https://github.com/aiogram/aiogram/blob/5f6e5a646b9a86bb1146244548a0d688bfaf4867/aiogram/bot/bot.py#L341) ([Bot API docs](https://core.telegram.org/bots/api/#sendcopy)).

If you have further questions, feel free to ask here or continue in one of our communities in Telegram: [@aiogram](https://t.me/aiogram) and/or [@aiogram_ru](https://t.me/aiogram_ru)

**Comment by ItsIm** [comment]
thank you very much!

> Привет, @ItsIm !
> 
> Я не думаю, что в Pyrogram это называется «пересылка». Пересылка - это когда сообщение имеет поле "отправлено от" в своем теле, как это делает айограмма (и официальные клиенты):
> ![изображение](https://user-images.githubusercontent.com/17182159/120604244-49df2080-c466-11eb-9f37-829f750e0d64.png)
> 
> Я полагаю, вы имели в виду «отправить как копию». У айограммы есть такая особенность. Используйте [`message.send_copy`](https://github.com/aiogram/aiogram/blob/5f6e5a646b9a86bb1146244548a0d688bfaf4867/aiogram/types/message.py#L2833)или [`bot.send_copy`](https://github.com/aiogram/aiogram/blob/5f6e5a646b9a86bb1146244548a0d688bfaf4867/aiogram/bot/bot.py#L341)( [документы Bot API](https://core.telegram.org/bots/api/#sendcopy) ). Обратите внимание, что эти два способа немного отличаются.
> 
> Если у вас есть дополнительные вопросы, задавайте их здесь или продолжайте в одном из наших сообществ в Telegram: [@aiogram](https://t.me/aiogram) и / или [@aiogram_ru.](https://t.me/aiogram_ru)

**Comment by evgfilim1** [comment]
> Can you tell me how to copy it so that you can see who was originally the sender of the message?

I guess you want to forward message, right? Then use [`bot.forward_message`](https://github.com/aiogram/aiogram/blob/5f6e5a646b9a86bb1146244548a0d688bfaf4867/aiogram/bot/bot.py#L317) for this.

**Comment by evgfilim1** [comment]
@ItsIm, is your question resolved?

**Comment by evgfilim1** [comment]
> Click the arrow to go to the user profile.

That arrow is a feature only for "Saved messages" and "Replies", which are available only for users, not bots.
