### ISSUE TITLE
`commands` in `@dp.message_handler` doesn't work with photos

### ISSUE THREAD

**Issue by bpqq** [aiogram/aiogram#604]
## Dispatcher -> message_handler -> command with photo

My setup

* Operating System: Windows 10
* Python Version: Python 3.7.3
* aiogram version: aiogram==2.13

## Expected Behavior

Bot should receive and process command with attached photo.

## Current Behavior

I can't send command and photo together.

## Description of failure 

`@dp.message_handler(commands=['mycommand'], content_types=[types.ContentType.TEXT, types.ContentType.PHOTO])`
`async def command_watermark(message: types.Message):`
`    # If you send a command, then the code is reproduced here `
`    # If you send a command with a photo, then the code is ignored here. `

## Help please
Can I do what I want or is it not possible?
Please tell me what is the error or another method of solution.

**Comment by kamikazebr** [comment]
@bpqq You tried only like below?

`@dp.message_handler(commands=['mycommand'], content_types=[types.ContentType.PHOTO])`

And you can try log it to console and check what you got.

After that method `command_watermark` create new one

```
@dp.message_handler()
async def print_if_none_is_get(message: types.Message):
    logging.log(f"Message: {message}")
```

Something like that, maybe you need change your logging to print ou pprint ou ppretty.

**Comment by evgfilim1** [comment]
Hello, @bpqq!

By default, [commands filter](https://github.com/aiogram/aiogram/blob/c42b7e4b0d72503ea1b63a64ff9e0159bc4b68ae/aiogram/dispatcher/filters/builtin.py#L28-L68) check whether the message is text message. To make your filter work, pass `commands_ignore_captions=False` to your handler registration, like this:
```python
@dp.message_handler(commands=['mycommand'], commands_ignore_caption=False, content_types=[types.ContentType.TEXT, types.ContentType.PHOTO])
async def command_watermark(message: types.Message):
    ...
```

If you have further questions, feel free to ask here or join our community in Telegram: [@aiogram](https://t.me/aiogram)

**Comment by evgfilim1** [comment]
For maintainers and issue author: I've renamed issue to make it more searchable later

**Comment by bpqq** [comment]
> 
> 
> Hello, @bpqq!
> 
> By default, [commands filter](https://github.com/aiogram/aiogram/blob/c42b7e4b0d72503ea1b63a64ff9e0159bc4b68ae/aiogram/dispatcher/filters/builtin.py#L28-L68) check whether the message is text message. To make your filter work, pass `commands_ignore_captions=False` to your handler registration, like this:
> 
> ```python
> @dp.message_handler(commands=['mycommand'], commands_ignore_caption=False, content_types=[types.ContentType.TEXT, types.ContentType.PHOTO])
> async def command_watermark(message: types.Message):
>     ...
> ```
> 
> If you have further questions, feel free to ask here or join our community in Telegram: [@aiogram](https://t.me/aiogram)

Thanks, this option `commands_ignore_caption=False` solves my problem.
But when I call the `message.text`, I get "None".
I can only get markdown text from `message.md_text`.
What should I do to get simple text, not markdown text?

**Comment by Olegt0rr** [comment]
> But when I call the `message.text`, I get "None".

You should use `caption` field instead `text` for all content types != ContentType.TEXT.

**Comment by bpqq** [comment]
> 
> 
> > But when I call the `message.text`, I get "None".
> 
> You should use `caption` field instead of `text` for all content types != ContentType.TEXT.

Ok. Thanks.
