### ISSUE TITLE
ChatTypeFilter check always False

### ISSUE THREAD

**Issue by kamikazebr** [aiogram/aiogram#607]
# ChatTypeFilter check always False
---
## My setup
Operating System: Ubuntu 20.04
Python Version: Python 3.8.5
aiogram version: ==2.13

## Expected Behavior
Using ChatType.PRIVATE should call the function/command

## Current Behavior
Nothing is called, because check return False, more detail below

## More Info
I tried many things and the end i give up and use old helper will be deprecated.

That line always is False.

`obj.type = "private"`

but the set have weird structure and never match.

[Code with problem](https://github.com/aiogram/aiogram/blob/d5a4c0c4afc6f03b9de19f7f68f852c9188cf072/aiogram/dispatcher/filters/builtin.py#L741
)
I dont have the code anymore, but i tested like the examples with:
`
chat_type=[ChatTypeFilter(ChatType.PRIVATE)]`

too with

`chat_type=[ChatTypeFilter("private")]`

In debug too see init run more one time, same using some one and one decorator.

**Comment by evgfilim1** [comment]
Hello, @kamikazebr!
Check this example, it should work: https://github.com/aiogram/aiogram/blob/dev-2.x/examples/chat_type_filter.py

**Comment by kamikazebr** [comment]
> Hello, @kamikazebr!
> Check this example, it should work: https://github.com/aiogram/aiogram/blob/dev-2.x/examples/chat_type_filter.py

Damn! I was using the ChatTypeFilter.PRIVATE instead of ChatType.PRIVATE

Sorry for that, and thank very much @evgfilim1
