### ISSUE TITLE
Can't save a photo from BOT

### ISSUE THREAD

**Issue by lbenvenuto91** [aiogram/aiogram#608]
## Context

* Operating System: Centos 7
* Python Version: 3.8

I'm trying to make a command for my bot that saves some photos to a server folder. I upload the photos to the chat bot using the integrated telegram camera.
I had a look at the documentation, https://docs.aiogram.dev/en/dev-3.x/api/methods/get_file.html , and I wrote the following code lines:

@dp.message_handler(commands='foto')
async def save_photo(message: types.Message):
    """
    This handler will be called when user sends `/foto` command
    """

    file_id = message.document.file_id

    file = await bot.get_file(file_id)
    file_path = file.file_path

    await bot.download_file(file_path, "test.jpg")

When I execute the comand nothing happens. Also executing the code in debug mode I don't see any trace of the message with the photo.
Does anyone have the same problems or can anyone help me?

Thank you very much.

**Comment by lbenvenuto91** [comment]
My bad, I wasn't writing a correct code.
This code works:
@dp.message_handler(content_types=types.ContentTypes.PHOTO)
async def bot_echo_all(message: types.Message):

    pid= await bot.get_file(message.photo[-1].file_id)

    photo_name='{}_{}'.format(message.chat.id,datetime.now())

    destination='{}/foto/{}.jpg'.format(os.path.dirname(os.path.realpath(__file__)),photo_name)
    await bot.download_file(pid.file_path,destination)

**Comment by Olegt0rr** [comment]
@lbenvenuto91 why don't you use a shortcut?

```python
photo = message.photo[-1]
...
await photo.download(...)
```

**Comment by lbenvenuto91** [comment]
Yeah you are right. 
Basically 'cos I'm not such an expert programmer.
Does this way have some advantages?

**Comment by evgfilim1** [comment]
> Does this way have some advantages?

Just code readability
