### ISSUE TITLE
sometimes get None in message.reply_to_message, when trying to reply a message of bot

### ISSUE THREAD

**Issue by tednaaa** [aiogram/aiogram#616]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: windows 10
* Python Version: 3.8.5
* aiogram version: 2.12.1
* aiohttp version: 3.7.4.post0
* uvloop version (if installed): 

## Expected Behavior

Please describe the behavior you are expecting

My bot is admin in group, and when i write command `/kick` and `reply` to message of user/bot, my bot kick them from group.
But sometimes i get `None` in `message.reply_to_message` when trying to reply a message of another bot (for example `True Mafia` bot).

With users all works fine.

**Comment by MasterGroosha** [comment]
Do you have a 100% reproducible test case?

**Comment by JrooTJunior** [comment]
Inactive issue
