### ISSUE TITLE
thumb parameter in answer_audio (sendAudio) method doesn't work

### ISSUE THREAD

**Issue by jedipython** [aiogram/aiogram#627]
Hello, i tried to start send my audio file with  thumbnail, but it is unlucky.

I used: 
`thumb = 'AgACAgIAAxkBAAICFGDp2lwaZj6K91zHR5ARbLd8KtWAAAIoszEbVpNRS962Z3cgJvOfAQADAgADbQADIAQ'
` or 
`thumb = InputFile(path_or_bytesio='tgbot/handlers/thumb.jpg')`
In `await callback.message.answer_audio(audio=audio, thumb=thumb)` or `await callback.bot.send_audio(audio=audio, chat_id=chat_id, thumb=thumb)`
Thumb in my audio didnt change. (https://prnt.sc/1a0zo8d) 

Is it my problem or the problem from Aiogram? Thanks

**Comment by Olegt0rr** [comment]
@jedipython,
It seems that you need to read the API documentation closely.
First of all thumb can't be passed as file_id.
Second - check your thumb properties fit the api technical requirements

**Comment by jedipython** [comment]
> @jedipython,
> It seems that you need to read the API documentation closely.
> First of all thumb can't be passed as file_id.
> Second - check your thumb properties fit the api technical requirements

Hi, yes, i  know.  thanks, InputFile didnt get file_id, it get nothing. Nothing happens, there are not even any errors when I pass the InputFile. If i use InputFile fron aiogram.types.base, so have error **TypeError: 'TypeVar' object is not callable**

**Comment by Olegt0rr** [comment]
Please, provide the code snippet to reproduce an issue with an error described above (object is not callable)

**Comment by jedipython** [comment]
> Please, provide the code snippet to reproduce an issue with an error described above (object is not callable)

`async def show_read_audio(callback: CallbackQuery, category, item_id):
    db_session = callback.message.bot.get("db")
    markup = read_audio_book_keyboard(category, item_id)
    item = await Book.get_book(db_session, item_id)
    chat_id = callback.from_user.id
    audio = item.audio
    thumb = InputFile(path_or_bytesio='tgbot/handlers/thumb.jpg')
    await callback.message.delete()
    await callback.message.answer_audio(audio=audio, caption=f'My description for audio"',
                                  title='MyTitle', thumb=thumb, reply_markup=markup)`
