### ISSUE TITLE
ValueError: <Token var=<ContextVar name='current_handler' at 0x7fe4a298a590> at 0x7fe4a0a69b80> was created in a different Context

### ISSUE THREAD

**Issue by lintyflent** [aiogram/aiogram#628]
## Context
 * Manjaro Linux Gnome Testing branch 
 * Python 3.9.6
 * aiogram 2.11.2
 * aiohttp 3.7.4.post0  

I use Aiomysql in conjunction with Aiogram. Experimentally, I found out that the await con.commit() line causes the error shown at the end. But why? But how is this error related to aiogram and why is there no mention of project files?|
P.s: If I noticed correctly, the error occurs only when UPDATE and possibly INSERT.

```
async def __query(self, *args, **kwargs):
    con = await aiomysql.connect(
            host=self.__db_host,
            user=self.__db_login,
            password=self.__db_pass,
            db=self.__db_name,
    )
    cur = await con.cursor()
    await cur.execute(*args, **kwargs)
    res = await cur.fetchall()
    await con.commit()
    await cur.close()
```
OR
```
...
    async def __query(self, *args, **kwargs):
        pool = await aiomysql.create_pool(
            host=self.__db_host,
            port=self.__port,
            user=self.__db_login,
            password=self.__db_pass,
            db=self.__db_name
        )
        res = None
        async with pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute(*args, **kwargs)
                res = await cur.fetchall()
                await conn.commit()
        pool.close()
        await pool.wait_closed()
        return res
 ...
    async def execute(self, *args, **kwargs):
        return await self.__query(*args, **kwargs)
...
    async def func(self, args...):
        ...
        await db.execute(f'UPDATE table_name SET column_name = {new_data} WHERE user_id = "{self.user_id}"')
        ...
```

### Steps to Reproduce

Any database query via aiomysql. On commit.

### Failure Logs

The error that occurs:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/user/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 127, in notify
    current_handler.reset(ctx_token)
ValueError: <Token var=<ContextVar name='current_handler' at 0x7f7ab7a7df90> at 0x7f7ab5caa800> was created in a different Context
Exception ignored in: <coroutine object Handler.notify at 0x7f7ab5c42140>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 127, in notify
    current_handler.reset(ctx_token)
ValueError: <Token var=<ContextVar name='current_handler' at 0x7f7ab7a7df90> at 0x7f7ab5c7bc40> was created in a different Context
    return res
```

**Comment by evgfilim1** [comment]
Hello, @lintyflent. Can you provide us more information by filling in issue template below?

---

```markdown

## Context
Describe your error in details here.

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Python Version: 
* aiogram version: 
* aiohttp version: 
* uvloop version (if installed): 

## Expected Behavior

Please describe the behavior you are expecting.

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

```

**Comment by lintyflent** [comment]
## Context
 * Manjaro Linux Gnome Testing branch 
 * Python 3.9.6
 * aiogram 2.11.2
 * aiohttp 3.7.4.post0  

I use Aiomysql in conjunction with Aiogram. Experimentally, I found out that the await con.commit() line causes the error shown at the end. But why? But how is this error related to aiogram and why is there no mention of project files?

```
async def __query(self, *args, **kwargs):
    con = await aiomysql.connect(
            host=self.__db_host,
            user=self.__db_login,
            password=self.__db_pass,
            db=self.__db_name,
    )
    cur = await con.cursor()
    await cur.execute(*args, **kwargs)
    res = await cur.fetchall()
    await con.commit()
    await cur.close()
```

### Steps to Reproduce

Any database query via aiomysql. On commit.

### Failure Logs

The error that occurs:

```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 117, in notify
    response = await handler_obj.handler(*args, **partial_data)
GeneratorExit

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 273, in process_update
    return await self.callback_query_handlers.notify(update.callback_query)
  File "/home/user/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 127, in notify
    current_handler.reset(ctx_token)
ValueError: <Token var=<ContextVar name='current_handler' at 0x7f7ab7a7df90> at 0x7f7ab5caa800> was created in a different Context
Exception ignored in: <coroutine object Handler.notify at 0x7f7ab5c42140>
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/aiogram/dispatcher/handler.py", line 127, in notify
    current_handler.reset(ctx_token)
ValueError: <Token var=<ContextVar name='current_handler' at 0x7f7ab7a7df90> at 0x7f7ab5c7bc40> was created in a different Context
    return res
```

**Comment by lintyflent** [comment]
UPDATE:
 If I noticed correctly, the error occurs only when UPDATE and possibly INSERT.

OR
...
    async def __query(self, *args, **kwargs):
        pool = await aiomysql.create_pool(
            host=self.__db_host,
            port=self.__port,
            user=self.__db_login,
            password=self.__db_pass,
            db=self.__db_name
        )
        res = None
        async with pool.acquire() as conn:
            async with conn.cursor() as cur:
                await cur.execute(*args, **kwargs)
                res = await cur.fetchall()
                await conn.commit()
        pool.close()
        await pool.wait_closed()
        return res
 ...
    async def execute(self, *args, **kwargs):
        return await self.__query(*args, **kwargs)
...
    async def func(self, args...):
        ...
        await db.execute(f'UPDATE table_name SET column_name = {new_data} WHERE user_id = "{self.user_id}"')
        ...
```

**Comment by maxvolkoff** [comment]
> ## UPDATE:
> If I noticed correctly, the error occurs only when UPDATE and possibly INSERT.
> 
> Another code example This also causes this error
> 
> ```
> ...
>     async def __query(self, *args, **kwargs):
>         pool = await aiomysql.create_pool(
>             host=self.__db_host,
>             port=self.__port,
>             user=self.__db_login,
>             password=self.__db_pass,
>             db=self.__db_name
>         )
>         res = None
>         async with pool.acquire() as conn:
>             async with conn.cursor() as cur:
>                 await cur.execute(*args, **kwargs)
>                 res = await cur.fetchall()
>                 await conn.commit()
>         pool.close()
>         await pool.wait_closed()
>         return res
>  ...
>     async def execute(self, *args, **kwargs):
>         return await self.__query(*args, **kwargs)
> ...
>     async def func(self, args...):
>         ...
>         await db.execute(f'UPDATE table_name SET column_name = {new_data} WHERE user_id = "{self.user_id}"')
>         ...
> ```

Hi! I have the same problem( Did you resolve the problem?

**Comment by JrooTJunior** [comment]
Stale issue.

**Comment by Kylmakalle** [comment]
While I accept that this issue is not easy to reproduce and the main focus is on v3 now, I'm interested in the solution.
