### ISSUE TITLE
Bug: member.can_send_messages store None instead True

### ISSUE THREAD

**Issue by ilyas-kalandar** [aiogram/aiogram#635]
* Operating System: Microsoft Windows 10 PRO 20H2
* Python Version:  3.9.5
* aiogram version: 2.13
* aiohttp version: 3.7.4
* uvloop version (if installed): Not installed

## I tried to ban member if he can't send messages, and I used following code <br>
![image](https://user-images.githubusercontent.com/56587546/125965231-20e05361-828b-4ab3-bc7a-5b373a00b7d2.png)

## Output from pycharm console:
![image](https://user-images.githubusercontent.com/56587546/125963850-569934bb-0a24-428a-9500-90caa8c8c692.png)

**Comment by github-localhost** [comment]
От сука. Юзает винду 10, но скрин с закосом под мак. Е-мае..

**Comment by Olegt0rr** [comment]
@ilyas-kalandar, 

Update your `aiogram` version to `2.14.3` and try again.

P.S.: Please use code in ` ``` `brackets instead of screenshots. Developers are not happy with retyping.

**Comment by ilyas-kalandar** [comment]
Thanks.
