### ISSUE TITLE
Conversation handling

### ISSUE THREAD

**Issue by SNvMK** [aiogram/aiogram#693]
Hi, i wanna to create a bot that will show homework. I want it to be like so:
me: /hw@snvmk_bot
bot: Enter date
me: 19.09.2021
bot: Enter lesson
me: Math
bot: exercises 90, 91, 92

i have something on Telegraf.js, but i want it to be python, on aiogram, and i dont know how to handle conversation in aiogram. Is there anything for this?

**Comment by Olegt0rr** [comment]
Use this example: 
https://github.com/aiogram/aiogram/blob/dev-2.x/examples/finite_state_machine_example.py

**Comment by SNvMK** [comment]
@Olegt0rr thanks, this helped
