### ISSUE TITLE
My error is AttributeError. Please help

### ISSUE THREAD

**Issue by akbarjon-dev** [aiogram/aiogram#697]
When I want to clear InlineKeyboardMarkup() with clear(), this error shown.
AttributeError: 'InlineKeyboardMarkup' object has no attribute 'clear'.
Please, help.

**Comment by JrooTJunior** [comment]
What do you want to do with this method? Why is needed?

**Comment by JrooTJunior** [comment]
@akbarjon-dev, FYI

**Comment by Olegt0rr** [comment]
@akbarjon-dev, just create a new InlineKeyboardMarkup object :)
