### ISSUE TITLE
Socks5Addr doesnt work.

### ISSUE THREAD

**Issue by kolayv** [aiogram/aiogram#71]
If im transfer to Bot proxy argument Socks5Addr, script instantly crash.

**Comment by JrooTJunior** [comment]
What version of library do you use?

**Comment by JrooTJunior** [comment]
Will be fixed in 2.x (#51)

**Comment by heyyyoyy** [comment]
```python
from aiosocksy import Socks5Auth

bot = Bot(token=TOKEN, loop=loop, proxy='socks5://ip:port', proxy_auth=Socks5Auth(login, password))
```
@kolayv  it works for me

**Comment by JrooTJunior** [comment]
In `2.x` used [aiohttp_socks](https://github.com/romis2012/aiohttp-socks) instead of `aiosocksy`.
With this implementation you can use only string based addresses.
