### ISSUE TITLE
message.reply_audio неверное название аудиозаписи

### ISSUE THREAD

**Issue by Helow19274** [aiogram/aiogram#73]
```python
@dp.message_handler(regexp='^https:\/\/music.yandex.ru\/?a?l?b?u?m?\/?[0-9]+?\/track\/[0-9]+$')
async def music_handler(message: types.Message):
    url, title = await parse_url(message.text, loop)
    print(url)
    print(title)

    await message.reply_audio(audio=url, title=title)
```
Принт:
https://длинная_ссылка
Twenty One Pilots - Nico And The Niners

В Телеграме:
![default](https://user-images.githubusercontent.com/20171143/44949869-ff5a9080-ae42-11e8-9398-31fd31b249e4.png)
Похоже что title хоть и передаётся в reply_audio, но не используется.

UPD: bot.send_audio тоже пробовал, результат тот же.

**Comment by JrooTJunior** [comment]
Похоже, что поля `performer` и `title` игнорируются на стороне Bot API при отправке аудио по ссылке. Проверил отправляя по ссылке и файлом.

Код:
```python3
AUDIO_URL = 'http://muzmo.ru/get/music/20140507/muzmo_ru_Metallica_-_Metalica_Fuel_12710830.mp3?sid=3ip4uccps4mp3ljt2viipsqcep'
AUDIO_PATH = os.path.expanduser('~/Downloads/muzmo_ru_Metallica_-_Metalica_Fuel_12710830.mp3')

@dp.message_handler(commands=['audio1'])
async def cmd_audio1(message: types.Message):
    audio = types.InputFile(AUDIO_PATH)
    await message.reply_audio(audio, performer='Foo', title='Bar')


@dp.message_handler(commands=['audio2'])
async def cmd_audio2(message: types.Message):
    await message.reply_audio(AUDIO_URL, performer='Foo', title='Bar')
```

Результат:
![image](https://user-images.githubusercontent.com/6726423/44950205-97a84380-ae4a-11e8-964a-d2aba89a148c.png)

**Comment by Helow19274** [comment]
Спасибо!
