### ISSUE TITLE
Bot need admin rights to access super_group's messages

### ISSUE THREAD

**Issue by ArtemBernatskyy** [aiogram/aiogram#75]
In my case this was necessary, if this correct approach we need to mention this in docs.

**Comment by JrooTJunior** [comment]
What do you mean?

Maybe you need to disable privacy mode in [@BotFather](https://t.me/BotFather) (and re-add bot to the chat)? I think you need to read the docs of Telegram Bot API about [privacy mode](https://core.telegram.org/bots#privacy-mode).

**Comment by ArtemBernatskyy** [comment]
hm, i've disabled privacy but haven't re-aded bot
