### ISSUE TITLE
Send a message every minute

### ISSUE THREAD

**Issue by segremelnikov** [aiogram/aiogram#750]
```python
@dp.message_handler(content_types=['text'])
async def get_text_messages(msg: types.Message):
   if msg.text.lower() == 'привет':
       await msg.answer(f'Привет! {msg.from_user.first_name}')
       await bot.send_message(1889401542, "hi") 
       
   else:
       await msg.answer('Не понимаю, что это значит.')
       await bot.send_message(1889401542, "unknown")


async def send_time():
    await bot.send_message(1889401542, datetime.now())

async def scheduler():
    aioschedule.every().minute.do(send_time)
    while True:
        await aioschedule.run_pending()
        await asyncio.sleep(1)

async def on_startup(_):
    asyncio.create_task(scheduler())

if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=False, on_startup=on_startup)
```

Hello, can you please take a look at this code? I'm just started looking at bot development and "collected" this code from several sources
On Windows it works fine - bot answers to messages and sends time every minute
But on Ubuntu it answers only to first message and after this only sends time

I don't think there can be such bug in such popular lib so can you please tell what am I doing wrong and what's the reason of such strange behavior on Ubuntu?

UPD after deleting `await bot.send_message(1889401542, "hi"/"unknown")` all works fine on Ubuntu but what's the reason - seems there is a conflict that `send_message` is used in regular handler and in  `scheduler`? Why is this so?

**Comment by Olegt0rr** [comment]
It's not an `aiogram` issue.

1. It seems you're passing wrong type to `.send_message()`
2. Add logging and add a raised exception to your issue.
3. Don't use github as a solution platform for non-related issues. Use https://t.me/aiogram_ru or stackoverflow

**Comment by segremelnikov** [comment]
1. Oh, really -- but after fixing it all stays same -- correct working on Windows and only 1 answer to message on Ubuntu. Why is this so?
2. There aren't any exceptions raising, or I misunderstood you? (Can I use Russian here? Don't know English enough)
3. Posted this question on aiogram_ru at morning, but no one answered there..

**Comment by segremelnikov** [comment]
And, sorry, why are you sure it's not an aiogram issue? After fixing (`f"datetime.now()"`) all stays the same at Ubuntu but in code there aren't any suspicious, isn't it?

**Comment by segremelnikov** [comment]
Oh, after changing another parameter -- id from int to string ("1889401542") all works fine on Ubuntu. Can you please explain why is this so?

**Comment by segremelnikov** [comment]
Sorry again, seems it's been coincidence -- on second start at Ubuntu it works wrong how I've described in issue..

**Comment by segremelnikov** [comment]
прошу прощения, последнее на эту тему попробую спросить — вот как выглядит на стороне клиента эта "остановка" бота на Убунту — он отвечает (на картинке на "hrt"), потом перестает отвечать, а при каждом перезапуске (на скрине их два) снова отвечает на это "hrt", то есть оно не удаляется из очереди, или как это понять..
![e32e32](https://user-images.githubusercontent.com/92302887/141767112-fe32ac52-1993-4caf-85a6-ce3cc5b5cb0e.png)

**Comment by segremelnikov** [comment]
Какое-то время так выводил, сейчас уже минут 20 нормально; если у вас есть объяснение было бы очень интересно прочитать

**Comment by Olegt0rr** [comment]
Ещё раз повторю. Здесь не stackoverflow и не чатик для решения частных задач.
Если не ответили в чате - спросите ещё раз, или наймите разработчика на фрилансе
