### ISSUE TITLE
Callback handler doesn't work

### ISSUE THREAD

**Issue by komarp** [aiogram/aiogram#752]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: Ubuntu 20.14
* Python Version: 3.9.5
* aiogram version: 2.16
* aiohttp version: 3.8.1
* uvloop version (if installed): 0.16.0

## Expected Behavior

I have a task in my project(cycle), that notify me in telegram that particular event has happend. When an event has happend,
backend sends me message with InlineKeyboardMarkup, and if button was pressed, callback_handler should do some work.

## Current Behavior

Backend sends InlineKeyboardMarkup to bot, but when i press a button - nothing happens(Of course, i have registeged
callback_query_handler, but in another module(i suspect this is a problem)) 

### Code:

```py
// src/path/to/file.py
            ...
            if True:
                keyboard = await get_inline_event_keyboard()
                three_exclamation = ':heavy_exclamation_mark:' * 3
                emojized_three_exclamation = emoji.emojize(three_exclamation, use_aliases=True)

                await bot.send_message(
                    MY_TG_ID,
                    text='LOREM IPSUM DOLOR SER AMET',
                    reply_markup=keyboard
                )
```

```py
// src/path/to/another/file.py 

@dp.callback_query_handler(lambda c: c.data == 'text')
async def process_callback_text(call: CallbackQuery):
    await bot.answer_callback_query(call.id)
    await bot.send_message(call.from_user.id, text='HAM')


@dp.callback_query_handler(lambda c: c.data == 'text_1')
async def process_callback_text_1(call: CallbackQuery):
    await bot.answer_callback_query(call.id)
    await bot.send_message(call.from_user.id, text='SPAM')
```
```py
// src/path/to/keyboard.py

async def get_inline_event_keyboard():
    keyboard = InlineKeyboardMarkup(row_width=2)

    buttons = [
        InlineKeyboardButton(text=InlineEnumButtons.LOREM, callback_data='text'),
        InlineKeyboardButton(text=InlineEnumButtons.IPSUM, callback_data='text_1')
    ]

    keyboard.row(*buttons)
    return keyboard
```

What's problem?

**Comment by Olegt0rr** [comment]
1. Send full reproducible code. Nobody wants to build own app to help you.
1. Check states, if you're using FSM. 
1. Use [logging middleware](https://github.com/aiogram/aiogram/blob/dev-2.x/aiogram/contrib/middlewares/logging.py#L10) to debug your code.

Other suggestions:
1. Use filter `text="text_1"` instead of `lambda c: c.data == 'text_1'`
1. Use shortcuts to make your code cleaner. E.g.: `call.answer()`
1. Don't use `async` in a functions without async like `get_inline_event_keyboard`
1. Use correct naming. `CallbackQuery` is a `query` first, not a `call`

**Comment by Olegt0rr** [comment]
@komarp is your issue still actual?

**Comment by FyZzyss** [comment]
@Olegt0rr I got exactly the same error. If I keep two handlers in one module, then everything works. As soon as I migrate the second module with callback_handler it doesn't work
