### ISSUE TITLE
Documentation request: Inline Keyboard example

### ISSUE THREAD

**Issue by Artanicus** [aiogram/aiogram#76]
Currently inline keyboards are only documented as the raw class headers. At least a simple example would be very useful since there's many different functions that seemingly need to be chained to get any useful results.

**Comment by JrooTJunior** [comment]
Related with #51
Thanks for issue.

**Comment by andrewrogow** [comment]
Hi @Artanicus !
Just an example, not a documentation.

```
@dp.message_handler(commands=['start', 'help'])
async def ask_how_r_u(message: types.Message):

    _keyboard = [
        [types.KeyboardButton('Fine')], 
        [types.KeyboardButton('Not bad')],
    ]
    keyboard = types.ReplyKeyboardMarkup(keyboard=_keyboard)

    await message.reply("Hi!\nHow are you?", reply_markup=keyboard)
```

I think the example could be help you😊
But anyway documentation is needed.

**Comment by Latand** [comment]
@andrewrogow, doesn't look like an inline keyboard to me.
