### ISSUE TITLE
TimeoutWarning: Detected slow response into webhook. (Greater than 55 seconds)

### ISSUE THREAD

**Issue by akarsh1995** [aiogram/aiogram#766]
```TimeoutWarning: Detected slow response into webhook. (Greater than 55 seconds)```

```Recommended to use 'async_task' decorator from Dispatcher for handler with long timeouts.```

I think above recommendation does not apply because there is no such request handler that would take 55 seconds to process. 

## Expected Behavior

The bot should be able to reply after throttle lag duration of 4 seconds expires.

## Current Behavior

Bot replies after 55 seconds and warns about the same.

### Steps to Reproduce

1. Google cloud run container with couple of handlers
2. When the first request arrives it takes a 4 seconds to serve the request.
3. I found the request keep coming while the container cold starts.
3. Then sending same/different command multiple times throttles if throttling is applied. I applied throttling of 4 seconds in each handler.
4. The subsequent tg commands sent, after throttling cools down, gets served after 55 seconds.

### Failure Logs

Operating System: Google Cloud Run env Docker Container
Python Version: 3.7
aiogram version: 2.16
aiohttp version: 3.8.1

**Comment by akarsh1995** [comment]
Replying into webhook resolved the issue of late response timeouts 

```SendMessage() #50ms``` instead of ```bot.send_message()```

https://github.com/aiogram/aiogram/blob/910e4d778443436f895326472ab03ab9b4deebb7/examples/webhook_example.py#L34

But I'm still curious why the handler was taking 55 seconds. It should have taken jsut little more than the reply into webhook method.

**Comment by JrooTJunior** [comment]
Timer works correctly, you have slow response in any case, it can be caused if you have slow requests into DB or bad internet connection or doing blocking IO in handlers that stops asyncio event loop for all tasks at all
