### ISSUE TITLE
Command on reply not working.

### ISSUE THREAD

**Issue by Pragma-Edragon** [aiogram/aiogram#773]
## Context

If developer wants to create dispatcher handler with command and with flag `is_reply` - he would not get it.

* Operating System: macOS bigsur/Ubuntu
* Python Version: 3.8
* aiogram version: latest
* aiohttp version: latest
* uvloop version (if installed): -

## Expected Behavior

```
@dispatcher.message_handler(commands=["ban"], is_reply=True)
```
Reply:
```
{"message_id": 695, "from": {"id": 746430418, "is_bot": false, "first_name": "⍰", "username": "rive_n", "language_code": "ru"}, "chat": {"id": -789919652, "title": "test", "type": "group", "all_members_are_administrators": true}, "date": 1639142963, "text": "/respect", "entities": [{"type": "bot_command", "offset": 0, "length": 8}]} None
```

## Current Behavior

As you can see - NONE is representation of `message.reply_to_message`. Using command reply only works on yourself (? why ?) and only on bot. On other users it wont work.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Create dispatcher handler with your own server build.
2. On handler use command with flag `is_reply=True`.
3. On public or private group try to use command on reply. 
4. Add admins and do it again (not working too).

**Comment by evgfilim1** [comment]
Check if you turned off privacy mode for your telegram bot and re-added it to the chat or made it a chat admin.
Also, what does your "Reply:" JSON mean? What is it?

**Comment by Pragma-Edragon** [comment]
I've made it a chat admin. He is able to read all messages and etc. 
But when I am using command reply on bot or myself message - it works. But if i am doing command reply on some user message - it is not.

**Comment by Pragma-Edragon** [comment]
I am talking about this. Imagine User - test, bot - testbot  and another User - testme.
testbot is admin in this group. He can read messages. testme is admin too. 

testme sends message: hello.
testme reply on message <hello> with command: /ban
result: testme banned. 

testbot sends message: test
testme reply on testbot message with command: /ban
result: testbot banned

test send message: test
testme reply on test message with command: /ban
result: aiogram can't match it as reply. For aiogram it's default message

**Comment by Pragma-Edragon** [comment]
The problem was solved as follows:
1.  You must go to botfather and enter the command /setprivacy -> DENY. 
2. Readd your bot 
3. Catch all messages! But this could not work with reply to the bots. Telegram policies blocking it
