### ISSUE TITLE
ValidationError in aiogram 3.0 if I pass a LazyProxy object to a keyboard button text 

### ISSUE THREAD

**Issue by asimaranov** [aiogram/aiogram#783]
The https://github.com/aiogram/aiogram/issues/117 issue reproduces in aiogram 3.0. 
Example code
```python
from aiogram.utils.i18n import lazy_gettext as _

class ExitMenuItem:
    ...
    EXIT = _("Выйти")



inline_exit_keyboard = InlineKeyboardMarkup(keyboard=[[InlineKeyboardButton(text=ExitMenuItem.EXIT)]])
```

Error
```python

  File "pydantic/main.py", line 406, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for InlineKeyboardButton
text
  str type expected (type=type_error.str)
  ```

**Comment by asimaranov** [comment]
[An attempt to fix](https://github.com/aiogram/aiogram/pull/784)

**Comment by gabbhack** [comment]
This is expected behavior.
From [docs](https://docs.aiogram.dev/en/dev-3.x/utils/i18n.html):
> Lazy gettext can’t be used as value for API methods or any Telegram Object (like aiogram.types.inline_keyboard_button.InlineKeyboardButton or etc.)

**Comment by pavelsemko** [comment]
in any buttons?

`pydantic.error_wrappers.ValidationError: 1 validation error for KeyboardButton
text
  str type expected (type=type_error.str)`
