### ISSUE TITLE
Add possibility to choose between search and match in regexp in magic.py

### ISSUE THREAD

**Issue by akantifirst** [aiogram/aiogram#792]
The problem is that sometimes the substring that must be filtered is located not in the beginning of the message, causing filter to fail

**Comment by leirons** [comment]
can you give more details

**Comment by evgfilim1** [comment]
Fixed in https://github.com/aiogram/magic-filter/commit/6ae3eb800aec7992e0a3251a89a4cc0d5ce5b477, make sure you have `magic-filter >= 1.0.6`
