### ISSUE TITLE
Menu-based wizard as a generalization of finite_state_machine

### ISSUE THREAD

**Issue by boyaryn** [aiogram/aiogram#807]
One common use case is a simple wizard, which can be implemented as shown in `examples/finite_state_machine_example.py`.

However, another common use case is when:
* there is no need to choose somethings in all the steps;
* it's more convenient to let a user choose the order in which the steps are 'answered';
* steps can form a tree-like hierarchy.

Is it possible with the current API to implement such menu-based "wizard"?

**Comment by evgfilim1** [comment]
Hello, @boyaryn. If I understand you correctly, there's a project aimed at making aiogram FSM easier to use: [Tishka17/aiogram_dialog](https://github.com/Tishka17/aiogram_dialog). Have a look at it.

**Comment by boyaryn** [comment]
Hello @evgfilim1 , it looks interesting, I'll look at it. Thanks!
