### ISSUE TITLE
Is there a way to send desired logs from python's library `logging` to telegram chat?

### ISSUE THREAD

**Issue by iamtodor** [aiogram/aiogram#821]
**Is your feature request related to a problem? Please describe.**
I have configured logging for the app with a particular format and a few handlers: `TimedRotatingFileHandler`, `StreamHandler`. Now I'd like to send some of the logs to my telegram chat (not all of the logs).
That is being said I need to filter log messages with some extras, such as `logger.info("started working...", extra={"TELEGRAM"})`

I've walked thru the docs https://docs.aiogram.dev/en/latest/telegram/index.html but I didn't find the example or usage of what I'm asking for.

If I miss the doc, please point me on it.
In case additional details have to be provided, please let me know.

Very much looking forward to hearing back from you!

**Comment by evgfilim1** [comment]
Hello. It's not an aiogram issue, it's related only to Python. For more info about logging and its advanced features, refer to docs: https://docs.python.org/3.10/library/logging.html.
