### ISSUE TITLE
[3.x] Error handlers not working

### ISSUE THREAD

**Issue by rdfsx** [aiogram/aiogram#822]
## Context

Error handlers do not work with filters.

* Operating System: ubuntu 21.04
* Python Version: python 3.9.10
* aiogram version: aiogram 3.0.0b1
* aiohttp version: 3.8.1
* uvloop version (if installed): 0.16.0

## Expected Behavior

The error handler catches the error.

## Current Behavior

The error handler does not catch the error.

## Failure Information (for bugs)

Recived `TypeError: __call__() got multiple values for argument 'exception'`

### Steps to Reproduce

1. Create an error handler
2. Register it with some filter, e.g. `dp.errors.register(catch, exception=ZeroDivisionError)`
3. Raise an error in some way, e.g. `await message.answer(f"{5/0}")`

### Failure Logs

[Please include any relevant log snippets or files here.](https://paste.aiogram.dev/ohefuvisiv.sql)

**Comment by JrooTJunior** [comment]
Fixed in Beta 2.
