### ISSUE TITLE
Implement more "reply to webhook" classes

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#823]
After reviewing #804, I've found that some methods aren't implemented as reply to webhook classes.

Missing classes I've discovered:
- [ ] `SendAnimation`
- [ ] `SendPoll`
- [ ] `SendDice`
- [ ] I'm sure there are more to find

_Originally posted by @evgfilim1 in https://github.com/aiogram/aiogram/issues/804#issuecomment-1025686058_

**Comment by JrooTJunior** [comment]
In v3 all methods is classes now.
