### ISSUE TITLE
 Arguments to the command are not passed if you use customize commands prefix

### ISSUE THREAD

**Issue by BorodachevPavel** [aiogram/aiogram#828]
## Context
* Python Version: 3.9
* aiogram version: 2.19
* aiohttp version: 3.8.1

## Expected Behavior

Arguments to the command are not passed if you use customize commands prefix

## Current Behavior
I planned to implement command processing in the bot: <b>!mute 1d</b>

made such handler:
<code>dp.message_handler(AdminFilter(is_chat_admin=True), IsReplyFilter(is_reply=True),
                    commands=['mute'], commands_prefix='!/',
                    chat_type=[types.ChatType.SUPERGROUP, types.ChatType.GROUP])
async def mute(message: types.Message):
    args = message.get_args()</code>

passing the command: <b>!mute 1d</b>
Args is empty. The command does not see the arguments.

**Comment by BorodachevPavel** [comment]
I suspect that this is due to the command check. 
The <code>is_command()</code> method has a check for text.startswith("/")
I can offer PR

**Comment by evgfilim1** [comment]
Duplicates #269
