### ISSUE TITLE
[3.x] skip_updates when start_polling

### ISSUE THREAD

**Issue by MassonNN** [aiogram/aiogram#845]
**Is your feature request related to a problem? Please describe.**
It is commonly known that Telegram Bot API has some strange using of functions, e.g. DeleteWebhook with a parameter drop_pending_updates uses for skip pending updates when you start your bot with polling.

**Describe the solution you'd like**
I suggest to make in 3.x the skip_updates parameter as in 2.x, which will use DeleteWebhook function. But to prevent known bug which will not ignore last update ignore it at a framework side.  

**Describe alternatives you've considered**
May be skip_updates parameter will raise an exception with information about (Dispatcher).delete_webhook(drop_pending_update=True)

**Comment by JrooTJunior** [comment]
Described in migration guide: https://docs.aiogram.dev/en/dev-3.x/migration_2_to_3.html

**Comment by lynrayy** [comment]
My solution
```
async def drop_pending_updates(bot: Bot):
    updates = await bot.get_updates(timeout=0)

    if not updates:
        print("Нет пропущенных апдейтов")
        return

    last_update_id = updates[-1].update_id
    await bot.get_updates(offset=last_update_id + 1)

    print(f"Пропущено апдейтов: {len(updates)}")

async def main():
    await drop_pending_updates(bot)
    try:
        await dp.start_polling(bot)
    finally:
        await bot.send_message(chat_id=..., text="SYSTEM: Выключен.")
```

For me, delete webhook doesn't work and aiogram docs sucks

**Comment by JrooTJunior** [comment]
Dont be rude and feel free to improve docs by yourself through pull requests

**Comment by lynrayy** [comment]
I am still don't know how it intended to skip updates on start. So i can't update the docs
