### ISSUE TITLE
The correct keyword argument name of setup() is “python_requires” instead of “requires_python”

### ISSUE THREAD

**Issue by PyVCEchecker** [aiogram/aiogram#855]
I found the keyword argument **requires_python** is set in the function **setup()**. However, it will not work and will not be reflected in the METADATA. The correct keyword argument should be **python_requires**.

Way to improve:
modify **setup()** in **setup.py,**, remove **requires_python**, and add **python_requires** keyword argument:
```python
setup(…
     python_requires=">=3.7",
     …)
```
Thanks for your attention.
Best regrads,
PyVCEchecker

**Comment by Olegt0rr** [comment]
Confirmed

> `python_requires`
> A string corresponding to a version specifier (as defined in PEP 440) for the Python version, used to specify the Requires-Python defined in PEP 345.

https://setuptools.pypa.io/en/latest/references/keywords.html

**Comment by Vishwa-docs** [comment]
I have worked on and raised a pull request for the same.

**Comment by Olegt0rr** [comment]
Please, tell me: how did you found this bug?! :)

**Comment by PyVCEchecker** [comment]
Recently, we are studying on **Python version constraint error**, which means the declared Python version constraint in **METADATA** is inconsistent with the **actual results**. Such errors can lead to installation failure and runtime failure. We collected some popular Python packages, identified Python version constraint issues, analyzed root causes, and designed algorithms to detect them.
