### ISSUE TITLE
Send content to channel using bot

### ISSUE THREAD

**Issue by neorm5** [aiogram/aiogram#86]
Hi guys,

I'm newbie in aiogram, I want to send data to my channel using bot, I've already add my bot to my channel as administrator, but how can I send content via this package?

Thanks

**Comment by JrooTJunior** [comment]
You need to know channel id or username and then you can sends the messages.

``` python3
MY_CHANNEL = 'myBestChannel'  # or MY_CHANNEL = -10010012345678

await bot.send_message(MY_CHANNEL, "Hello, World!")
```

**Comment by KShukhrat** [comment]
thnks
