### ISSUE TITLE
TimeoutError when call download_by_file_id method

### ISSUE THREAD

**Issue by sephrrr** [aiogram/aiogram#861]
Its about 4 or 5 days im getting this error whenever i call download_by_file_id method. it was never like this before and this caused suddenly without any reason.

note that i didn't update aiogram for a year and im using py 3.6

**Comment by JrooTJunior** [comment]
You have an network issues, check your connection.

**Comment by sephrrr** [comment]
> You have an network issues, check your connection.

There is no network issue as i contact my server administrator. i think there is problem with telegram api ...

**Comment by evgfilim1** [comment]
Does it work now?
