### ISSUE TITLE
Simple script that sends a message raises `RuntimeError: Event loop is closed` on Windows

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#863]
## Context

* Operating System: Windows 10
* Python Version: 3.9, 3.10
* aiogram version: 2.19, 3.0.0b2
* aiohttp version: 3.8.1

## Expected Behavior

Process finishes gracefully

## Current Behavior

```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x00000207916D4040>
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\user\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

### Steps to Reproduce

```python
import asyncio

from aiogram import Bot

TOKEN = ""  # put your token here
CHAT_ID = 0  # put your user ID here


async def main():
    bot = Bot(TOKEN)
    await bot.send_message(CHAT_ID, "Hello there!")
    await bot.session.close()  # replace with `await bot.close()` on 2.x
    # await asyncio.sleep(0.1)


if __name__ == '__main__':
    asyncio.run(main())

```

If you uncomment `sleep` method, it works fine and finishes without traceback. I guess the problem is in aiohttp.
**The message is delivered anyway**, with or without `sleep`

**Comment by evgfilim1** [comment]
Related:
aio-libs/aiohttp#6635 (same problem)
https://docs.aiohttp.org/en/stable/client_advanced.html#graceful-shutdown (workaround is described in docs)
aio-libs/aiohttp#1925 (original issue, fixed and will be available in aiohttp>=4.0.0)

**Comment by gabbhack** [comment]
Also related: https://bugs.python.org/issue39232
Another workaround: https://github.com/encode/httpx/issues/914#issuecomment-622586610

**Comment by DenisNagornuyk** [comment]
It's worked!

**Comment by JrooTJunior** [comment]
Fixed in v3
