### ISSUE TITLE
Spoiler formatting is not supported

### ISSUE THREAD

**Issue by prepwork** [aiogram/aiogram#865]
https://github.com/aiogram/aiogram/blob/79588b7c5d3168e8baa5c91e6b0592f629a64269/aiogram/utils/text_decorations.py#L58

## Context

aiogram 3.x

## Expected Behavior

Message.html_text and Message.md_text return fully unparsed raw representation of the formatted message text.

## Current Behavior

Message.html_text and Message.md_text don't take in account spoiler entities. Spoiler entities are simply ignored.

**Comment by evgfilim1** [comment]
Hello, @prepwork.

Can you be more clear on this issue? Please, fill in the issue template below.

```
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System:
* Python Version: 
* aiogram version: 
* aiohttp version: 
* uvloop version (if installed): 

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.
```

**Comment by JrooTJunior** [comment]
Thanks for information, will be fixed in Beta 3.
