### ISSUE TITLE
unable to create web_app button

### ISSUE THREAD

**Issue by NQUAREx** [aiogram/aiogram#891]
Good afternoon, an update has recently been released in telegram and added web_app buttons. leading to the "site" in the telegram itself, the documentation says that you need to import the script to the page and create a button in the bot

Html:
```
<html><head>
<script src="https://telegram.org/js/telegram-web-app.js"></script>
</head></html>
```
code for sending a message with a button:
```
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton
from aiogram.types.web_app_info import WebAppInfo
await msg.reply("test", reply_markup=InlineKeyboardMarkup().add(InlineKeyboardButton(text="test", web_app=WebAppInfo(url="https://test_link"))))
```
Error:
```
Button_type_invalid
```
thanks in advance for your help)

Source: https://stackoverflow.com/questions/71914783/unable-to-create-web-app-button-aiogram

**Comment by JrooTJunior** [comment]
WebApp can only be used in private chats.
When you try to send WebApp button in group, supergroup or channel you will get this error.

**Comment by NQUAREx** [comment]
I'm not going to send her to the group, this error comes out exactly when I send her to a private chat.
Please show a working example of how to do it correctly

**Comment by evgfilim1** [comment]
> I'm not going to send her to the group, this error comes out exactly when I send her to a private chat. Please show a working example of how to do it correctly

@NQUAREx send us a minimal reproducible example. It's like a minimum needed code to reproduce this issue which I can just copy-paste and run (adding or changing a token or making some other host-specific changes).

**Comment by NQUAREx** [comment]
Oh my God, you won't believe it, but it worked! Nothing worked with the same code yesterday. Magic!
Here is the code I tested:
'''
from aiogram import Bot, Dispatcher, executor, types
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton
from aiogram.types.web_app_info import WebAppInfo

API_TOKEN = 'your bot api token'

bot = Bot(token=API_TOKEN)
dp = Dispatcher(bot)

@dp.message_handler(commands="start")
async def cmd_start(message: types.Message):
	await message.answer("test", reply_markup=InlineKeyboardMarkup().add(InlineKeyboardButton(text="test", web_app=WebAppInfo(url="https://github.com/aiogram/aiogram/issues/891"))))

if __name__ == '__main__':
    executor.start_polling(dp, skip_updates=True)
'''

**Comment by NQUAREx** [comment]
Thanks.

Magic.......
