### ISSUE TITLE
`ForceReply` doesn't work

### ISSUE THREAD

**Issue by rdfsx** [aiogram/aiogram#901]
## Context

ForceReply does not provide a reply

* Operating System: ubuntu 20.04
* Python Version: 3.9
* aiogram version: 3.0.0b3
* aiohttp version: 3.8.1
* uvloop version (if installed): 0.16.0

## Expected Behavior

ForceReply provide a reply

## Current Behavior

ForceReply does not provide a reply

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Just try to run this code:

```python
import logging

from aiogram import Bot, Dispatcher, Router
from aiogram.types import Message, ForceReply

TOKEN = ""
dp = Dispatcher()

router = Router()

logger = logging.getLogger(__name__)


@router.message(commands={"start"})
async def command_start_handler(message: Message) -> None:
    await message.answer(f"Hello, <b>{message.from_user.full_name}!</b>", reply_markup=ForceReply(force_reply=True))


def main() -> None:
    bot = Bot(TOKEN, parse_mode="HTML")

    dp.include_router(router)
    dp.run_polling(bot, )


if __name__ == "__main__":
    main()
```

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by JrooTJunior** [comment]
Reproduced.

Description: https://pydantic-docs.helpmanual.io/usage/model_config/#smart-union

`pydantic` always tries to coerce `Union` type, for example in this case `ForceReply` converted to `ReplyKeyboardRemove(remove_keyboard=True, selective=None)`. :thinking:

Interesting case.
