### ISSUE TITLE
Can't send sticker from created sticker set 3.0.0b3

### ISSUE THREAD

**Issue by mishimastar** [aiogram/aiogram#914]
Bot can't send a sticker from created/existing sticker set. It sends sticker as `.png` file, instead of sticker object(or as `.webp`, I'm not sure).
I'm using *aiogram 3.0.0b3*

I'm uploading new sticker with `bot` method `upload_sticker_file` : 
```python
new_sticker = await bot.upload_sticker_file(
                    user_id=query.from_user.id, 
                    png_sticker=FSInputFile(f'stickers/new/{query.from_user.id}.webp'),
    )
```
So I got `aiogram.types.file.File`  object  named `new_sticker`.

Then I check if there is a sticker set created for current user by my bot. 
If it exists, I add the pre-loaded sticker to the set.
If it doesn't exist, I create a new one by adding a preloaded sticker.

I'm using `new_sticker.file_id` (`aiogram.types.file.File.file_id` ) attribute to pass into `bot.add_sticker_to_set` / `bot.create_new_sticker_set` methods:
```python
    try:
        sSet = await bot.get_sticker_set(f'{query.from_user.username}_by_ASCIIStickersBot')
        if await bot.add_sticker_to_set(
                user_id=query.from_user.id,
                name=f'{query.from_user.username}_by_ASCIIStickersBot',
                emojis=auth_conf['Emoji'][f'{query.from_user.id}'],
                png_sticker=new_sticker.file_id,
        ):
            print(f'Added sticker to sticker pack, named {query.from_user.username}_by_ASCIIStickersBot')
            await bot.send_sticker(query.from_user.id, new_sticker.file_id)
        else:
            print(f'error while adding sticker to set named {query.from_user.username}_by_ASCIIStickersBot')
    except:
        if await bot.create_new_sticker_set(
            user_id=query.from_user.id,
            name=f'{query.from_user.username}_by_ASCIIStickersBot',
            title='ASCII Art Stickers',
            emojis=auth_conf['Emoji'][f'{query.from_user.id}'],
            png_sticker=new_sticker.file_id,
        ):
            print(f'created new sticker pack, named {query.from_user.username}_by_ASCIIStickersBot')
            await bot.send_message(chat_id=query.from_user.id, text=f"Your new sticker set!\nhttps://t.me/addstickers/{query.from_user.username}_by_ASCIIStickersBot", parse_mode='HTML')
            await bot.send_sticker(query.from_user.id, new_sticker.file_id)
        else:
            print('smth went wrong')
```

_Bot can correctly create new sticker sets and add stickers to them_

So user got reply like that:

<img src="https://raw.githubusercontent.com/mishimastar/tg-stickers-ascii-art/master/doc/bad_example.png" alt="bad_example" width="50%" />

I tried to use `bot.upload_sticker_file` with `.webp` and `.png` files. It didn't change anything, including the `.png` file type in reply.

I want the user to see the response like this:

<img src="https://raw.githubusercontent.com/mishimastar/tg-stickers-ascii-art/master/doc/good_example.png" alt="good_example" width="50%" />

Now, im using `bot.send_document` method to get good(not really) result:
```python
await bot.send_document(query.from_user.id, FSInputFile(f'stickers/new/{query.from_user.id}.webp'))
```
I'm not satisfied with this result, because I have to upload a file that already exists on the server a second time and the user can't click on the sticker to open the preview of the sticker pack (later add it to his own).

**Is there any way to send sticker from existing sticker set as sticker object not as document/file?**

*One extra question*:
Sending stickers in the `.webp` format is more efficient than in the `.png` because of `.webp` compression. 
Every time I'm downloading existing stickers with *aiogram 3.0.0b3* from Telegram servers with:
```python
await bot.download(message.sticker.file_id)
```

or with *aiogram 2.9.2:*
```python
await message.sticker.download(f'stickers/old/')
```
I got `<downloaded_sticker_name>.webp` file.
Why does the user receive a response in the form of a `.png` file when sending a sticker using the `bot.send_sticker` method?

**Thank you so much for your hard work!**

**Comment by JrooTJunior** [comment]
Not in our side, expected undocumented behaviour of the Bot API Server.
