### ISSUE TITLE
Aiogram not allowing exception handling after ip address change whilst bot is still running

### ISSUE THREAD

**Issue by LikeMoneySecretly** [aiogram/aiogram#916]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Windows 11
* Python Version: 3.10.4
* aiogram version: Up to date
* aiohttp version: Latest version as of writing
* uvloop version (if installed): not installed

After the ip address is changed by the /switchip command a networkError and client OS Error is thrown, I should be able to catch these errors and act upon them (however I currently cannot no matter the wrappers for these errors that I use), I've tried catching for WinError catching for ClientError, catching for Network Error (after of course importing these errors into the code) 
Even catching for Exception isn't catching these errors, see gyazo photographs for more information
![image](https://user-images.githubusercontent.com/6726423/172488750-0e9021a1-191e-4ea6-abc0-e1877e0d362b.png)

## Current Behavior

See above, uncatchable error is thrown
![image](https://user-images.githubusercontent.com/6726423/172488822-ca901f89-49ef-4f8d-8d38-a89008e5dd0a.png)

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Change ip address whilst aiogram is running
2. A client OS Error and then a network Error is thrown
3. Errors aren't caught by anything/uncatchable

### Failure Logs
```
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiogram\bot\api.py", line 139, in make_request
    async with session.post(url, data=req, **kwargs) as response:
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client.py", line 559, in _request
    await resp.start(conn)
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "C:\Users\USER\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\aiohttp\streams.py", line 616, in read
aiogram.utils.exceptions.NetworkError: Aiohttp client throws an error: ClientOSError: [WinError 64] The specified network name is no longer available
```

**Comment by LikeMoneySecretly** [comment]
I would like to point out none of the print's in https://gyazo.com/0a69965423eed8c325ffe5cfa2ed51ba are triggered, so the error is clearly not being caught at all by any of them even though you would expect at least the network Error to be caught by the outer catch block. The outer catch block does catch issues to do with not having a wifi connection (i.e. if I try to connect to telegram with no internet the `except Network Error:` code is thrown however the error is not thrown in this case here

**Comment by LikeMoneySecretly** [comment]
Thirdly, the bot is still running even after the error is thrown. As in I have to still close the bot with Cntrl+C in the visual studio box. Which is another thing that is slightly odd, is it not a true Error being thrown here or what? Is it just a spammy text notification of a problem?

**Comment by JrooTJunior** [comment]
Generally this issue is not related to the `aiogram` directly because this error thrown from OS, then re-raised by `aiohttp` and then re-raised from `aiogram`.

Also you don't need to catch this error in this place because `aiogram` catch any connection errors inside long-polling process and retry after some sleep.

https://github.com/aiogram/aiogram/blob/a0fb37a54de3232213a9a6e1182490a422834ad4/aiogram/dispatcher/dispatcher.py#L379-L392

---

Also you should answer to yourself some questions:
1. Why you are changing the ip address of network interface? It's something weird and should not be used in production.
2. Why you are using Windows on production (or not using but trying to solve platform-specific errors)? 

---
Please don't use any external services in GutHub Issues, you can paste images or code directly in the message.

**Comment by JrooTJunior** [comment]
I'll close this issue, if you have additional questions you can re-open this issue or create new-one
