### ISSUE TITLE
Prevent handlers from cancelling

### ISSUE THREAD

**Issue by jemeraldo** [aiogram/aiogram#919]
Perhaps I have gaps in understanding aiogram, but why can't I make handler cancellation protection?

```
import asyncio
import logging
import os

from aiogram import Bot, Dispatcher, types

#API_TOKEN = os.getenv("BOT_TOKEN")
API_TOKEN = "TOKEN"

# Configure logging
logging.basicConfig(level=logging.INFO)

# Initialize bot and dispatcher
bot = Bot(token=API_TOKEN)
dp = Dispatcher(bot)

def shielded(fn):
    async def wrapped(*args, **kwargs):
        await asyncio.shield(fn(*args, **kwargs))

    return wrapped


@dp.message_handler()
@shielded
async def echo(message: types.Message, *args, **kwargs):
    try:
        await asyncio.sleep(7)
        await message.answer(message.text)
    except asyncio.CancelledError:
        print("handler cancelled :(")

async def cancel_dp_with_delay(dp, sec):
    await asyncio.sleep(sec)
    dp.stop_polling()
    


async def main():
    asyncio.create_task(cancel_dp_with_delay(dp, 5))
    await dp.start_polling()
    await dp.wait_closed()
    await asyncio.sleep(3)

if __name__ == '__main__':
    asyncio.run(main())
```

**Comment by JrooTJunior** [comment]
What do you mean?

`stop_polling` doesn't cancel handlers.
This method is only break infinity loop (`while self._polling:` do `getUpdates`) method but not the event handlers.
wait_closed waits until polling process will be stopped, that's mean until all already started handlers or long getUpdates requests is finished

**Comment by jemeraldo** [comment]
> `stop_polling` doesn't cancel handlers. This method is only break infinity loop (`while self._polling:` do `getUpdates`) method but not the event handlers. wait_closed waits until polling process will be stopped, that's mean until all already started handlers or long getUpdates requests is finished

Following this logic, while running code above, we should receive message from echo handler if we stop polling during handler execution, right? But I got CancelledError.

**Comment by jemeraldo** [comment]
It seems like there is some magic, but now it works for me too. Maybe I run version of this code before, where I didn't wait some time after stop polling, but I defenitly received CancelledError some way.

Anyway, I really appreciate you answers, ty.
