### ISSUE TITLE
commands for channel_post_handler

### ISSUE THREAD

**Issue by a72** [aiogram/aiogram#933]
## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Operating System: linux
* Python Version:  3.9
* aiogram version: 2.21
* aiohttp version: 3.8.1
* uvloop version (if installed): 

when running the code:
```
@dp.channel_post_handler(commands=['start'])
async def chanel_echo(message: types.Message):
    await message.answer(message.text)

```
error:
```
Traceback (most recent call last):
  File "src/py/tgbot_test/tg_aiogram.py", line 48, in <module>
    async def chanel_echo(message: types.Message):
  File ".local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 661, in decorator
    self.register_channel_post_handler(callback, *custom_filters, commands=commands, regexp=regexp,
  File ".local/lib/python3.9/site-packages/aiogram/dispatcher/dispatcher.py", line 636, in register_channel_post_handler
    filters_set = self.filters_factory.resolve(self.channel_post_handlers,
  File ".local/lib/python3.9/site-packages/aiogram/dispatcher/filters/factory.py", line 51, in resolve
    filters_set = list(
  File ".local/lib/python3.9/site-packages/aiogram/dispatcher/filters/factory.py", line 77, in _resolve_registered
    raise NameError("Invalid filter name(s): '" + "', ".join(full_config.keys()) + "'")
NameError: Invalid filter name(s): 'commands'
```

**Comment by evgfilim1** [comment]
Are commands really needed in a channel?
I think it's bad style, but if you really need it, you can import `Command` directly from `aiogram.dispatcher.filters` and use it like `@dp.channel_post_handler(Command(commands="start"))`

**Comment by a72** [comment]
> Are commands really needed in a channel? I think it's bad style, but if you really need it, you can import `Command` directly from `aiogram.dispatcher.filters` and use it like `@dp.channel_post_handler(Command(commands="start"))`

this option works

```
@dp.channel_post_handler(Command(['start', 'buy'], prefixes='!/'))
```
this one doesn't work

**Comment by draklowell** [comment]
> @dp.channel_post_handler(Command(['start', 'buy'], prefixes='!/'))

Can't reproduce the problem. This code works ok:
```python
from aiogram import Bot, Dispatcher
from aiogram.dispatcher.filters.builtin import Command
from aiogram import types
from aiogram.utils.executor import start_polling

bot = Bot(TOKEN)
dp = Dispatcher(bot)

@dp.channel_post_handler(Command(['start', 'buy'], prefixes='!/'))
async def test(message: types.Message):
    print(message.text)

start_polling(dp)
```

Python 3.8.10
Ubuntu 20.04.4 LTS
Aiogram 2.21
