### ISSUE TITLE
Webhook example for 3.x

### ISSUE THREAD

**Issue by Masynchin** [aiogram/aiogram#946]
**Is your feature request related to a problem? Please describe.**
there is no example with webhook for 3.x version of aiogram.

**Describe the solution you'd like**
Webhook example same as for 2.x version.

**Comment by JrooTJunior** [comment]
We have two examples with webhook:
1. With multibot: https://github.com/aiogram/aiogram/blob/dev-3.x/examples/multibot.py
2. With webapp example: https://github.com/aiogram/aiogram/blob/dev-3.x/examples/web_app/main.py

But it's a good point to have example named like `webhook.py`

**Comment by Masynchin** [comment]
I think this should be added to https://github.com/aiogram/aiogram/projects/3#column-18991685

**Comment by evgfilim1** [comment]
> I think this should be added to https://github.com/aiogram/aiogram/projects/3#column-18991685.

Off-topic here, not related to webhook example

**Comment by JrooTJunior** [comment]
Completed: https://docs.aiogram.dev/en/dev-3.x/dispatcher/webhook.html
