### ISSUE TITLE
Add missing enums, check existing ones, drop helpers

### ISSUE THREAD

**Issue by evgfilim1** [aiogram/aiogram#952]
## Enums in the API

- [x] `ChatType`: _Type of chat, can be either “private”, “group”, “supergroup” or “channel”_
- [x] `MessageEntityType`: _Type of the entity. Currently, can be “mention” (@username), “hashtag” (#hashtag), “cashtag” ($USD), “bot_command” (/start@jobs_bot), “url” (https://telegram.org), “email” (do-not-reply@telegram.org), “phone_number” (+1-212-555-0123), “bold” (bold text), “italic” (italic text), “underline” (underlined text), “strikethrough” (strikethrough text), “spoiler” (spoiler message), “code” (monowidth string), “pre” (monowidth block), “text_link” (for clickable text URLs), “text_mention” (for users [without usernames](https://telegram.org/blog/edit#new-mentions))_
- [x] `DiceEmoji`: _Currently, must be one of “🎲”, “🎯”, “🏀”, “⚽”, “🎳”, or “🎰”._
- [x] `PollType`: _Poll type, currently can be “regular” or “quiz”_
- [x] `ChatMemberStatus`
- [x] `BotCommandScopeType`
- [x] `MenuButtonType`
- [x] `InputMediaType`
- [x] `ParseMode`: _MarkdownV2, Markdown, HTML_
- [x] `ChatAction` (#803): _Type of action to broadcast. Choose one, depending on what the user is about to receive: typing for [text messages](https://core.telegram.org/bots/api#sendmessage), upload_photo for [photos](https://core.telegram.org/bots/api#sendphoto), record_video or upload_video for [videos](https://core.telegram.org/bots/api#sendvideo), record_voice or upload_voice for [voice notes](https://core.telegram.org/bots/api#sendvoice), upload_document for [general files](https://core.telegram.org/bots/api#senddocument), choose_sticker for [stickers](https://core.telegram.org/bots/api#sendsticker), find_location for [location data](https://core.telegram.org/bots/api#sendlocation), record_video_note or upload_video_note for [video notes](https://core.telegram.org/bots/api#sendvideonote)._
- [x] `MaskPositionPoint`: _The part of the face relative to which the mask should be placed. One of “forehead”, “eyes”, “mouth”, or “chin”._
- [x] `InlineQueryChatType` (merge with `ChatType`?): _Optional. Type of the chat from which the inline query was sent. Can be either “sender” for a private chat with the inline query sender, “private”, “group”, “supergroup”, or “channel”. The chat type should be always known for requests sent from official clients and most third-party clients, unless the request was sent from a secret chat_
- [x] `InlineQueryResultType`
- [ ] `EncryptedPassportElementType` (move to `PassportElementType`?): _Element type. One of “personal_details”, “passport”, “driver_license”, “identity_card”, “internal_passport”, “address”, “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”, “temporary_registration”, “phone_number”, “email”._
- [ ] `PassportElementErrorSource`
- [ ] `PassportElementErrorDataFieldType` (so long :/, merge to `PassportElementType`?): _The section of the user's Telegram Passport which has the error, one of “personal_details”, “passport”, “driver_license”, “identity_card”, “internal_passport”, “address”_
- [ ] `PassportElementErrorFrontSideType` (same): _The section of the user's Telegram Passport which has the issue, one of “passport”, “driver_license”, “identity_card”, “internal_passport”_
- [ ] `PassportElementErrorReverseSideType` (same): _The section of the user's Telegram Passport which has the issue, one of “driver_license”, “identity_card”_
- [ ] ...`ErrorSelfieType` (same): _The section of the user's Telegram Passport which has the issue, one of “passport”, “driver_license”, “identity_card”, “internal_passport”_
- [ ] ...`ErrorFileType` (same): _The section of the user's Telegram Passport which has the issue, one of “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”, “temporary_registration”_
- [ ] ...`ErrorFilesType` (huh?, same): _The section of the user's Telegram Passport which has the issue, one of “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”, “temporary_registration”_
- [ ] ...`ErrorTranslationFileType` (same): _Type of element of the user's Telegram Passport which has the issue, one of “passport”, “driver_license”, “identity_card”, “internal_passport”, “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”, “temporary_registration”_
- [ ] ...`ErrorTranslationFilesType` (same): _Type of element of the user's Telegram Passport which has the issue, one of “passport”, “driver_license”, “identity_card”, “internal_passport”, “utility_bill”, “bank_statement”, “rental_agreement”, “passport_registration”, “temporary_registration”_

## Custom enums

- [x] `ContentType`: `Message` fields
- [x] `UpdateType` (maybe): `Update` fields

**Comment by JrooTJunior** [comment]
This issue now is pinned on top of all issues, as the main priority for Beta 6 is aliases/shortcuts for methods in types.

In general, it is planned to re-implement code generation based on declarative configuration for types, methods, shortcuts.

The second goal is an auto-generation of Enums for common set of values (like chat type, dice emojies and etc.).

**Comment by evgfilim1** [comment]
Related: https://github.com/aiogram/tg-codegen/issues/11
