### ISSUE TITLE
Default state is not None

### ISSUE THREAD

**Issue by Masynchin** [aiogram/aiogram#954]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Context

- Operating system: macOS 12.4
- Python Version: 3.10.4
- aiogram version: 3.0.0b3
- aiohttp version: 3.8.1

### Expected behavior

No answer.

### Current behavior

Bot answers with "Use /first"

### Steps to reproduce

1) Send "/first".
2) Send any.

### Code example

```python3
import os

from aiogram import Bot, Dispatcher
from aiogram.dispatcher.fsm.storage.memory import MemoryStorage
from aiogram.dispatcher.fsm.state import State, StatesGroup
from aiogram.dispatcher.fsm.storage.memory import MemoryStorage


bot = Bot(token=os.getenv("BOT_TOKEN"))
dp = Dispatcher(storage=MemoryStorage())


class FirstState(StatesGroup):
    first = State()


@dp.message(commands=["first"])
async def first(message, state):
    await state.set_state(FirstState.first)
    await message.answer("Set to first!")


@dp.message()
async def unrecognized(message, state):
    await message.answer("Use /first")


dp.run_polling(bot)
```

### Additional information

This error doesn't happen in aiogram 2. I think this is because in aiogram 2 handers default state is set to None. If yes, how can aiogram 3 handlers copy this behaviour?

**Comment by Masynchin** [comment]
There will be good if you can add documentation about migrating FSM handlers from 2.x to 3.x. If my suggestion about default state is right, it would be good if you will document it. Also about FSM documentation, can routers solve my issue? There is no any practical information about routers purpose in docs.

**Comment by evgfilim1** [comment]
Hello, @Masynchin. Yes, this is the default behavior in 3.x, no filtering by state is done in any way, so you have to use `state=None` explicitly. Note that keyword filters will be deprecated and removed soon, so it's better to use `StateFilter(state=None)` directly (import it from `aiogram.dispatcher.filters`).

I don't see this behavior is documented, so thanks for your suggestion.

**Comment by Masynchin** [comment]
> It's better to use `StateFilter(state=None)` directly (import it from `aiogram.dispatcher.filters`).

Thanks for this tip.
