### ISSUE TITLE
Found a small typo on your docs.

### ISSUE THREAD

**Issue by siflaneur** [aiogram/aiogram#96]
https://aiogram.readthedocs.io/en/latest/examples/adwanced_executor_example.html
Title:<del>adwanced</del>

**Comment by JrooTJunior** [comment]
> **It's not a bug, it's a feature.**

Yep. I know about that typo :smiley:

---
From official russian comunity: [@aiogram_ru#37216](https://t.me/aiogram_ru/37216)
> that was the secret meaning
> I specifically do not refactor it
> because it is so bad that even good

---
If you want you can create pull-request with fix
