### ISSUE TITLE
`GetChatMemberCount` vs `GetChatMembersCount` in the 3.x docs

### ISSUE THREAD

**Issue by MassonNN** [aiogram/aiogram#965]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

n/a

### Python version

n/a

### aiogram version

3.0

### Expected behavior

Only getChatMemberCount page in methods docs is exists

### Current behavior

getChatMembersCount and getChatMemberCount pages are exists

### Steps to reproduce

1. Open 3.x docs
2. Open "Bot API" page
3. Open "Methods" page
4. See the misspell

### Additional information

https://docs.aiogram.dev/en/dev-3.x/api/methods/get_chat_member_count.html
https://docs.aiogram.dev/en/dev-3.x/api/methods/get_chat_members_count.html

**Comment by evgfilim1** [comment]
It's not really a bug because one of the changes introduced in Bot API 5.3 was renaming `getChatMembersCount` to `getChatMemberCount`: https://core.telegram.org/bots/api-changelog#june-25-2021

**Comment by evgfilim1** [comment]
It might be a good suggestion to remove backwards-compatibility methods from docs as 3.0 would be "brand new" version without any need for such methods, so I'm reopening it.

@aiogram/dev-team what do you think?

**Comment by Olegt0rr** [comment]
It seems redundant. I vote to remove old name
