### ISSUE TITLE
Let the SOCKS proxy to resolve hostname

### ISSUE THREAD

**Issue by phrolov** [aiogram/aiogram#97]
The problem is if the telegram api is blocked by provider then in some cases you can not connect to telegram because of redirection (rewriting dns by provider? i don't know).

The solution is to resolve hostname by socks proxy. `aiohttp_socks ` `SocksConnecto`r has the special parameter `rdns` which allows to do this.

It would be great to have ability to specify this option as parameter in `Bot` constructor.

**Comment by makmaks217artibo** [comment]
aiogram/.гитхаб/ISSUE_TEMPLATE/bug_report.МД
