### ISSUE TITLE
Dispatcher does not register handlers from another modules (where dispatcher has not been initialized)

### ISSUE THREAD

**Issue by FyZzyss** [aiogram/aiogram#974]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

MacOS 12.3.1

### Python version

3.10.5

### aiogram version

2.21

### Expected behavior

Handlers will be registered in all modules where dispatcher was imported.

### Current behavior

Handlers are registered only in the module where dispatcher was initialized.

### Steps to reproduce

1. Create main module
2. Create another module
3. Write some handlers
4. Try to call handlers from another module

### Code example

```python3
# first main file(tg.py)
from aiogram import types, Dispatcher, Bot
from aiogram.contrib.fsm_storage.memory import MemoryStorage
from aiogram.utils import executor

bot = Bot(token='token', parse_mode=types.ParseMode.MARKDOWN_V2)
dispatcher = Dispatcher(bot, storage=MemoryStorage())


@dispatcher.message_handler(commands=["test"])
async def command_method(message: types.Message) -> None:
    keyboard = types.InlineKeyboardMarkup()
    keyboard.add(types.InlineKeyboardButton('press me', callback_data='some_data'))
    await message.answer(text='test message', reply_markup=keyboard)


if __name__ == "__main__":
    executor.start_polling(dispatcher)
```

```python3
# second file, all handlers not working

from aiogram import types

from tg import dispatcher


@dispatcher.callback_query_handler(lambda callback: True)
async def callback_method(callback_query: types.CallbackQuery):
    await callback_query.message.answer('ok')


@dispatcher.message_handler(commands=["start"])
async def command_method2(message: types.Message) -> None:
    await message.answer(text='test1')
```

**Comment by evgfilim1** [comment]
Hello, @FyZzyss, and thanks for asking a question.
Unfortunately, this doesn't work such way, and it's not aiogram error. If you want to make a “modular” aiogram v2 bot, see #522.

When you're trying to import something from `tg.py` inside `second.py`, and you're running `tg.py`, `second.py` won't magically run just because it is in the same project. That's how imports work in Python.
