### ISSUE TITLE
Specifying python version 3.7 in the documentation as valid

### ISSUE THREAD

**Issue by romanolegov** [aiogram/aiogram#981]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Windows 11

### Python version

3.7

### aiogram version

3.0.0b4

### Expected behavior

The documentation should indicate the minimum versions of the essential dependencies. Since aiogram 2.x is developed and supports python 3.7 on the main page I expect to see a statement that version 3.7 is no longer supported. Aiogram 3.0.0b4 will not install on python 3.7, because the requirements file specifies Requires-Python: >=3.8,<4.0

### Current behavior

Now on the https://docs.aiogram.dev/en/dev-3.x/ page, the image reference block states the minimum version 3.7 and nowhere else does it say that version 3.7 is not supported. Specifying 'written in Python 3.8' does not mean 'requres Python 3.8' - for example, '[python 2.7+ and 3.4+ (developed with 3.6)](http://docs.peewee-orm.com/en/latest/)'.

### Steps to reproduce

Execute pip install -U aiogram on Python 3.7

**Comment by Olegt0rr** [comment]
Since `shields.io` uses `pypi` version, it shows current stable version badges (2.x)
