### ISSUE TITLE
lock bot to user(s) - filter on message.from_user.id?

### ISSUE THREAD

**Issue by cmorgan** [aiogram/aiogram#99]
Is that the most secure way to lock a bot down to a user?
Are there any examples of such a Filter?
Is it possible to Filter by group? e.g. is the group id available anywhere in Message context?
cheers!

**Comment by denisazevedo** [comment]
I'm not sure if this is the best way to implement it, but this is what I'm doing:

`@dp.message_handler(lambda msg: msg.from_user.username in ALLOWED_USERS)`

Where `ALLOWED_USERS` is an array of strings.
