### ISSUE TITLE
Fix filters constructor arguments

### ISSUE THREAD

**Issue by TrixiS** [aiogram/aiogram#993]
### Checklist

- [X] I am sure the error is coming from aiogram code
- [X] I have searched in the issue tracker for similar bug reports, including closed ones

### Operating system

Ubuntu 20.04 LTS

### Python version

3.10.4

### aiogram version

Latest from dev-3.x branch

### Expected behavior

No `__call__` argument in filter subclass constructors

### Current behavior

`BaseFilter` subclasses have `*, __call__: (...) -> Awaitable[bool | Dict[str, Any]]` in their `__init__` arguments

### Steps to reproduce

Copy the code below

### Code example

```python3
from aiogram.filters import BaseFilter


class SomeFilter(BaseFilter):
    async def __call__(self, *args):
        ...


# BaseFilter is a subclass of pydantic.BaseModel
# so it refers __call__ function in constructor
# (class) SomeFilter(*, __call__: (...) -> Awaitable[bool | Dict[str, Any]])

# Argument missing for parameter "__call__"
filter_inst = SomeFilter()
```

**Comment by TrixiS** [comment]
And why is `BaseFilter` a subclass of `pydantic.BaseModel`?

**Comment by evgfilim1** [comment]
> `Argument missing for parameter "__call__"`

I guess this may be a bug of your linter not recognizing BaseModel properly.

> And why is `BaseFilter` a subclass of `pydantic.BaseModel`?

This helps bound filters to work properly, which are deprecated, see #942.

**Comment by JrooTJunior** [comment]
This issue is not relevant and not in our side.

This is the problem with your linter, sometimes it can take false-positive errors with pydantic models.
In due to #942 we don't do anything additional to resolve this issue because from Beta 5 pydantic will no more be used for filters base class.
